CREATE OR REPLACE VIEW FIDE_ESTADOS_V AS
SELECT
    ID_ESTADO,
    NOMBRE_ESTADO
FROM FIDE_ESTADOS_TB;


CREATE OR REPLACE VIEW FIDE_TIPOTARJETAS_V AS
SELECT
    ID_TIPOTARJETA,
    COLOR,
    ID_ESTADO
FROM FIDE_TIPOTARJETAS_TB;


CREATE OR REPLACE VIEW FIDE_CANTONES_V AS
SELECT
    ID_CANTON,
    NOMBRE_CANTON,
    ID_ESTADO
FROM FIDE_CANTONES_TB;

/

CREATE OR REPLACE VIEW FIDE_CARGOS_V AS
SELECT
    ID_CARGO,
    NOMBRE_CARGO,
    ID_ESTADO
FROM FIDE_CARGOS_TB;

/

CREATE OR REPLACE VIEW FIDE_CATEGORIAS_V AS
SELECT
    ID_CATEGORIA,
    NOMBRE_CATEGORIA,
    ID_ESTADO
FROM FIDE_CATEGORIAS_TB;

/

CREATE OR REPLACE VIEW FIDE_CATEGORIA_INVENTARIO_V AS
SELECT
    ID_CATEGORIAINVENTARIO,
    NOMBRE_CATEGORIA_INVENTARIO,
    ID_ESTADO
FROM FIDE_CATEGORIA_INVENTARIO_TB;

/

CREATE OR REPLACE VIEW FIDE_DISTRITOS_V AS
SELECT
    ID_DISTRITO,
    NOMBRE_DISTRITO,
    ID_ESTADO
FROM FIDE_DISTRITOS_TB;

/


CREATE OR REPLACE VIEW FIDE_ESPECIALIDADES_V AS
SELECT
    ID_ESPECIALIDAD,
    NOMBRE_ESPECIALIDAD,
    ID_ESTADO
FROM FIDE_ESPECIALIDADES_TB;


/

CREATE OR REPLACE VIEW FIDE_POSICIONES_V AS
SELECT
    ID_POSICION,
    NOMBRE_POSICION,
    ID_ESTADO
FROM FIDE_POSICIONES_TB;

/

CREATE OR REPLACE VIEW FIDE_PROVINCIAS_V AS
SELECT
    ID_PROVINCIA,
    NOMBRE_PROVINCIA,
    ID_ESTADO
FROM FIDE_PROVINCIAS_TB;


/

CREATE OR REPLACE VIEW FIDE_TEMPORADAS_V AS
SELECT
    ID_TEMPORADA,
    TIPO_TEMPORADA,
    ANIO,
    ID_ESTADO
FROM FIDE_TEMPORADAS_TB;

/

CREATE OR REPLACE VIEW FIDE_TIPOLESION_V AS
SELECT
    ID_TIPOLESION,
    NOMBRE_TIPO_LESION,
    ID_ESTADO
FROM FIDE_TIPOLESION_TB;


/

CREATE OR REPLACE VIEW FIDE_TIPO_PARTIDOS_V AS
SELECT
    ID_TIPOPARTIDOS,
    TIPO_DE_PARTIDO,
    ID_ESTADO
FROM FIDE_TIPO_PARTIDOS_TB;

/

CREATE OR REPLACE VIEW FIDE_ARTICULOS_V AS
SELECT
    ID_ARTICULO,
    ID_CATEGORIAINVENTARIO,
    ID_ESTADO,
    CANTIDAD,
    NOMBRE_ARTICULO
FROM FIDE_ARTICULOS_TB;

/


CREATE OR REPLACE VIEW FIDE_DIRECCION_EXACTA_V AS
SELECT
    ID_DIRECCION_EXACTA,
    OTRAS_SENIAS,
    ID_DISTRITO,
    ID_CANTON,
    ID_PROVINCIA,
    ID_ESTADO
FROM FIDE_DIRECCION_EXACTA_TB;

/


CREATE OR REPLACE VIEW FIDE_MEDICOS_V AS
SELECT
    ID_MEDICO,
    NOMBRE,
    APELLIDO_PATERNO,
    APELLIDO_MATERNO,
    ID_ESPECIALIDAD,
    ID_ESTADO
FROM FIDE_MEDICOS_TB;

/


CREATE OR REPLACE VIEW FIDE_EMPLEADOS_V AS
SELECT
    ID_EMPLEADO,
    NOMBRE,
    APELLIDO_PATERNO,
    APELLIDO_MATERNO,
    EDAD,
    NOMBRE_DE_USUARIO,
    CONTRASENIA,
    ID_CARGO,
    ID_DIRECCION_EXACTA,
    ID_ESTADO
FROM FIDE_EMPLEADOS_TB;

/



CREATE OR REPLACE VIEW FIDE_JUGADORES_V AS
SELECT
    ID_JUGADOR,
    ID_CATEGORIA,
    NOMBRE,
    APELLIDO_MATERNO,
    APELLIDO_PATERNO,
    DORSAL,
    FECHA_NACIMIENTO,
    ID_ESTADO,
    ID_DIRECCION_EXACTA
FROM FIDE_JUGADORES_TB;

/



CREATE OR REPLACE VIEW FIDE_FACTURACION_INSCRIPCIONES_V AS
SELECT
    ID_FACTURACION_INSCRIPCION,
    ID_JUGADOR,
    MES,
    ANIO,
    MONTO,
    FECHA_PAGO,
    ID_ESTADO,
    OBSERVACIONES
FROM FIDE_FACTURACION_INSCRIPCIONES_TB;

/


CREATE OR REPLACE VIEW FIDE_SEDES_V AS
SELECT
    ID_SEDE,
    NOMBRE_SEDE,
    ID_DIRECCION_EXACTA,
    ID_ESTADO
FROM FIDE_SEDES_TB;

/


CREATE OR REPLACE VIEW FIDE_JUGADOR_POSICIONES_V AS
SELECT
    ID_JUGADOR,
    ID_POSICION
FROM FIDE_JUGADOR_POSICIONES_TB;

/


CREATE OR REPLACE VIEW FIDE_PARTE_MEDICO_V AS
SELECT
    ID_PARTEMEDICO,
    ID_JUGADOR,
    OBSERVACIONES,
    FECHA,
    ID_MEDICO,
    ID_ESTADO
FROM FIDE_PARTE_MEDICO_TB;

/


CREATE OR REPLACE VIEW FIDE_PARTIDOS_V AS
SELECT
    ID_PARTIDO,
    ID_CATEGORIA,
    ID_TIPOPARTIDOS,
    ID_TEMPORADA,
    FECHA,
    RIVAL,
    GOLES_FAVOR,
    GOLES_CONTRA,
    ID_SEDE,
    ID_ESTADO
FROM FIDE_PARTIDOS_TB;

/


CREATE OR REPLACE VIEW FIDE_REVISION_FISICA_V AS
SELECT
    ID_REVISION,
    ID_JUGADOR,
    PESO,
    IMC,
    ALTURA,
    FECHA_REVISION,
    ID_ESTADO
FROM FIDE_REVISION_FISICA_TB;

/


CREATE OR REPLACE VIEW FIDE_TELEFONOS_V AS
SELECT
    ID_TELEFONO,
    NUMERO_TELEFONO,
    ID_EMPLEADO,
    ID_ESTADO
FROM FIDE_TELEFONOS_TB;

/


CREATE OR REPLACE VIEW FIDE_ASISTENCIA_V AS
SELECT
    ID_PARTIDO,
    ID_JUGADOR,
    ID_ESTADO
FROM FIDE_ASISTENCIA_TB;

/


CREATE OR REPLACE VIEW FIDE_ESTADISTICA_EQUIPO_V AS
SELECT
    ID_ESTADISTICA_EQUIPO,
    TIROS,
    TIROS_PORTERIA,
    PASES_EXITOSOS,
    PASES_FALLIDOS,
    POSESION_BALON,
    ID_PARTIDO,
    ID_ESTADO
FROM FIDE_ESTADISTICA_EQUIPO_TB;

/


CREATE OR REPLACE VIEW FIDE_ESTADISTICA_JUGADOR_V AS
SELECT
    ID_ESTADISTICA_JUGADOR,
    ID_JUGADOR,
    ID_PARTIDO,
    PASES,
    PASES_EXITOSOS,
    REGATES,
    REGATES_EXITOSOS,
    TIROS,
    TIROS_EXITOSOS,
    ENTRADAS,
    ENTRADAS_EXITOSAS,
    MINUTOS_JUGADOS,
    GOLES,
    ASISTENCIAS,
    ID_ESTADO
FROM FIDE_ESTADISTICA_JUGADOR_TB;

/


CREATE OR REPLACE VIEW FIDE_LESIONES_V AS
SELECT
    ID_LESION,
    DESCRIPCION,
    FECHA_RECUPERACION,
    ID_TIPOLESION,
    ID_PARTEMEDICO,
    ID_ESTADO
FROM FIDE_LESIONES_TB;

/


CREATE OR REPLACE VIEW FIDE_TARJETAS_V AS
SELECT
    ID_PARTIDO,
    ID_JUGADOR,
    ID_TIPOTARJETA,
    CANTIDAD_TARJETAS
FROM FIDE_TARJETAS_TB;

/


CREATE OR REPLACE VIEW FIDE_DETALLE_JUGADORES_V AS
SELECT 
    J.ID_JUGADOR,
    J.NOMBRE,
    J.APELLIDO_PATERNO,
    J.APELLIDO_MATERNO,
    J.DORSAL,
    J.FECHA_NACIMIENTO,
    C.NOMBRE_CATEGORIA,
    E.NOMBRE_ESTADO
FROM FIDE_JUGADORES_TB J
INNER JOIN FIDE_CATEGORIAS_TB C
    ON J.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FIDE_ESTADOS_TB E
    ON J.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_DETALLE_PARTIDOS_V AS
SELECT
    P.ID_PARTIDO,
    P.FECHA,
    P.RIVAL,
    P.GOLES_FAVOR,
    P.GOLES_CONTRA,
    C.NOMBRE_CATEGORIA,
    T.TIPO_DE_PARTIDO,
    TE.TIPO_TEMPORADA,
    TE.ANIO,
    S.NOMBRE_SEDE,
    E.NOMBRE_ESTADO
FROM FIDE_PARTIDOS_TB P
INNER JOIN FIDE_CATEGORIAS_TB C
    ON P.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FIDE_TIPO_PARTIDOS_TB T
    ON P.ID_TIPOPARTIDOS = T.ID_TIPOPARTIDOS
INNER JOIN FIDE_TEMPORADAS_TB TE
    ON P.ID_TEMPORADA = TE.ID_TEMPORADA
INNER JOIN FIDE_SEDES_TB S
    ON P.ID_SEDE = S.ID_SEDE
INNER JOIN FIDE_ESTADOS_TB E
    ON P.ID_ESTADO = E.ID_ESTADO;
   
   / 
    
CREATE OR REPLACE VIEW FIDE_DETALLE_ESTADISTICAS_JUGADOR_V AS
SELECT
    EJ.ID_ESTADISTICA_JUGADOR,
    J.ID_JUGADOR,
    J.NOMBRE,
    J.APELLIDO_PATERNO,
    J.APELLIDO_MATERNO,
    P.ID_PARTIDO,
    P.FECHA,
    P.RIVAL,
    EJ.MINUTOS_JUGADOS,
    EJ.GOLES,
    EJ.ASISTENCIAS,
    EJ.PASES,
    EJ.PASES_EXITOSOS,
    EJ.REGATES,
    EJ.REGATES_EXITOSOS,
    EJ.TIROS,
    EJ.TIROS_EXITOSOS,
    EJ.ENTRADAS,
    EJ.ENTRADAS_EXITOSAS,
    E.NOMBRE_ESTADO
FROM FIDE_ESTADISTICA_JUGADOR_TB EJ
INNER JOIN FIDE_JUGADORES_TB J
    ON EJ.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_PARTIDOS_TB P
    ON EJ.ID_PARTIDO = P.ID_PARTIDO
INNER JOIN FIDE_ESTADOS_TB E
    ON EJ.ID_ESTADO = E.ID_ESTADO;
  
  /
    
CREATE OR REPLACE VIEW FIDE_FACTURACION_JUGADORES_V AS
SELECT
    F.ID_FACTURACION_INSCRIPCION,
    J.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS JUGADOR,
    C.NOMBRE_CATEGORIA,
    F.MES,
    F.ANIO,
    F.MONTO,
    F.FECHA_PAGO,
    F.OBSERVACIONES,
    E.NOMBRE_ESTADO
FROM FIDE_FACTURACION_INSCRIPCIONES_TB F
INNER JOIN FIDE_JUGADORES_TB J
    ON F.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_CATEGORIAS_TB C
    ON J.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FIDE_ESTADOS_TB E
    ON F.ID_ESTADO = E.ID_ESTADO;
   
 /  
    
CREATE OR REPLACE VIEW FIDE_LESIONES_JUGADORES_V AS
SELECT
    L.ID_LESION,
    J.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS JUGADOR,
    TL.NOMBRE_TIPO_LESION,
    L.DESCRIPCION,
    PM.FECHA AS FECHA_PARTE_MEDICO,
    L.FECHA_RECUPERACION,
    M.NOMBRE || ' ' || M.APELLIDO_PATERNO AS MEDICO,
    ESP.NOMBRE_ESPECIALIDAD,
    E.NOMBRE_ESTADO
FROM FIDE_LESIONES_TB L
INNER JOIN FIDE_TIPOLESION_TB TL
    ON L.ID_TIPOLESION = TL.ID_TIPOLESION
INNER JOIN FIDE_PARTE_MEDICO_TB PM
    ON L.ID_PARTEMEDICO = PM.ID_PARTEMEDICO
INNER JOIN FIDE_JUGADORES_TB J
    ON PM.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_MEDICOS_TB M
    ON PM.ID_MEDICO = M.ID_MEDICO
INNER JOIN FIDE_ESPECIALIDADES_TB ESP
    ON M.ID_ESPECIALIDAD = ESP.ID_ESPECIALIDAD
INNER JOIN FIDE_ESTADOS_TB E
    ON L.ID_ESTADO = E.ID_ESTADO;

/

CREATE OR REPLACE VIEW FIDE_CALENDARIO_PARTIDOS_V AS
SELECT
    P.ID_PARTIDO,
    P.FECHA,
    P.RIVAL,
    P.GOLES_FAVOR,
    P.GOLES_CONTRA,
    CASE
        WHEN P.GOLES_FAVOR > P.GOLES_CONTRA THEN 'Victoria'
        WHEN P.GOLES_FAVOR < P.GOLES_CONTRA THEN 'Derrota'
        ELSE 'Empate'
    END AS RESULTADO,
    C.NOMBRE_CATEGORIA,
    TP.TIPO_DE_PARTIDO,
    T.TIPO_TEMPORADA,
    T.ANIO,
    S.NOMBRE_SEDE,
    E.NOMBRE_ESTADO
FROM FIDE_PARTIDOS_TB P
INNER JOIN FIDE_CATEGORIAS_TB C
    ON P.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FIDE_TIPO_PARTIDOS_TB TP
    ON P.ID_TIPOPARTIDOS = TP.ID_TIPOPARTIDOS
INNER JOIN FIDE_TEMPORADAS_TB T
    ON P.ID_TEMPORADA = T.ID_TEMPORADA
INNER JOIN FIDE_SEDES_TB S
    ON P.ID_SEDE = S.ID_SEDE
INNER JOIN FIDE_ESTADOS_TB E
    ON P.ID_ESTADO = E.ID_ESTADO;

