
PROCEDURE FIDE_ESTADOS_TB_INSERTAR_SP(
    P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
    P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO FIDE_ESTADOS_TB(ID_ESTADO, NOMBRE_ESTADO)
    VALUES(P_ID_ESTADO, P_NOMBRE_ESTADO);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);    
END FIDE_ESTADOS_TB_INSERTAR_SP;

PROCEDURE FIDE_ESTADOS_TB_MODIFICAR_SP(
    P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
    P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_ESTADOS_TB
    SET NOMBRE_ESTADO = P_NOMBRE_ESTADO
    WHERE ID_ESTADO = P_ID_ESTADO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR DATOS: ' || SQLERRM);    
END FIDE_ESTADOS_TB_MODIFICAR_SP;

PROCEDURE FIDE_ESTADOS_TB_ELIMINAR_SP(
    P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
    P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_ESTADOS_TB
    SET NOMBRE_ESTADO = P_NOMBRE_ESTADO
    WHERE ID_ESTADO = P_ID_ESTADO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR DATOS: ' || SQLERRM);    
END FIDE_ESTADOS_TB_ELIMINAR_SP;

PROCEDURE FIDE_TIPOTARJETAS_TB_INSERTAR_SP(
    P_ID_TIPOTARJETA IN FIDE_TIPOTARJETAS_TB.ID_TIPOTARJETA%TYPE,
    P_COLOR IN FIDE_TIPOTARJETAS_TB.COLOR%TYPE,
    P_ID_ESTADO IN FIDE_TIPOTARJETAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO FIDE_TIPOTARJETAS_TB(ID_TIPOTARJETA, COLOR, ID_ESTADO)
    VALUES(P_ID_TIPOTARJETA, P_COLOR, P_ID_ESTADO);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR DATOS: ' || SQLERRM);    
END FIDE_TIPOTARJETAS_TB_INSERTAR_SP;

PROCEDURE FIDE_TIPOTARJETAS_TB_MODIFICAR_SP(
    P_ID_TIPOTARJETA IN FIDE_TIPOTARJETAS_TB.ID_TIPOTARJETA%TYPE,
    P_COLOR IN FIDE_TIPOTARJETAS_TB.COLOR%TYPE,
    P_ID_ESTADO IN FIDE_TIPOTARJETAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_TIPOTARJETAS_TB
    SET COLOR = P_COLOR,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_TIPOTARJETA = P_ID_TIPOTARJETA;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR DATOS: ' || SQLERRM);    
END FIDE_TIPOTARJETAS_TB_MODIFICAR_SP;

PROCEDURE FIDE_TIPOTARJETAS_TB_ELIMINAR_SP(
    P_ID_TIPOTARJETA IN FIDE_TIPOTARJETAS_TB.ID_TIPOTARJETA%TYPE,
    P_ID_ESTADO IN FIDE_TIPOTARJETAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_TIPOTARJETAS_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_TIPOTARJETA = P_ID_TIPOTARJETA;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR DATOS: ' || SQLERRM);
END FIDE_TIPOTARJETAS_TB_ELIMINAR_SP;

PROCEDURE FIDE_CANTONES_TB_INSERTAR_SP(
    P_ID_CANTON IN FIDE_CANTONES_TB.ID_CANTON%TYPE,
    P_NOMBRE_CANTON IN FIDE_CANTONES_TB.NOMBRE_CANTON%TYPE,
    P_ID_ESTADO IN FIDE_CANTONES_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO FIDE_CANTONES_TB(ID_CANTON, NOMBRE_CANTON, ID_ESTADO)
    VALUES(P_ID_CANTON, P_NOMBRE_CANTON, P_ID_ESTADO);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CANTONES_TB_INSERTAR_SP;

PROCEDURE FIDE_CANTONES_TB_MODIFICAR_SP(
    P_ID_CANTON IN FIDE_CANTONES_TB.ID_CANTON%TYPE,
    P_NOMBRE_CANTON IN FIDE_CANTONES_TB.NOMBRE_CANTON%TYPE,
    P_ID_ESTADO IN FIDE_CANTONES_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_CANTONES_TB
    SET NOMBRE_CANTON = P_NOMBRE_CANTON,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_CANTON = P_ID_CANTON;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CANTONES_TB_MODIFICAR_SP;

PROCEDURE FIDE_CANTONES_TB_ELIMINAR_SP(
    P_ID_CANTON IN FIDE_CANTONES_TB.ID_CANTON%TYPE,
    P_ID_ESTADO IN FIDE_CANTONES_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_CANTONES_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_CANTON = P_ID_CANTON;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CANTONES_TB_ELIMINAR_SP;

PROCEDURE FIDE_CARGOS_TB_INSERTAR_SP(
    P_ID_CARGO IN FIDE_CARGOS_TB.ID_CARGO%TYPE,
    P_NOMBRE_CARGO IN FIDE_CARGOS_TB.NOMBRE_CARGO%TYPE,
    P_ID_ESTADO IN FIDE_CARGOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO FIDE_CARGOS_TB(ID_CARGO, NOMBRE_CARGO, ID_ESTADO)
    VALUES(P_ID_CARGO, P_NOMBRE_CARGO, P_ID_ESTADO);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CARGOS_TB_INSERTAR_SP;

PROCEDURE FIDE_CARGOS_TB_MODIFICAR_SP(
    P_ID_CARGO IN FIDE_CARGOS_TB.ID_CARGO%TYPE,
    P_NOMBRE_CARGO IN FIDE_CARGOS_TB.NOMBRE_CARGO%TYPE,
    P_ID_ESTADO IN FIDE_CARGOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_CARGOS_TB
    SET NOMBRE_CARGO = P_NOMBRE_CARGO,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_CARGO = P_ID_CARGO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CARGOS_TB_MODIFICAR_SP;

PROCEDURE FIDE_CARGOS_TB_ELIMINAR_SP(
    P_ID_CARGO IN FIDE_CARGOS_TB.ID_CARGO%TYPE,
    P_ID_ESTADO IN FIDE_CARGOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_CARGOS_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_CARGO = P_ID_CARGO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CARGOS_TB_ELIMINAR_SP;

PROCEDURE FIDE_CATEGORIAS_TB_INSERTAR_SP(
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE,
    P_NOMBRE_CATEGORIA IN FIDE_CATEGORIAS_TB.NOMBRE_CATEGORIA%TYPE,
    P_ID_ESTADO IN FIDE_CATEGORIAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO FIDE_CATEGORIAS_TB(ID_CATEGORIA, NOMBRE_CATEGORIA, ID_ESTADO)
    VALUES(P_ID_CATEGORIA, P_NOMBRE_CATEGORIA, P_ID_ESTADO);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CATEGORIAS_TB_INSERTAR_SP;

PROCEDURE FIDE_CATEGORIAS_TB_MODIFICAR_SP(
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE,
    P_NOMBRE_CATEGORIA IN FIDE_CATEGORIAS_TB.NOMBRE_CATEGORIA%TYPE,
    P_ID_ESTADO IN FIDE_CATEGORIAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_CATEGORIAS_TB
    SET NOMBRE_CATEGORIA = P_NOMBRE_CATEGORIA,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CATEGORIAS_TB_MODIFICAR_SP;

PROCEDURE FIDE_CATEGORIAS_TB_ELIMINAR_SP(
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE,
    P_ID_ESTADO IN FIDE_CATEGORIAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_CATEGORIAS_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CATEGORIAS_TB_ELIMINAR_SP;

PROCEDURE FIDE_CATEGORIA_INVENTARIO_TB_INSERTAR_SP(
    P_ID_CATEGORIAINVENTARIO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_CATEGORIAINVENTARIO%TYPE,
    P_NOMBRE_CATEGORIA_INVENTARIO IN FIDE_CATEGORIA_INVENTARIO_TB.NOMBRE_CATEGORIA_INVENTARIO%TYPE,
    P_ID_ESTADO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO FIDE_CATEGORIA_INVENTARIO_TB(ID_CATEGORIAINVENTARIO, NOMBRE_CATEGORIA_INVENTARIO, ID_ESTADO)
    VALUES(P_ID_CATEGORIAINVENTARIO, P_NOMBRE_CATEGORIA_INVENTARIO, P_ID_ESTADO);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CATEGORIA_INVENTARIO_TB_INSERTAR_SP;

PROCEDURE FIDE_CATEGORIA_INVENTARIO_TB_MODIFICAR_SP(
    P_ID_CATEGORIAINVENTARIO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_CATEGORIAINVENTARIO%TYPE,
    P_NOMBRE_CATEGORIA_INVENTARIO IN FIDE_CATEGORIA_INVENTARIO_TB.NOMBRE_CATEGORIA_INVENTARIO%TYPE,
    P_ID_ESTADO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_CATEGORIA_INVENTARIO_TB
    SET NOMBRE_CATEGORIA_INVENTARIO = P_NOMBRE_CATEGORIA_INVENTARIO,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_CATEGORIAINVENTARIO = P_ID_CATEGORIAINVENTARIO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CATEGORIA_INVENTARIO_TB_MODIFICAR_SP;

PROCEDURE FIDE_CATEGORIA_INVENTARIO_TB_ELIMINAR_SP(
    P_ID_CATEGORIAINVENTARIO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_CATEGORIAINVENTARIO%TYPE,
    P_ID_ESTADO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_CATEGORIA_INVENTARIO_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_CATEGORIAINVENTARIO = P_ID_CATEGORIAINVENTARIO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_CATEGORIA_INVENTARIO_TB_ELIMINAR_SP;

PROCEDURE FIDE_DISTRITOS_TB_INSERTAR_SP(
    P_ID_DISTRITO IN FIDE_DISTRITOS_TB.ID_DISTRITO%TYPE,
    P_NOMBRE_DISTRITO IN FIDE_DISTRITOS_TB.NOMBRE_DISTRITO%TYPE,
    P_ID_ESTADO IN FIDE_DISTRITOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO FIDE_DISTRITOS_TB(ID_DISTRITO, NOMBRE_DISTRITO, ID_ESTADO)
    VALUES(P_ID_DISTRITO, P_NOMBRE_DISTRITO, P_ID_ESTADO);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_DISTRITOS_TB_INSERTAR_SP;

PROCEDURE FIDE_DISTRITOS_TB_MODIFICAR_SP(
    P_ID_DISTRITO IN FIDE_DISTRITOS_TB.ID_DISTRITO%TYPE,
    P_NOMBRE_DISTRITO IN FIDE_DISTRITOS_TB.NOMBRE_DISTRITO%TYPE,
    P_ID_ESTADO IN FIDE_DISTRITOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_DISTRITOS_TB
    SET NOMBRE_DISTRITO = P_NOMBRE_DISTRITO,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_DISTRITO = P_ID_DISTRITO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_DISTRITOS_TB_MODIFICAR_SP;

PROCEDURE FIDE_DISTRITOS_TB_ELIMINAR_SP(
    P_ID_DISTRITO IN FIDE_DISTRITOS_TB.ID_DISTRITO%TYPE,
    P_ID_ESTADO IN FIDE_DISTRITOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_DISTRITOS_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_DISTRITO = P_ID_DISTRITO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_DISTRITOS_TB_ELIMINAR_SP;

PROCEDURE FIDE_ESPECIALIDADES_TB_INSERTAR_SP(
    P_ID_ESPECIALIDAD IN FIDE_ESPECIALIDADES_TB.ID_ESPECIALIDAD%TYPE,
    P_NOMBRE_ESPECIALIDAD IN FIDE_ESPECIALIDADES_TB.NOMBRE_ESPECIALIDAD%TYPE,
    P_ID_ESTADO IN FIDE_ESPECIALIDADES_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO FIDE_ESPECIALIDADES_TB(ID_ESPECIALIDAD, NOMBRE_ESPECIALIDAD, ID_ESTADO)
    VALUES(P_ID_ESPECIALIDAD, P_NOMBRE_ESPECIALIDAD, P_ID_ESTADO);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_ESPECIALIDADES_TB_INSERTAR_SP;

PROCEDURE FIDE_ESPECIALIDADES_TB_MODIFICAR_SP(
    P_ID_ESPECIALIDAD IN FIDE_ESPECIALIDADES_TB.ID_ESPECIALIDAD%TYPE,
    P_NOMBRE_ESPECIALIDAD IN FIDE_ESPECIALIDADES_TB.NOMBRE_ESPECIALIDAD%TYPE,
    P_ID_ESTADO IN FIDE_ESPECIALIDADES_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_ESPECIALIDADES_TB
    SET NOMBRE_ESPECIALIDAD = P_NOMBRE_ESPECIALIDAD,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_ESPECIALIDAD = P_ID_ESPECIALIDAD;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_ESPECIALIDADES_TB_MODIFICAR_SP;

PROCEDURE FIDE_ESPECIALIDADES_TB_ELIMINAR_SP(
    P_ID_ESPECIALIDAD IN FIDE_ESPECIALIDADES_TB.ID_ESPECIALIDAD%TYPE,
    P_ID_ESTADO IN FIDE_ESPECIALIDADES_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_ESPECIALIDADES_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_ESPECIALIDAD = P_ID_ESPECIALIDAD;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_ESPECIALIDADES_TB_ELIMINAR_SP;

PROCEDURE FIDE_POSICIONES_TB_INSERTAR_SP(
    P_ID_POSICION IN FIDE_POSICIONES_TB.ID_POSICION%TYPE,
    P_NOMBRE_POSICION IN FIDE_POSICIONES_TB.NOMBRE_POSICION%TYPE,
    P_ID_ESTADO IN FIDE_POSICIONES_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO FIDE_POSICIONES_TB(ID_POSICION, NOMBRE_POSICION, ID_ESTADO)
    VALUES(P_ID_POSICION, P_NOMBRE_POSICION, P_ID_ESTADO);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_POSICIONES_TB_INSERTAR_SP;

PROCEDURE FIDE_POSICIONES_TB_MODIFICAR_SP(
    P_ID_POSICION IN FIDE_POSICIONES_TB.ID_POSICION%TYPE,
    P_NOMBRE_POSICION IN FIDE_POSICIONES_TB.NOMBRE_POSICION%TYPE,
    P_ID_ESTADO IN FIDE_POSICIONES_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_POSICIONES_TB
    SET NOMBRE_POSICION = P_NOMBRE_POSICION,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_POSICION = P_ID_POSICION;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_POSICIONES_TB_MODIFICAR_SP;

PROCEDURE FIDE_POSICIONES_TB_ELIMINAR_SP(
    P_ID_POSICION IN FIDE_POSICIONES_TB.ID_POSICION%TYPE,
    P_ID_ESTADO IN FIDE_POSICIONES_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_POSICIONES_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_POSICION = P_ID_POSICION;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_POSICIONES_TB_ELIMINAR_SP;

PROCEDURE FIDE_PROVINCIAS_TB_INSERTAR_SP(
    P_ID_PROVINCIA IN FIDE_PROVINCIAS_TB.ID_PROVINCIA%TYPE,
    P_NOMBRE_PROVINCIA IN FIDE_PROVINCIAS_TB.NOMBRE_PROVINCIA%TYPE,
    P_ID_ESTADO IN FIDE_PROVINCIAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO FIDE_PROVINCIAS_TB(ID_PROVINCIA, NOMBRE_PROVINCIA, ID_ESTADO)
    VALUES(P_ID_PROVINCIA, P_NOMBRE_PROVINCIA, P_ID_ESTADO);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_PROVINCIAS_TB_INSERTAR_SP;

PROCEDURE FIDE_PROVINCIAS_TB_MODIFICAR_SP(
    P_ID_PROVINCIA IN FIDE_PROVINCIAS_TB.ID_PROVINCIA%TYPE,
    P_NOMBRE_PROVINCIA IN FIDE_PROVINCIAS_TB.NOMBRE_PROVINCIA%TYPE,
    P_ID_ESTADO IN FIDE_PROVINCIAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_PROVINCIAS_TB
    SET NOMBRE_PROVINCIA = P_NOMBRE_PROVINCIA,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_PROVINCIA = P_ID_PROVINCIA;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_PROVINCIAS_TB_MODIFICAR_SP;

PROCEDURE FIDE_PROVINCIAS_TB_ELIMINAR_SP(
    P_ID_PROVINCIA IN FIDE_PROVINCIAS_TB.ID_PROVINCIA%TYPE,
    P_ID_ESTADO IN FIDE_PROVINCIAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_PROVINCIAS_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_PROVINCIA = P_ID_PROVINCIA;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: LA CONSULTA DEVOLVIO MULTIPLES FILAS');
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DATOS: ' || SQLERRM);
END FIDE_PROVINCIAS_TB_ELIMINAR_SP;


PROCEDURE FIDE_TIPOLESION_TB_INSERTAR_SP(
	P_ID_TIPOLESION IN FIDE_TIPOLESION_TB.ID_TIPOLESION%TYPE,
	P_NOMBRE_TIPO_LESION IN FIDE_TIPOLESION_TB.NOMBRE_TIPO_LESION%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_TIPOLESION_TB(ID_TIPOLESION, NOMBRE_TIPO_LESION, ID_ESTADO)
	VALUES(P_ID_TIPOLESION, P_NOMBRE_TIPO_LESION, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
        	DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
        WHEN DUP_VAL_ON_INDEX THEN
        	DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
        WHEN VALUE_ERROR THEN
        	DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_TIPOLESION_TB_INSERTAR_SP;

PROCEDURE FIDE_TIPOLESION_TB_MODIFICAR_SP(
	P_ID_TIPOLESION IN FIDE_TIPOLESION_TB.ID_TIPOLESION%TYPE,
	P_NOMBRE_TIPO_LESION IN FIDE_TIPOLESION_TB.NOMBRE_TIPO_LESION%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_TIPOLESION_TB
	SET NOMBRE_TIPO_LESION = P_NOMBRE_TIPO_LESION,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_TIPOLESION = P_ID_TIPOLESION;
	
	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE LESION.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TIPO DE LESION ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
    	WHEN VALUE_ERROR THEN
        	DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
    	WHEN OTHERS THEN
        	DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_TIPOLESION_TB_MODIFICAR_SP;


PROCEDURE FIDE_TIPOLESION_TB_ELIMINAR_SP(
	P_ID_TIPOLESION IN FIDE_TIPOLESION_TB.ID_TIPOLESION%TYPE
)IS
BEGIN 
	UPDATE FIDE_TIPOLESION_TB
	SET ID_ESTADO=2
	WHERE ID_TIPOLESION = P_ID_TIPOLESION;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE LESION.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TIPO DE LESION ELIMINADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL TIPO DE LESION.');
END FIDE_TIPOLESION_TB_ELIMINAR_SP;

PROCEDURE FIDE_TEMPORADAS_TB_INSERTAR_SP(
	P_ID_TEMPORADA IN FIDE_TEMPORADAS_TB.ID_TEMPORADA%TYPE,
	P_TIPO_TEMPORADA IN FIDE_TEMPORADAS_TB.TIPO_TEMPORADA%TYPE,
	P_ANIO IN FIDE_TEMPORADAS_TB.ANIO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_TEMPORADAS_TB(ID_TEMPORADA, TIPO_TEMPORADA, ANIO, ID_ESTADO)
	VALUES(P_ID_TEMPORADA, P_TIPO_TEMPORADA, P_ANIO, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_TEMPORADAS_TB_INSERTAR_SP;

PROCEDURE FIDE_TEMPORADAS_TB_MODIFICAR_SP(
	P_ID_TEMPORADA IN FIDE_TEMPORADAS_TB.ID_TEMPORADA%TYPE,
	P_TIPO_TEMPORADA IN FIDE_TEMPORADAS_TB.TIPO_TEMPORADA%TYPE,
	P_ANIO IN FIDE_TEMPORADAS_TB.ANIO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_TEMPORADAS_TB
	SET TIPO_TEMPORADA = P_TIPO_TEMPORADA,
	ANIO = P_ANIO,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_TEMPORADA = P_ID_TEMPORADA;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE TEMPORADA.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TEMPORADA ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_TEMPORADAS_TB_MODIFICAR_SP;

PROCEDURE FIDE_TEMPORADAS_TB_ELIMINAR_SP(
	P_ID_TEMPORADA IN FIDE_TEMPORADAS_TB.ID_TEMPORADA%TYPE
)IS
BEGIN
	UPDATE FIDE_TEMPORADAS_TB
	SET ID_ESTADO = 2
	WHERE ID_TEMPORADA = P_ID_TEMPORADA;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE TEMPORADA.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TEMPORADA ELIMINADO LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_TEMPORADAS_TB_ELIMINAR_SP;

PROCEDURE FIDE_TIPO_PARTIDOS_TB_INSERTAR_SP(
	P_ID_TIPOPARTIDOS IN FIDE_TIPO_PARTIDOS_TB.ID_TIPOPARTIDOS%TYPE,
	P_TIPO_DE_PARTIDO IN FIDE_TIPO_PARTIDOS_TB.TIPO_DE_PARTIDO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_TIPO_PARTIDOS_TB(ID_TIPOPARTIDOS, TIPO_DE_PARTIDO, ID_ESTADO)
	VALUES(P_ID_TIPOPARTIDOS, P_TIPO_DE_PARTIDO, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_TIPO_PARTIDOS_TB_INSERTAR_SP;

PROCEDURE FIDE_TIPO_PARTIDOS_TB_MODIFICAR_SP(
	P_ID_TIPOPARTIDOS IN FIDE_TIPO_PARTIDOS_TB.ID_TIPOPARTIDOS%TYPE,
	P_TIPO_DE_PARTIDO IN FIDE_TIPO_PARTIDOS_TB.TIPO_DE_PARTIDO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_TIPO_PARTIDOS_TB
	SET TIPO_DE_PARTIDO = P_TIPO_DE_PARTIDO,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_TIPOPARTIDOS = P_ID_TIPOPARTIDOS;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE TIPO DE PARTIDO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TIPO DE PARTIDO ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_TIPO_PARTIDOS_TB_MODIFICAR_SP;

PROCEDURE FIDE_TIPO_PARTIDOS_TB_ELIMINAR_SP(
	P_ID_TIPOPARTIDOS IN FIDE_TIPO_PARTIDOS_TB.ID_TIPOPARTIDOS%TYPE
)IS
BEGIN
	UPDATE FIDE_TIPO_PARTIDOS_TB
	SET ID_ESTADO = 2
	WHERE ID_TIPOPARTIDOS = P_ID_TIPOPARTIDOS;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE TIPO DE PARTIDO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TIPO DE PARTIDO ELIMINADO LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_TIPO_PARTIDOS_TB_ELIMINAR_SP;

PROCEDURE FIDE_ARTICULOS_TB_INSERTAR_SP(
	P_ID_ARTICULO IN FIDE_ARTICULOS_TB.ID_ARTICULO%TYPE,
	P_ID_CATEGORIAINVENTARIO IN FIDE_ARTICULOS_TB.ID_CATEGORIAINVENTARIO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
	P_CANTIDAD IN FIDE_ARTICULOS_TB.CANTIDAD%TYPE,
	P_NOMBRE_ARTICULO IN FIDE_ARTICULOS_TB.NOMBRE_ARTICULO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_ARTICULOS_TB(ID_ARTICULO, ID_CATEGORIAINVENTARIO, ID_ESTADO, CANTIDAD, NOMBRE_ARTICULO)
	VALUES(P_ID_ARTICULO, P_ID_CATEGORIAINVENTARIO, P_ID_ESTADO, P_CANTIDAD, P_NOMBRE_ARTICULO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_ARTICULOS_TB_INSERTAR_SP;

PROCEDURE FIDE_ARTICULOS_TB_MODIFICAR_SP(
	P_ID_ARTICULO IN FIDE_ARTICULOS_TB.ID_ARTICULO%TYPE,
	P_ID_CATEGORIAINVENTARIO IN FIDE_ARTICULOS_TB.ID_CATEGORIAINVENTARIO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
	P_CANTIDAD IN FIDE_ARTICULOS_TB.CANTIDAD%TYPE,
	P_NOMBRE_ARTICULO IN FIDE_ARTICULOS_TB.NOMBRE_ARTICULO%TYPE
)IS
BEGIN
	UPDATE FIDE_ARTICULOS_TB
	SET ID_CATEGORIAINVENTARIO = P_ID_CATEGORIAINVENTARIO,
	ID_ESTADO = P_ID_ESTADO,
	CANTIDAD = P_CANTIDAD,
	NOMBRE_ARTICULO = P_NOMBRE_ARTICULO
	WHERE ID_ARTICULO = P_ID_ARTICULO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE ARTICULO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('ARTICULO ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_ARTICULOS_TB_MODIFICAR_SP;

PROCEDURE FIDE_ARTICULOS_TB_ELIMINAR_SP(
	P_ID_ARTICULO IN FIDE_ARTICULOS_TB.ID_ARTICULO%TYPE
)IS
BEGIN
	UPDATE FIDE_ARTICULOS_TB
	SET ID_ESTADO = 2
	WHERE ID_ARTICULO = P_ID_ARTICULO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE ARTICULO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('ARTICULO ELIMINADO LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_ARTICULOS_TB_ELIMINAR_SP;

PROCEDURE FIDE_DIRECCION_EXACTA_TB_INSERTAR_SP(
	P_ID_DIRECCION_EXACTA IN FIDE_DIRECCION_EXACTA_TB.ID_DIRECCION_EXACTA%TYPE,
	P_OTRAS_SENIAS IN FIDE_DIRECCION_EXACTA_TB.OTRAS_SENIAS%TYPE,
	P_ID_DISTRITO IN FIDE_DIRECCION_EXACTA_TB.ID_DISTRITO%TYPE,
	P_ID_CANTON IN FIDE_DIRECCION_EXACTA_TB.ID_CANTON%TYPE,
	P_ID_PROVINCIA IN FIDE_DIRECCION_EXACTA_TB.ID_PROVINCIA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_DIRECCION_EXACTA_TB(ID_DIRECCION_EXACTA, OTRAS_SENIAS, ID_DISTRITO, ID_CANTON, ID_PROVINCIA, ID_ESTADO)
	VALUES(P_ID_DIRECCION_EXACTA, P_OTRAS_SENIAS, P_ID_DISTRITO, P_ID_CANTON, P_ID_PROVINCIA, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_DIRECCION_EXACTA_TB_INSERTAR_SP;

PROCEDURE FIDE_DIRECCION_EXACTA_TB_MODIFICAR_SP(
	P_ID_DIRECCION_EXACTA IN FIDE_DIRECCION_EXACTA_TB.ID_DIRECCION_EXACTA%TYPE,
	P_OTRAS_SENIAS IN FIDE_DIRECCION_EXACTA_TB.OTRAS_SENIAS%TYPE,
	P_ID_DISTRITO IN FIDE_DIRECCION_EXACTA_TB.ID_DISTRITO%TYPE,
	P_ID_CANTON IN FIDE_DIRECCION_EXACTA_TB.ID_CANTON%TYPE,
	P_ID_PROVINCIA IN FIDE_DIRECCION_EXACTA_TB.ID_PROVINCIA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_DIRECCION_EXACTA_TB
	SET OTRAS_SENIAS = P_OTRAS_SENIAS,
	ID_DISTRITO = P_ID_DISTRITO,
	ID_CANTON = P_ID_CANTON,
	ID_PROVINCIA = P_ID_PROVINCIA,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_DIRECCION_EXACTA = P_ID_DIRECCION_EXACTA;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE DIRECCION.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('DIRECCION ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_DIRECCION_EXACTA_TB_MODIFICAR_SP;

PROCEDURE FIDE_DIRECCION_EXACTA_TB_ELIMINAR_SP(
	P_ID_DIRECCION_EXACTA IN FIDE_DIRECCION_EXACTA_TB.ID_DIRECCION_EXACTA%TYPE
)IS
BEGIN
	UPDATE FIDE_DIRECCION_EXACTA_TB
	SET ID_ESTADO = 2
	WHERE ID_DIRECCION_EXACTA = P_ID_DIRECCION_EXACTA;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE DIRECCION.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('DIRECCION ELIMINADO LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_DIRECCION_EXACTA_TB_ELIMINAR_SP;

PROCEDURE FIDE_MEDICOS_TB_INSERTAR_SP(
	P_ID_MEDICO IN FIDE_MEDICOS_TB.ID_MEDICO%TYPE,
	P_NOMBRE IN FIDE_MEDICOS_TB.NOMBRE%TYPE,
	P_APELLIDO_PATERNO IN FIDE_MEDICOS_TB.APELLIDO_PATERNO%TYPE,
	P_APELLIDO_MATERNO IN FIDE_MEDICOS_TB.APELLIDO_MATERNO%TYPE,
	P_ID_ESPECIALIDAD IN FIDE_MEDICOS_TB.ID_ESPECIALIDAD%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_MEDICOS_TB(ID_MEDICO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ID_ESPECIALIDAD, ID_ESTADO)
	VALUES(P_ID_MEDICO, P_NOMBRE, P_APELLIDO_PATERNO, P_APELLIDO_MATERNO, P_ID_ESPECIALIDAD, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_MEDICOS_TB_INSERTAR_SP;

PROCEDURE FIDE_MEDICOS_TB_MODIFICAR_SP(
	P_ID_MEDICO IN FIDE_MEDICOS_TB.ID_MEDICO%TYPE,
	P_NOMBRE IN FIDE_MEDICOS_TB.NOMBRE%TYPE,
	P_APELLIDO_PATERNO IN FIDE_MEDICOS_TB.APELLIDO_PATERNO%TYPE,
	P_APELLIDO_MATERNO IN FIDE_MEDICOS_TB.APELLIDO_MATERNO%TYPE,
	P_ID_ESPECIALIDAD IN FIDE_MEDICOS_TB.ID_ESPECIALIDAD%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_MEDICOS_TB
	SET NOMBRE = P_NOMBRE,
	APELLIDO_PATERNO = P_APELLIDO_PATERNO,
	APELLIDO_MATERNO = P_APELLIDO_MATERNO,
	ID_ESPECIALIDAD = P_ID_ESPECIALIDAD,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_MEDICO = P_ID_MEDICO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE MEDICO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('MEDICO ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_MEDICOS_TB_MODIFICAR_SP;

PROCEDURE FIDE_MEDICOS_TB_ELIMINAR_SP(
	P_ID_MEDICO IN FIDE_MEDICOS_TB.ID_MEDICO%TYPE
)IS
BEGIN
	UPDATE FIDE_MEDICOS_TB
	SET ID_ESTADO = 2
	WHERE ID_MEDICO = P_ID_MEDICO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE MEDICO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('MEDICO ELIMINADO LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_MEDICOS_TB_ELIMINAR_SP;

PROCEDURE FIDE_EMPLEADOS_TB_INSERTAR_SP(
	P_ID_EMPLEADO IN FIDE_EMPLEADOS_TB.ID_EMPLEADO%TYPE,
	P_NOMBRE IN FIDE_EMPLEADOS_TB.NOMBRE%TYPE,
	P_APELLIDO_PATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_PATERNO%TYPE,
	P_APELLIDO_MATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_MATERNO%TYPE,
	P_EDAD IN FIDE_EMPLEADOS_TB.EDAD%TYPE,
	P_NOMBRE_DE_USUARIO IN FIDE_EMPLEADOS_TB.NOMBRE_DE_USUARIO%TYPE,
	P_CONTRASENIA IN FIDE_EMPLEADOS_TB.CONTRASENIA%TYPE,
	P_ID_CARGO IN FIDE_EMPLEADOS_TB.ID_CARGO%TYPE,
	P_ID_DIRECCION_EXACTA IN FIDE_EMPLEADOS_TB.ID_DIRECCION_EXACTA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_EMPLEADOS_TB(ID_EMPLEADO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, EDAD, NOMBRE_DE_USUARIO, CONTRASENIA, ID_CARGO, ID_DIRECCION_EXACTA, ID_ESTADO)
	VALUES(P_ID_EMPLEADO, P_NOMBRE, P_APELLIDO_PATERNO, P_APELLIDO_MATERNO, P_EDAD, P_NOMBRE_DE_USUARIO, P_CONTRASENIA, P_ID_CARGO, P_ID_DIRECCION_EXACTA, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_EMPLEADOS_TB_INSERTAR_SP;

PROCEDURE FIDE_EMPLEADOS_TB_MODIFICAR_SP(
	P_ID_EMPLEADO IN FIDE_EMPLEADOS_TB.ID_EMPLEADO%TYPE,
	P_NOMBRE IN FIDE_EMPLEADOS_TB.NOMBRE%TYPE,
	P_APELLIDO_PATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_PATERNO%TYPE,
	P_APELLIDO_MATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_MATERNO%TYPE,
	P_EDAD IN FIDE_EMPLEADOS_TB.EDAD%TYPE,
	P_NOMBRE_DE_USUARIO IN FIDE_EMPLEADOS_TB.NOMBRE_DE_USUARIO%TYPE,
	P_CONTRASENIA IN FIDE_EMPLEADOS_TB.CONTRASENIA%TYPE,
	P_ID_CARGO IN FIDE_EMPLEADOS_TB.ID_CARGO%TYPE,
	P_ID_DIRECCION_EXACTA IN FIDE_EMPLEADOS_TB.ID_DIRECCION_EXACTA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_EMPLEADOS_TB
	SET NOMBRE = P_NOMBRE,
	APELLIDO_PATERNO = P_APELLIDO_PATERNO,
	APELLIDO_MATERNO = P_APELLIDO_MATERNO,
	EDAD = P_EDAD,
	NOMBRE_DE_USUARIO = P_NOMBRE_DE_USUARIO,
	CONTRASENIA = P_CONTRASENIA,
	ID_CARGO = P_ID_CARGO,
	ID_DIRECCION_EXACTA = P_ID_DIRECCION_EXACTA,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_EMPLEADO = P_ID_EMPLEADO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE EMPLEADO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('EMPLEADO ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_EMPLEADOS_TB_MODIFICAR_SP;

PROCEDURE FIDE_EMPLEADOS_TB_ELIMINAR_SP(
	P_ID_EMPLEADO IN FIDE_EMPLEADOS_TB.ID_EMPLEADO%TYPE
)IS
BEGIN
	UPDATE FIDE_EMPLEADOS_TB
	SET ID_ESTADO = 2
	WHERE ID_EMPLEADO = P_ID_EMPLEADO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE EMPLEADO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('EMPLEADO ELIMINADO LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_EMPLEADOS_TB_ELIMINAR_SP;

PROCEDURE FIDE_JUGADORES_TB_INSERTAR_SP(
	P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE,
	P_ID_CATEGORIA IN FIDE_JUGADORES_TB.ID_CATEGORIA%TYPE,
	P_NOMBRE IN FIDE_JUGADORES_TB.NOMBRE%TYPE,
	P_APELLIDO_MATERNO IN FIDE_JUGADORES_TB.APELLIDO_MATERNO%TYPE,
	P_APELLIDO_PATERNO IN FIDE_JUGADORES_TB.APELLIDO_PATERNO%TYPE,
	P_DORSAL IN FIDE_JUGADORES_TB.DORSAL%TYPE,
	P_EDAD IN FIDE_JUGADORES_TB.EDAD%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
	P_ID_DIRECCION_EXACTA IN FIDE_JUGADORES_TB.ID_DIRECCION_EXACTA%TYPE
)IS
BEGIN
	INSERT INTO FIDE_JUGADORES_TB(ID_JUGADOR, ID_CATEGORIA, NOMBRE, APELLIDO_MATERNO, APELLIDO_PATERNO, DORSAL, EDAD, ID_ESTADO, ID_DIRECCION_EXACTA)
	VALUES(P_ID_JUGADOR, P_ID_CATEGORIA, P_NOMBRE, P_APELLIDO_MATERNO, P_APELLIDO_PATERNO, P_DORSAL, P_EDAD, P_ID_ESTADO, P_ID_DIRECCION_EXACTA);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_JUGADORES_TB_INSERTAR_SP;

PROCEDURE FIDE_JUGADORES_TB_MODIFICAR_SP(
	P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE,
	P_ID_CATEGORIA IN FIDE_JUGADORES_TB.ID_CATEGORIA%TYPE,
	P_NOMBRE IN FIDE_JUGADORES_TB.NOMBRE%TYPE,
	P_APELLIDO_MATERNO IN FIDE_JUGADORES_TB.APELLIDO_MATERNO%TYPE,
	P_APELLIDO_PATERNO IN FIDE_JUGADORES_TB.APELLIDO_PATERNO%TYPE,
	P_DORSAL IN FIDE_JUGADORES_TB.DORSAL%TYPE,
	P_EDAD IN FIDE_JUGADORES_TB.EDAD%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
	P_ID_DIRECCION_EXACTA IN FIDE_JUGADORES_TB.ID_DIRECCION_EXACTA%TYPE
)IS
BEGIN
	UPDATE FIDE_JUGADORES_TB
	SET ID_CATEGORIA = P_ID_CATEGORIA,
	NOMBRE = P_NOMBRE,
	APELLIDO_MATERNO = P_APELLIDO_MATERNO,
	APELLIDO_PATERNO = P_APELLIDO_PATERNO,
	DORSAL = P_DORSAL,
	EDAD = P_EDAD,
	ID_ESTADO = P_ID_ESTADO,
	ID_DIRECCION_EXACTA = P_ID_DIRECCION_EXACTA
	WHERE ID_JUGADOR = P_ID_JUGADOR;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE JUGADOR.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('JUGADOR ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_JUGADORES_TB_MODIFICAR_SP;

PROCEDURE FIDE_JUGADORES_TB_ELIMINAR_SP(
	P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
)IS
BEGIN
	UPDATE FIDE_JUGADORES_TB
	SET ID_ESTADO = 2
	WHERE ID_JUGADOR = P_ID_JUGADOR;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE JUGADOR.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('JUGADOR ELIMINADO LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_JUGADORES_TB_ELIMINAR_SP;

PROCEDURE FIDE_SEDES_TB_INSERTAR_SP(
	P_ID_SEDE IN FIDE_SEDES_TB.ID_SEDE%TYPE,
	P_NOMBRE_SEDE IN FIDE_SEDES_TB.NOMBRE_SEDE%TYPE,
	P_ID_DIRECCION_EXACTA IN FIDE_SEDES_TB.ID_DIRECCION_EXACTA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_SEDES_TB(ID_SEDE, NOMBRE_SEDE, ID_DIRECCION_EXACTA, ID_ESTADO)
	VALUES(P_ID_SEDE, P_NOMBRE_SEDE, P_ID_DIRECCION_EXACTA, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_SEDES_TB_INSERTAR_SP;

PROCEDURE FIDE_SEDES_TB_MODIFICAR_SP(
	P_ID_SEDE IN FIDE_SEDES_TB.ID_SEDE%TYPE,
	P_NOMBRE_SEDE IN FIDE_SEDES_TB.NOMBRE_SEDE%TYPE,
	P_ID_DIRECCION_EXACTA IN FIDE_SEDES_TB.ID_DIRECCION_EXACTA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_SEDES_TB
	SET NOMBRE_SEDE = P_NOMBRE_SEDE,
	ID_DIRECCION_EXACTA = P_ID_DIRECCION_EXACTA,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_SEDE = P_ID_SEDE;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE SEDE.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SEDE ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_SEDES_TB_MODIFICAR_SP;

PROCEDURE FIDE_SEDES_TB_ELIMINAR_SP(
	P_ID_SEDE IN FIDE_SEDES_TB.ID_SEDE%TYPE
)IS
BEGIN
	UPDATE FIDE_SEDES_TB
	SET ID_ESTADO = 2
	WHERE ID_SEDE = P_ID_SEDE;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE SEDE.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SEDE ELIMINADO LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_SEDES_TB_ELIMINAR_SP;

PROCEDURE FIDE_JUGADOR_POSICIONES_TB_INSERTAR_SP(
	P_ID_JUGADOR IN FIDE_JUGADOR_POSICIONES_TB.ID_JUGADOR%TYPE,
	P_ID_POSICION IN FIDE_JUGADOR_POSICIONES_TB.ID_POSICION%TYPE
)IS
BEGIN
	INSERT INTO FIDE_JUGADOR_POSICIONES_TB(ID_JUGADOR, ID_POSICION)
	VALUES(P_ID_JUGADOR, P_ID_POSICION);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_JUGADOR_POSICIONES_TB_INSERTAR_SP;

PROCEDURE FIDE_JUGADOR_POSICIONES_TB_MODIFICAR_SP(
	P_ID_JUGADOR IN FIDE_JUGADOR_POSICIONES_TB.ID_JUGADOR%TYPE,
	P_ID_POSICION_ACTUAL IN FIDE_JUGADOR_POSICIONES_TB.ID_POSICION%TYPE,
	P_ID_POSICION_NUEVA IN FIDE_JUGADOR_POSICIONES_TB.ID_POSICION%TYPE
)IS
BEGIN
	UPDATE FIDE_JUGADOR_POSICIONES_TB
	SET ID_POSICION = P_ID_POSICION_NUEVA
	WHERE ID_JUGADOR = P_ID_JUGADOR
	AND ID_POSICION = P_ID_POSICION_ACTUAL;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA POSICION DEL JUGADOR.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('POSICION DEL JUGADOR ACTUALIZADA CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_JUGADOR_POSICIONES_TB_MODIFICAR_SP;

PROCEDURE FIDE_JUGADOR_POSICIONES_TB_ELIMINAR_SP(
	P_ID_JUGADOR IN FIDE_JUGADOR_POSICIONES_TB.ID_JUGADOR%TYPE,
	P_ID_POSICION IN FIDE_JUGADOR_POSICIONES_TB.ID_POSICION%TYPE
)IS
BEGIN
	DELETE FROM FIDE_JUGADOR_POSICIONES_TB
	WHERE ID_JUGADOR = P_ID_JUGADOR
	AND ID_POSICION = P_ID_POSICION;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE POSICION DEL JUGADOR.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('POSICION DEL JUGADOR ELIMINADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_JUGADOR_POSICIONES_TB_ELIMINAR_SP;





PROCEDURE FIDE_PARTE_MEDICO_TB_INSERTAR_SP(
	P_ID_PARTEMEDICO IN FIDE_PARTE_MEDICO_TB.ID_PARTEMEDICO%TYPE,
	P_ID_JUGADOR IN FIDE_PARTE_MEDICO_TB.ID_JUGADOR%TYPE,
	P_OBSERVACIONES IN FIDE_PARTE_MEDICO_TB.OBSERVACIONES%TYPE,
	P_FECHA IN FIDE_PARTE_MEDICO_TB.FECHA%TYPE,
	P_ID_MEDICO IN FIDE_PARTE_MEDICO_TB.ID_MEDICO%TYPE,
	P_ID_ESTADO IN FIDE_PARTE_MEDICO_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_PARTE_MEDICO_TB(ID_PARTEMEDICO, ID_JUGADOR, OBSERVACIONES, FECHA, ID_MEDICO, ID_ESTADO)
	VALUES(P_ID_PARTEMEDICO, P_ID_JUGADOR, P_OBSERVACIONES, P_FECHA, P_ID_MEDICO, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_PARTE_MEDICO_TB_INSERTAR_SP;

PROCEDURE FIDE_PARTE_MEDICO_TB_MODIFICAR_SP(
	P_ID_PARTEMEDICO IN FIDE_PARTE_MEDICO_TB.ID_PARTEMEDICO%TYPE,
	P_ID_JUGADOR IN FIDE_PARTE_MEDICO_TB.ID_JUGADOR%TYPE,
	P_OBSERVACIONES IN FIDE_PARTE_MEDICO_TB.OBSERVACIONES%TYPE,
	P_FECHA IN FIDE_PARTE_MEDICO_TB.FECHA%TYPE,
	P_ID_MEDICO IN FIDE_PARTE_MEDICO_TB.ID_MEDICO%TYPE,
	P_ID_ESTADO IN FIDE_PARTE_MEDICO_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_PARTE_MEDICO_TB
	SET ID_JUGADOR = P_ID_JUGADOR,
	OBSERVACIONES = P_OBSERVACIONES,
	FECHA = P_FECHA,
	ID_MEDICO = P_ID_MEDICO,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_PARTEMEDICO = P_ID_PARTEMEDICO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL PARTE MEDICO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('PARTE MEDICO ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_PARTE_MEDICO_TB_MODIFICAR_SP;

PROCEDURE FIDE_PARTE_MEDICO_TB_ELIMINAR_SP(
	P_ID_PARTEMEDICO IN FIDE_PARTE_MEDICO_TB.ID_PARTEMEDICO%TYPE
)IS
BEGIN
	UPDATE FIDE_PARTE_MEDICO_TB
	SET ID_ESTADO = 2
	WHERE ID_PARTEMEDICO = P_ID_PARTEMEDICO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL PARTE MEDICO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('PARTE MEDICO ELIMINADO LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_PARTE_MEDICO_TB_ELIMINAR_SP;


PROCEDURE FIDE_PARTIDOS_TB_INSERTAR_SP(
	P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE,
	P_ID_CATEGORIA IN FIDE_PARTIDOS_TB.ID_CATEGORIA%TYPE,
	P_ID_TIPOPARTIDOS IN FIDE_PARTIDOS_TB.ID_TIPOPARTIDOS%TYPE,
	P_ID_TEMPORADA IN FIDE_PARTIDOS_TB.ID_TEMPORADA%TYPE,
	P_FECHA IN FIDE_PARTIDOS_TB.FECHA%TYPE,
	P_RIVAL IN FIDE_PARTIDOS_TB.RIVAL%TYPE,
	P_GOLES_FAVOR IN FIDE_PARTIDOS_TB.GOLES_FAVOR%TYPE,
	P_GOLES_CONTRA IN FIDE_PARTIDOS_TB.GOLES_CONTRA%TYPE,
	P_ID_SEDE IN FIDE_PARTIDOS_TB.ID_SEDE%TYPE,
	P_ID_ESTADO IN FIDE_PARTIDOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_PARTIDOS_TB(ID_PARTIDO, ID_CATEGORIA, ID_TIPOPARTIDOS, ID_TEMPORADA, FECHA, RIVAL, GOLES_FAVOR, GOLES_CONTRA, ID_SEDE, ID_ESTADO)
	VALUES(P_ID_PARTIDO, P_ID_CATEGORIA, P_ID_TIPOPARTIDOS, P_ID_TEMPORADA, P_FECHA, P_RIVAL, P_GOLES_FAVOR, P_GOLES_CONTRA, P_ID_SEDE, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_PARTIDOS_TB_INSERTAR_SP;

PROCEDURE FIDE_PARTIDOS_TB_MODIFICAR_SP(
	P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE,
	P_ID_CATEGORIA IN FIDE_PARTIDOS_TB.ID_CATEGORIA%TYPE,
	P_ID_TIPOPARTIDOS IN FIDE_PARTIDOS_TB.ID_TIPOPARTIDOS%TYPE,
	P_ID_TEMPORADA IN FIDE_PARTIDOS_TB.ID_TEMPORADA%TYPE,
	P_FECHA IN FIDE_PARTIDOS_TB.FECHA%TYPE,
	P_RIVAL IN FIDE_PARTIDOS_TB.RIVAL%TYPE,
	P_GOLES_FAVOR IN FIDE_PARTIDOS_TB.GOLES_FAVOR%TYPE,
	P_GOLES_CONTRA IN FIDE_PARTIDOS_TB.GOLES_CONTRA%TYPE,
	P_ID_SEDE IN FIDE_PARTIDOS_TB.ID_SEDE%TYPE,
	P_ID_ESTADO IN FIDE_PARTIDOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_PARTIDOS_TB
	SET ID_CATEGORIA = P_ID_CATEGORIA,
	ID_TIPOPARTIDOS = P_ID_TIPOPARTIDOS,
	ID_TEMPORADA = P_ID_TEMPORADA,
	FECHA = P_FECHA,
	RIVAL = P_RIVAL,
	GOLES_FAVOR = P_GOLES_FAVOR,
	GOLES_CONTRA = P_GOLES_CONTRA,
	ID_SEDE = P_ID_SEDE,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_PARTIDO = P_ID_PARTIDO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL PARTIDO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('PARTIDO ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_PARTIDOS_TB_MODIFICAR_SP;

PROCEDURE FIDE_PARTIDOS_TB_ELIMINAR_SP(
	P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE
)IS
BEGIN
	UPDATE FIDE_PARTIDOS_TB
	SET ID_ESTADO = 2
	WHERE ID_PARTIDO = P_ID_PARTIDO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL PARTIDO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('PARTIDO ELIMINADO LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_PARTIDOS_TB_ELIMINAR_SP;


PROCEDURE FIDE_REVISION_FISICA_TB_INSERTAR_SP(
	P_ID_REVISION IN FIDE_REVISION_FISICA_TB.ID_REVISION%TYPE,
	P_ID_JUGADOR IN FIDE_REVISION_FISICA_TB.ID_JUGADOR%TYPE,
	P_PESO IN FIDE_REVISION_FISICA_TB.PESO%TYPE,
	P_IMC IN FIDE_REVISION_FISICA_TB.IMC%TYPE,
	P_ALTURA IN FIDE_REVISION_FISICA_TB.ALTURA%TYPE,
	P_FECHA_REVISION IN FIDE_REVISION_FISICA_TB.FECHA_REVISION%TYPE,
	P_ID_ESTADO IN FIDE_REVISION_FISICA_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_REVISION_FISICA_TB(ID_REVISION, ID_JUGADOR, PESO, IMC, ALTURA, FECHA_REVISION, ID_ESTADO)
	VALUES(P_ID_REVISION, P_ID_JUGADOR, P_PESO, P_IMC, P_ALTURA, P_FECHA_REVISION, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_REVISION_FISICA_TB_INSERTAR_SP;

PROCEDURE FIDE_REVISION_FISICA_TB_MODIFICAR_SP(
	P_ID_REVISION IN FIDE_REVISION_FISICA_TB.ID_REVISION%TYPE,
	P_ID_JUGADOR IN FIDE_REVISION_FISICA_TB.ID_JUGADOR%TYPE,
	P_PESO IN FIDE_REVISION_FISICA_TB.PESO%TYPE,
	P_IMC IN FIDE_REVISION_FISICA_TB.IMC%TYPE,
	P_ALTURA IN FIDE_REVISION_FISICA_TB.ALTURA%TYPE,
	P_FECHA_REVISION IN FIDE_REVISION_FISICA_TB.FECHA_REVISION%TYPE,
	P_ID_ESTADO IN FIDE_REVISION_FISICA_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_REVISION_FISICA_TB
	SET ID_JUGADOR = P_ID_JUGADOR,
	PESO = P_PESO,
	IMC = P_IMC,
	ALTURA = P_ALTURA,
	FECHA_REVISION = P_FECHA_REVISION,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_REVISION = P_ID_REVISION;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA REVISION FISICA.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('REVISION FISICA ACTUALIZADA CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_REVISION_FISICA_TB_MODIFICAR_SP;

PROCEDURE FIDE_REVISION_FISICA_TB_ELIMINAR_SP(
	P_ID_REVISION IN FIDE_REVISION_FISICA_TB.ID_REVISION%TYPE
)IS
BEGIN
	UPDATE FIDE_REVISION_FISICA_TB
	SET ID_ESTADO = 2
	WHERE ID_REVISION = P_ID_REVISION;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA REVISION FISICA.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('REVISION FISICA ELIMINADA LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_REVISION_FISICA_TB_ELIMINAR_SP;


PROCEDURE FIDE_TELEFONOS_TB_INSERTAR_SP(
	P_ID_TELEFONO IN FIDE_TELEFONOS_TB.ID_TELEFONO%TYPE,
	P_NUMERO_TELEFONO IN FIDE_TELEFONOS_TB.NUMERO_TELEFONO%TYPE,
	P_ID_EMPLEADO IN FIDE_TELEFONOS_TB.ID_EMPLEADO%TYPE,
	P_ID_ESTADO IN FIDE_TELEFONOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_TELEFONOS_TB(ID_TELEFONO, NUMERO_TELEFONO, ID_EMPLEADO, ID_ESTADO)
	VALUES(P_ID_TELEFONO, P_NUMERO_TELEFONO, P_ID_EMPLEADO, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_TELEFONOS_TB_INSERTAR_SP;

PROCEDURE FIDE_TELEFONOS_TB_MODIFICAR_SP(
	P_ID_TELEFONO IN FIDE_TELEFONOS_TB.ID_TELEFONO%TYPE,
	P_NUMERO_TELEFONO IN FIDE_TELEFONOS_TB.NUMERO_TELEFONO%TYPE,
	P_ID_EMPLEADO IN FIDE_TELEFONOS_TB.ID_EMPLEADO%TYPE,
	P_ID_ESTADO IN FIDE_TELEFONOS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_TELEFONOS_TB
	SET NUMERO_TELEFONO = P_NUMERO_TELEFONO,
	ID_EMPLEADO = P_ID_EMPLEADO,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_TELEFONO = P_ID_TELEFONO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TELEFONO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TELEFONO ACTUALIZADO CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END  FIDE_TELEFONOS_TB_MODIFICAR_SP;

PROCEDURE  FIDE_TELEFONOS_TB_ELIMINAR_SP(
	P_ID_TELEFONO IN FIDE_TELEFONOS_TB.ID_TELEFONO%TYPE
)IS
BEGIN
	UPDATE FIDE_TELEFONOS_TB
	SET ID_ESTADO = 2
	WHERE ID_TELEFONO = P_ID_TELEFONO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TELEFONO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TELEFONO ELIMINADO LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_TELEFONOS_TB_ELIMINAR_SP;


PROCEDURE FIDE_ASISTENCIA_TB_INSERTAR_SP(
	P_ID_PARTIDO IN FIDE_ASISTENCIA_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_ASISTENCIA_TB.ID_JUGADOR%TYPE,
	P_ID_ESTADO IN FIDE_ASISTENCIA_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_ASISTENCIA_TB(ID_PARTIDO, ID_JUGADOR, ID_ESTADO)
	VALUES(P_ID_PARTIDO, P_ID_JUGADOR, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_ASISTENCIA_TB_INSERTAR_SP;

PROCEDURE FIDE_ASISTENCIA_TB_MODIFICAR_SP(
	P_ID_PARTIDO IN FIDE_ASISTENCIA_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_ASISTENCIA_TB.ID_JUGADOR%TYPE,
	P_ID_ESTADO IN FIDE_ASISTENCIA_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_ASISTENCIA_TB
	SET ID_ESTADO = P_ID_ESTADO
	WHERE ID_PARTIDO = P_ID_PARTIDO
	AND ID_JUGADOR = P_ID_JUGADOR;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE ASISTENCIA.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('ASISTENCIA ACTUALIZADA CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_ASISTENCIA_TB_MODIFICAR_SP;

PROCEDURE FIDE_ASISTENCIA_TB_ELIMINAR_SP(
	P_ID_PARTIDO IN FIDE_ASISTENCIA_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_ASISTENCIA_TB.ID_JUGADOR%TYPE
)IS
BEGIN
	UPDATE FIDE_ASISTENCIA_TB
	SET ID_ESTADO = 2
	WHERE ID_PARTIDO = P_ID_PARTIDO
	AND ID_JUGADOR = P_ID_JUGADOR;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE ASISTENCIA.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('ASISTENCIA ELIMINADA LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_ASISTENCIA_TB_ELIMINAR_SP;


PROCEDURE FIDE_ESTADISTICA_EQUIPO_TB_INSERTAR_SP(
	P_ID_ESTADISTICA_EQUIPO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_ESTADISTICA_EQUIPO%TYPE,
	P_TIROS IN FIDE_ESTADISTICA_EQUIPO_TB.TIROS%TYPE,
	P_TIROS_PORTERIA IN FIDE_ESTADISTICA_EQUIPO_TB.TIROS_PORTERIA%TYPE,
	P_PASES_EXITOSOS IN FIDE_ESTADISTICA_EQUIPO_TB.PASES_EXITOSOS%TYPE,
	P_PASES_FALLIDOS IN FIDE_ESTADISTICA_EQUIPO_TB.PASES_FALLIDOS%TYPE,
	P_POSESION_BALON IN FIDE_ESTADISTICA_EQUIPO_TB.POSESION_BALON%TYPE,
	P_ID_PARTIDO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_PARTIDO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_ESTADISTICA_EQUIPO_TB(ID_ESTADISTICA_EQUIPO, TIROS, TIROS_PORTERIA, PASES_EXITOSOS, PASES_FALLIDOS, POSESION_BALON, ID_PARTIDO, ID_ESTADO)
	VALUES(P_ID_ESTADISTICA_EQUIPO, P_TIROS, P_TIROS_PORTERIA, P_PASES_EXITOSOS, P_PASES_FALLIDOS, P_POSESION_BALON, P_ID_PARTIDO, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_ESTADISTICA_EQUIPO_TB_INSERTAR_SP;

PROCEDURE FIDE_ESTADISTICA_EQUIPO_TB_MODIFICAR_SP(
	P_ID_ESTADISTICA_EQUIPO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_ESTADISTICA_EQUIPO%TYPE,
	P_TIROS IN FIDE_ESTADISTICA_EQUIPO_TB.TIROS%TYPE,
	P_TIROS_PORTERIA IN FIDE_ESTADISTICA_EQUIPO_TB.TIROS_PORTERIA%TYPE,
	P_PASES_EXITOSOS IN FIDE_ESTADISTICA_EQUIPO_TB.PASES_EXITOSOS%TYPE,
	P_PASES_FALLIDOS IN FIDE_ESTADISTICA_EQUIPO_TB.PASES_FALLIDOS%TYPE,
	P_POSESION_BALON IN FIDE_ESTADISTICA_EQUIPO_TB.POSESION_BALON%TYPE,
	P_ID_PARTIDO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_PARTIDO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_ESTADISTICA_EQUIPO_TB
	SET TIROS = P_TIROS,
	TIROS_PORTERIA = P_TIROS_PORTERIA,
	PASES_EXITOSOS = P_PASES_EXITOSOS,
	PASES_FALLIDOS = P_PASES_FALLIDOS,
	POSESION_BALON = P_POSESION_BALON,
	ID_PARTIDO = P_ID_PARTIDO,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_ESTADISTICA_EQUIPO = P_ID_ESTADISTICA_EQUIPO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA ESTADISTICA DE EQUIPO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('ESTADISTICA DE EQUIPO ACTUALIZADA CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_ESTADISTICA_EQUIPO_TB_MODIFICAR_SP;

PROCEDURE FIDE_ESTADISTICA_EQUIPO_TB_ELIMINAR_SP(
	P_ID_ESTADISTICA_EQUIPO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_ESTADISTICA_EQUIPO%TYPE
)IS
BEGIN
	UPDATE FIDE_ESTADISTICA_EQUIPO_TB
	SET ID_ESTADO = 2
	WHERE ID_ESTADISTICA_EQUIPO = P_ID_ESTADISTICA_EQUIPO;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA ESTADISTICA DE EQUIPO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('ESTADISTICA DE EQUIPO ELIMINADA LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_ESTADISTICA_EQUIPO_TB_ELIMINAR_SP;


PROCEDURE FIDE_ESTADISTICA_JUGADOR_TB_INSERTAR_SP(
	P_ID_ESTADISTICA_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_ESTADISTICA_JUGADOR%TYPE,
	P_ID_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_JUGADOR%TYPE,
	P_ID_PARTIDO IN FIDE_ESTADISTICA_JUGADOR_TB.ID_PARTIDO%TYPE,
	P_PASES IN FIDE_ESTADISTICA_JUGADOR_TB.PASES%TYPE,
	P_PASES_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.PASES_EXITOSOS%TYPE,
	P_REGATES IN FIDE_ESTADISTICA_JUGADOR_TB.REGATES%TYPE,
	P_REGATES_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.REGATES_EXITOSOS%TYPE,
	P_TIROS IN FIDE_ESTADISTICA_JUGADOR_TB.TIROS%TYPE,
	P_TIROS_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.TIROS_EXITOSOS%TYPE,
	P_ENTRADAS IN FIDE_ESTADISTICA_JUGADOR_TB.ENTRADAS%TYPE,
	P_ENTRADAS_EXITOSAS IN FIDE_ESTADISTICA_JUGADOR_TB.ENTRADAS_EXITOSAS%TYPE,
	P_MINUTOS_JUGADOS IN FIDE_ESTADISTICA_JUGADOR_TB.MINUTOS_JUGADOS%TYPE,
	P_GOLES IN FIDE_ESTADISTICA_JUGADOR_TB.GOLES%TYPE,
	P_ASISTENCIAS IN FIDE_ESTADISTICA_JUGADOR_TB.ASISTENCIAS%TYPE,
	P_ID_ESTADO IN FIDE_ESTADISTICA_JUGADOR_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_ESTADISTICA_JUGADOR_TB(ID_ESTADISTICA_JUGADOR, ID_JUGADOR, ID_PARTIDO, PASES, PASES_EXITOSOS, REGATES, REGATES_EXITOSOS, TIROS, TIROS_EXITOSOS, ENTRADAS, ENTRADAS_EXITOSAS, MINUTOS_JUGADOS, GOLES, ASISTENCIAS, ID_ESTADO)
	VALUES(P_ID_ESTADISTICA_JUGADOR, P_ID_JUGADOR, P_ID_PARTIDO, P_PASES, P_PASES_EXITOSOS, P_REGATES, P_REGATES_EXITOSOS, P_TIROS, P_TIROS_EXITOSOS, P_ENTRADAS, P_ENTRADAS_EXITOSAS, P_MINUTOS_JUGADOS, P_GOLES, P_ASISTENCIAS, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_ESTADISTICA_JUGADOR_TB_INSERTAR_SP;

PROCEDURE FIDE_ESTADISTICA_JUGADOR_TB_MODIFICAR_SP(
	P_ID_ESTADISTICA_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_ESTADISTICA_JUGADOR%TYPE,
	P_ID_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_JUGADOR%TYPE,
	P_ID_PARTIDO IN FIDE_ESTADISTICA_JUGADOR_TB.ID_PARTIDO%TYPE,
	P_PASES IN FIDE_ESTADISTICA_JUGADOR_TB.PASES%TYPE,
	P_PASES_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.PASES_EXITOSOS%TYPE,
	P_REGATES IN FIDE_ESTADISTICA_JUGADOR_TB.REGATES%TYPE,
	P_REGATES_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.REGATES_EXITOSOS%TYPE,
	P_TIROS IN FIDE_ESTADISTICA_JUGADOR_TB.TIROS%TYPE,
	P_TIROS_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.TIROS_EXITOSOS%TYPE,
	P_ENTRADAS IN FIDE_ESTADISTICA_JUGADOR_TB.ENTRADAS%TYPE,
	P_ENTRADAS_EXITOSAS IN FIDE_ESTADISTICA_JUGADOR_TB.ENTRADAS_EXITOSAS%TYPE,
	P_MINUTOS_JUGADOS IN FIDE_ESTADISTICA_JUGADOR_TB.MINUTOS_JUGADOS%TYPE,
	P_GOLES IN FIDE_ESTADISTICA_JUGADOR_TB.GOLES%TYPE,
	P_ASISTENCIAS IN FIDE_ESTADISTICA_JUGADOR_TB.ASISTENCIAS%TYPE,
	P_ID_ESTADO IN FIDE_ESTADISTICA_JUGADOR_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_ESTADISTICA_JUGADOR_TB
	SET ID_JUGADOR = P_ID_JUGADOR,
	ID_PARTIDO = P_ID_PARTIDO,
	PASES = P_PASES,
	PASES_EXITOSOS = P_PASES_EXITOSOS,
	REGATES = P_REGATES,
	REGATES_EXITOSOS = P_REGATES_EXITOSOS,
	TIROS = P_TIROS,
	TIROS_EXITOSOS = P_TIROS_EXITOSOS,
	ENTRADAS = P_ENTRADAS,
	ENTRADAS_EXITOSAS = P_ENTRADAS_EXITOSAS,
	MINUTOS_JUGADOS = P_MINUTOS_JUGADOS,
	GOLES = P_GOLES,
	ASISTENCIAS = P_ASISTENCIAS,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_ESTADISTICA_JUGADOR = P_ID_ESTADISTICA_JUGADOR;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA ESTADISTICA DEL JUGADOR.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('ESTADISTICA DEL JUGADOR ACTUALIZADA CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_ESTADISTICA_JUGADOR_TB_MODIFICAR_SP;

PROCEDURE FIDE_ESTADISTICA_JUGADOR_TB_ELIMINAR_SP(
	P_ID_ESTADISTICA_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_ESTADISTICA_JUGADOR%TYPE
)IS
BEGIN
	UPDATE FIDE_ESTADISTICA_JUGADOR_TB
	SET ID_ESTADO = 2
	WHERE ID_ESTADISTICA_JUGADOR = P_ID_ESTADISTICA_JUGADOR;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA ESTADISTICA DEL JUGADOR.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('ESTADISTICA DEL JUGADOR ELIMINADA LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_ESTADISTICA_JUGADOR_TB_ELIMINAR_SP;


PROCEDURE FIDE_LESIONES_TB_INSERTAR_SP(
	P_ID_LESION IN FIDE_LESIONES_TB.ID_LESION%TYPE,
	P_DESCRIPCION IN FIDE_LESIONES_TB.DESCRIPCION%TYPE,
	P_FECHA_RECUPERACION IN FIDE_LESIONES_TB.FECHA_RECUPERACION%TYPE,
	P_ID_TIPOLESION IN FIDE_LESIONES_TB.ID_TIPOLESION%TYPE,
	P_ID_PARTEMEDICO IN FIDE_LESIONES_TB.ID_PARTEMEDICO%TYPE,
	P_ID_ESTADO IN FIDE_LESIONES_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_LESIONES_TB(ID_LESION, DESCRIPCION, FECHA_RECUPERACION, ID_TIPOLESION, ID_PARTEMEDICO, ID_ESTADO)
	VALUES(P_ID_LESION, P_DESCRIPCION, P_FECHA_RECUPERACION, P_ID_TIPOLESION, P_ID_PARTEMEDICO, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_LESIONES_TB_INSERTAR_SP;

PROCEDURE FIDE_LESIONES_TB_MODIFICAR_SP(
	P_ID_LESION IN FIDE_LESIONES_TB.ID_LESION%TYPE,
	P_DESCRIPCION IN FIDE_LESIONES_TB.DESCRIPCION%TYPE,
	P_FECHA_RECUPERACION IN FIDE_LESIONES_TB.FECHA_RECUPERACION%TYPE,
	P_ID_TIPOLESION IN FIDE_LESIONES_TB.ID_TIPOLESION%TYPE,
	P_ID_PARTEMEDICO IN FIDE_LESIONES_TB.ID_PARTEMEDICO%TYPE,
	P_ID_ESTADO IN FIDE_LESIONES_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_LESIONES_TB
	SET DESCRIPCION = P_DESCRIPCION,
	FECHA_RECUPERACION = P_FECHA_RECUPERACION,
	ID_TIPOLESION = P_ID_TIPOLESION,
	ID_PARTEMEDICO = P_ID_PARTEMEDICO,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_LESION = P_ID_LESION;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA LESION.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('LESION ACTUALIZADA CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_LESIONES_TB_MODIFICAR_SP;

PROCEDURE FIDE_LESIONES_TB_ELIMINAR_SP(
	P_ID_LESION IN FIDE_LESIONES_TB.ID_LESION%TYPE
)IS
BEGIN
	UPDATE FIDE_LESIONES_TB
	SET ID_ESTADO = 2
	WHERE ID_LESION = P_ID_LESION;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA LESION.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('LESION ELIMINADA LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_LESIONES_TB_ELIMINAR_SP;


PROCEDURE FIDE_TARJETAS_TB_INSERTAR_SP(
	P_ID_PARTIDO IN FIDE_TARJETAS_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_TARJETAS_TB.ID_JUGADOR%TYPE,
	P_ID_TIPOTARJETA IN FIDE_TARJETAS_TB.ID_TIPOTARJETA%TYPE,
	P_CANTIDAD_TARJETAS IN FIDE_TARJETAS_TB.CANTIDAD_TARJETAS%TYPE,
	P_ID_ESTADO IN FIDE_TARJETAS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	INSERT INTO FIDE_TARJETAS_TB(ID_PARTIDO, ID_JUGADOR, ID_TIPOTARJETA, CANTIDAD_TARJETAS, ID_ESTADO)
	VALUES(P_ID_PARTIDO, P_ID_JUGADOR, P_ID_TIPOTARJETA, P_CANTIDAD_TARJETAS, P_ID_ESTADO);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_TARJETAS_TB_INSERTAR_SP;

PROCEDURE FIDE_TARJETAS_TB_MODIFICAR_SP(
	P_ID_PARTIDO IN FIDE_TARJETAS_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_TARJETAS_TB.ID_JUGADOR%TYPE,
	P_ID_TIPOTARJETA IN FIDE_TARJETAS_TB.ID_TIPOTARJETA%TYPE,
	P_CANTIDAD_TARJETAS IN FIDE_TARJETAS_TB.CANTIDAD_TARJETAS%TYPE,
	P_ID_ESTADO IN FIDE_TARJETAS_TB.ID_ESTADO%TYPE
)IS
BEGIN
	UPDATE FIDE_TARJETAS_TB
	SET CANTIDAD_TARJETAS = P_CANTIDAD_TARJETAS,
	ID_ESTADO = P_ID_ESTADO
	WHERE ID_PARTIDO = P_ID_PARTIDO
	AND ID_JUGADOR = P_ID_JUGADOR
	AND ID_TIPOTARJETA = P_ID_TIPOTARJETA;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE TARJETA.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TARJETA ACTUALIZADA CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_TARJETAS_TB_MODIFICAR_SP;

PROCEDURE FIDE_TARJETAS_TB_ELIMINAR_SP(
	P_ID_PARTIDO IN FIDE_TARJETAS_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_TARJETAS_TB.ID_JUGADOR%TYPE,
	P_ID_TIPOTARJETA IN FIDE_TARJETAS_TB.ID_TIPOTARJETA%TYPE
)IS
BEGIN
	UPDATE FIDE_TARJETAS_TB
	SET ID_ESTADO = 2
	WHERE ID_PARTIDO = P_ID_PARTIDO
	AND ID_JUGADOR = P_ID_JUGADOR
	AND ID_TIPOTARJETA = P_ID_TIPOTARJETA;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REGISTRO DE TARJETA.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TARJETA ELIMINADA LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_TARJETAS_TB_ELIMINAR_SP;


PROCEDURE FIDE_FACTURACION_INSCRIPCIONES_TB_INSERTAR_SP(
	P_ID_FACTURACION_INSCRIPCION IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_FACTURACION_INSCRIPCION%TYPE,
	P_ID_JUGADOR IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_JUGADOR%TYPE,
	P_MES IN FIDE_FACTURACION_INSCRIPCIONES_TB.MES%TYPE,
	P_ANIO IN FIDE_FACTURACION_INSCRIPCIONES_TB.ANIO%TYPE,
	P_MONTO IN FIDE_FACTURACION_INSCRIPCIONES_TB.MONTO%TYPE,
	P_FECHA_PAGO IN FIDE_FACTURACION_INSCRIPCIONES_TB.FECHA_PAGO%TYPE,
	P_ID_ESTADO IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_ESTADO%TYPE,
	P_OBSERVACIONES IN FIDE_FACTURACION_INSCRIPCIONES_TB.OBSERVACIONES%TYPE
)IS
BEGIN
	INSERT INTO FIDE_FACTURACION_INSCRIPCIONES_TB(ID_FACTURACION_INSCRIPCION, ID_JUGADOR, MES, ANIO, MONTO, FECHA_PAGO, ID_ESTADO, OBSERVACIONES)
	VALUES(P_ID_FACTURACION_INSCRIPCION, P_ID_JUGADOR, P_MES, P_ANIO, P_MONTO, P_FECHA_PAGO, P_ID_ESTADO, P_OBSERVACIONES);
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO SE INSERTARON DATOS');
	WHEN DUP_VAL_ON_INDEX THEN
		DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON ESE ID.');
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
END FIDE_FACTURACION_INSCRIPCIONES_TB_INSERTAR_SP;

PROCEDURE FIDE_FACTURACION_INSCRIPCIONES_TB_MODIFICAR_SP(
	P_ID_FACTURACION_INSCRIPCION IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_FACTURACION_INSCRIPCION%TYPE,
	P_ID_JUGADOR IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_JUGADOR%TYPE,
	P_MES IN FIDE_FACTURACION_INSCRIPCIONES_TB.MES%TYPE,
	P_ANIO IN FIDE_FACTURACION_INSCRIPCIONES_TB.ANIO%TYPE,
	P_MONTO IN FIDE_FACTURACION_INSCRIPCIONES_TB.MONTO%TYPE,
	P_FECHA_PAGO IN FIDE_FACTURACION_INSCRIPCIONES_TB.FECHA_PAGO%TYPE,
	P_ID_ESTADO IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_ESTADO%TYPE,
	P_OBSERVACIONES IN FIDE_FACTURACION_INSCRIPCIONES_TB.OBSERVACIONES%TYPE
)IS
BEGIN
	UPDATE FIDE_FACTURACION_INSCRIPCIONES_TB
	SET ID_JUGADOR = P_ID_JUGADOR,
	MES = P_MES,
	ANIO = P_ANIO,
	MONTO = P_MONTO,
	FECHA_PAGO = P_FECHA_PAGO,
	ID_ESTADO = P_ID_ESTADO,
	OBSERVACIONES = P_OBSERVACIONES
	WHERE ID_FACTURACION_INSCRIPCION = P_ID_FACTURACION_INSCRIPCION;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FACTURACION DE INSCRIPCION.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('FACTURACION DE INSCRIPCION ACTUALIZADA CORRECTAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN VALUE_ERROR THEN
		DBMS_OUTPUT.PUT_LINE('ERROR EN EL TIPO O TAMAÑO DE LOS DATOS INGRESADOS.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EL REGISTRO.');
END FIDE_FACTURACION_INSCRIPCIONES_TB_MODIFICAR_SP;

PROCEDURE  FIDE_FACTURACION_INSCRIPCIONES_TB_ELIMINAR_SP(
	P_ID_FACTURACION_INSCRIPCION IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_FACTURACION_INSCRIPCION%TYPE
)IS
BEGIN
	UPDATE FIDE_FACTURACION_INSCRIPCIONES_TB
	SET ID_ESTADO = 2
	WHERE ID_FACTURACION_INSCRIPCION = P_ID_FACTURACION_INSCRIPCION;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FACTURACION DE INSCRIPCION.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('FACTURACION DE INSCRIPCION ELIMINADA LOGICAMENTE.');
	END IF;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL REGISTRO.');
END FIDE_FACTURACION_INSCRIPCIONES_TB_ELIMINAR_SP;


---------------------------------


FUNCTION CATEGORIAS_LISTAR_FN(
	P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE
)
RETURN VARCHAR2
IS

	V_CATEGORIA FIDE_CATEGORIAS_TB.NOMBRE_CATEGORIA%TYPE;

	CURSOR C_CATEGORIA IS
		SELECT NOMBRE_CATEGORIA
		FROM FIDE_CATEGORIAS_TB
		WHERE ID_CATEGORIA = P_ID_CATEGORIA;

BEGIN

	FOR CAT IN C_CATEGORIA LOOP
		V_CATEGORIA := CAT.NOMBRE_CATEGORIA;
	END LOOP;

	RETURN V_CATEGORIA;

END CATEGORIAS_LISTAR_FN;



FUNCTION ESPECIALIDADES_LISTAR_FN(
	P_ID_ESPECIALIDAD IN FIDE_ESPECIALIDADES_TB.ID_ESPECIALIDAD%TYPE
)
RETURN VARCHAR2
IS
	V_ESPECIALIDAD FIDE_ESPECIALIDADES_TB.NOMBRE_ESPECIALIDAD%TYPE;

	CURSOR C_ESPECIALIDAD IS
		SELECT NOMBRE_ESPECIALIDAD
		FROM FIDE_ESPECIALIDADES_TB
		WHERE ID_ESPECIALIDAD = P_ID_ESPECIALIDAD;
BEGIN
	FOR ESP IN C_ESPECIALIDAD LOOP
		V_ESPECIALIDAD := ESP.NOMBRE_ESPECIALIDAD;
	END LOOP;

	RETURN V_ESPECIALIDAD;
END ESPECIALIDADES_LISTAR_FN;


FUNCTION TIPO_LESION_LISTAR_FN(
	P_ID_TIPOLESION IN FIDE_TIPOLESION_TB.ID_TIPOLESION%TYPE
)
RETURN VARCHAR2
IS
	V_TIPO_LESION FIDE_TIPOLESION_TB.NOMBRE_TIPO_LESION%TYPE;

	CURSOR C_TIPO_LESION IS
		SELECT NOMBRE_TIPO_LESION
		FROM FIDE_TIPOLESION_TB
		WHERE ID_TIPOLESION = P_ID_TIPOLESION;
BEGIN
	FOR LES IN C_TIPO_LESION LOOP
		V_TIPO_LESION := LES.NOMBRE_TIPO_LESION;
	END LOOP;

	RETURN V_TIPO_LESION;
END TIPO_LESION_LISTAR_FN;


FUNCTION TIPO_TARJETAS_LISTAR_FN(
	P_ID_TIPOTARJETA IN FIDE_TIPOTARJETAS_TB.ID_TIPOTARJETA%TYPE
)
RETURN VARCHAR2
IS
	V_TIPO_TARJETA FIDE_TIPOTARJETAS_TB.COLOR%TYPE;

	CURSOR C_TIPO_TARJETA IS
		SELECT COLOR
		FROM FIDE_TIPOTARJETAS_TB
		WHERE ID_TIPOTARJETA = P_ID_TIPOTARJETA;
BEGIN
	FOR TAR IN C_TIPO_TARJETA LOOP
		V_TIPO_TARJETA := TAR.COLOR;
	END LOOP;

	RETURN V_TIPO_TARJETA;
END TIPO_TARJETAS_LISTAR_FN;


FUNCTION CATEGORIA_INVENTARIO_LISTAR_FN(
	P_ID_CATEGORIAINVENTARIO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_CATEGORIAINVENTARIO%TYPE
)
RETURN VARCHAR2
IS
	V_CATEGORIA_INVENTARIO FIDE_CATEGORIA_INVENTARIO_TB.NOMBRE_CATEGORIA_INVENTARIO%TYPE;

	CURSOR C_CATEGORIA_INVENTARIO IS
		SELECT NOMBRE_CATEGORIA_INVENTARIO
		FROM FIDE_CATEGORIA_INVENTARIO_TB
		WHERE ID_CATEGORIAINVENTARIO = P_ID_CATEGORIAINVENTARIO;
BEGIN
	FOR INV IN C_CATEGORIA_INVENTARIO LOOP
		V_CATEGORIA_INVENTARIO := INV.NOMBRE_CATEGORIA_INVENTARIO;
	END LOOP;

	RETURN V_CATEGORIA_INVENTARIO;
END CATEGORIA_INVENTARIO_LISTAR_FN;


FUNCTION POSICIONES_LISTAR_FN(
	P_ID_POSICION IN FIDE_POSICIONES_TB.ID_POSICION%TYPE
)
RETURN VARCHAR2
IS
	V_POSICION FIDE_POSICIONES_TB.NOMBRE_POSICION%TYPE;

	CURSOR C_POSICION IS
		SELECT NOMBRE_POSICION
		FROM FIDE_POSICIONES_TB
		WHERE ID_POSICION = P_ID_POSICION;
BEGIN
	FOR POS IN C_POSICION LOOP
		V_POSICION := POS.NOMBRE_POSICION;
	END LOOP;

	RETURN V_POSICION;
END POSICIONES_LISTAR_FN;


FUNCTION DORSALES_LISTAR_FN(
	P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER
IS
	V_DORSAL FIDE_JUGADORES_TB.DORSAL%TYPE;

	CURSOR C_DORSAL IS
		SELECT DORSAL
		FROM FIDE_JUGADORES_TB
		WHERE ID_JUGADOR = P_ID_JUGADOR;
BEGIN
	FOR DOR IN C_DORSAL LOOP
		V_DORSAL := DOR.DORSAL;
	END LOOP;

	RETURN V_DORSAL;
END DORSALES_LISTAR_FN;


/*Indica si el partido se gano, empato o perdio*/

FUNCTION RESULTADO_PARTIDO_FN(
	P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE
)
RETURN VARCHAR2
IS
	V_GOLES_FAVOR FIDE_PARTIDOS_TB.GOLES_FAVOR%TYPE;
	V_GOLES_CONTRA FIDE_PARTIDOS_TB.GOLES_CONTRA%TYPE;
	V_RESULTADO VARCHAR2(20);

	CURSOR C_PARTIDO IS
	SELECT GOLES_FAVOR, GOLES_CONTRA
	FROM FIDE_PARTIDOS_TB
	WHERE ID_PARTIDO = P_ID_PARTIDO;

BEGIN
	OPEN C_PARTIDO;
	FETCH C_PARTIDO INTO V_GOLES_FAVOR, V_GOLES_CONTRA;

	IF C_PARTIDO%FOUND THEN
		IF V_GOLES_FAVOR > V_GOLES_CONTRA THEN
			V_RESULTADO := 'GANADO';
		ELSIF V_GOLES_FAVOR < V_GOLES_CONTRA THEN
			V_RESULTADO := 'PERDIDO';
		ELSE
			V_RESULTADO := 'EMPATE';
		END IF;
	ELSE
		V_RESULTADO := 'NO ENCONTRADO';
	END IF;

	CLOSE C_PARTIDO;

	RETURN V_RESULTADO;

END RESULTADO_PARTIDO_FN;



/*Cuenta la cantidad de jugadores que asisten a un partido*/

FUNCTION TOTAL_ASISTENCIA_PARTIDO_FN(
	P_ID_PARTIDO IN FIDE_ASISTENCIA_TB.ID_PARTIDO%TYPE
)
RETURN NUMBER
IS
	V_TOTAL NUMBER;

	CURSOR C_ASISTENCIA IS
	SELECT COUNT(*)
	FROM FIDE_ASISTENCIA_TB
	WHERE ID_PARTIDO = P_ID_PARTIDO;

BEGIN
	OPEN C_ASISTENCIA;
	FETCH C_ASISTENCIA INTO V_TOTAL;
	CLOSE C_ASISTENCIA;

	RETURN V_TOTAL;

END TOTAL_ASISTENCIA_PARTIDO_FN;




/*Suma los goles que tuvo un jugador*/

FUNCTION TOTAL_GOLES_JUGADOR_FN(
	P_ID_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER
IS
	V_TOTAL_GOLES NUMBER;

	CURSOR C_GOLES IS
	SELECT NVL(SUM(GOLES), 0)
	FROM FIDE_ESTADISTICA_JUGADOR_TB
	WHERE ID_JUGADOR = P_ID_JUGADOR;

BEGIN
	OPEN C_GOLES;
	FETCH C_GOLES INTO V_TOTAL_GOLES;
	CLOSE C_GOLES;

	RETURN V_TOTAL_GOLES;

END TOTAL_GOLES_JUGADOR_FN;




/*Suma las asistencias que tuvo un jugador*/

FUNCTION TOTAL_ASISTENCIAS_JUGADOR_FN(
	P_ID_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER
IS
	V_TOTAL_ASISTENCIAS NUMBER;

	CURSOR C_ASISTENCIAS IS
	SELECT NVL(SUM(ASISTENCIAS), 0)
	FROM FIDE_ESTADISTICA_JUGADOR_TB
	WHERE ID_JUGADOR = P_ID_JUGADOR;

BEGIN
	OPEN C_ASISTENCIAS;
	FETCH C_ASISTENCIAS INTO V_TOTAL_ASISTENCIAS;
	CLOSE C_ASISTENCIAS;

	RETURN V_TOTAL_ASISTENCIAS;

END TOTAL_ASISTENCIAS_JUGADOR_FN;




/*Suma las faltas de un jugador*/

FUNCTION TOTAL_TARJETAS_JUGADOR_FN(
	P_ID_JUGADOR IN FIDE_TARJETAS_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER
IS
	V_TOTAL_TARJETAS NUMBER;

	CURSOR C_TARJETAS IS
	SELECT NVL(SUM(CANTIDAD_TARJETAS), 0)
	FROM FIDE_TARJETAS_TB
	WHERE ID_JUGADOR = P_ID_JUGADOR
	AND ID_ESTADO = 1;

BEGIN
	OPEN C_TARJETAS;
	FETCH C_TARJETAS INTO V_TOTAL_TARJETAS;
	CLOSE C_TARJETAS;

	RETURN V_TOTAL_TARJETAS;

END TOTAL_TARJETAS_JUGADOR_FN;




/*Suma el monto pagado por un jugador*/

FUNCTION MONTO_PAGADO_JUGADOR_FN(
	P_ID_JUGADOR IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER
IS
	V_MONTO_TOTAL NUMBER;

	CURSOR C_MONTO IS
	SELECT NVL(SUM(MONTO), 0)
	FROM FIDE_FACTURACION_INSCRIPCIONES_TB
	WHERE ID_JUGADOR = P_ID_JUGADOR
	AND ID_ESTADO = 8;

BEGIN
	OPEN C_MONTO;
	FETCH C_MONTO INTO V_MONTO_TOTAL;
	CLOSE C_MONTO;

	RETURN V_MONTO_TOTAL;

END MONTO_PAGADO_JUGADOR_FN;


/*Suma la cantidad de veces que un jugador se ha lesionado*/

FUNCTION TOTAL_LESIONES_JUGADOR_FN(
	P_ID_JUGADOR IN FIDE_PARTE_MEDICO_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER
IS
	V_TOTAL_LESIONES NUMBER;

	CURSOR C_LESIONES IS /*Cuenta en colaboracion a parte medico y a lesiones*/
	SELECT COUNT(*)
	FROM FIDE_PARTE_MEDICO_TB PM
	INNER JOIN FIDE_LESIONES_TB L
	ON PM.ID_PARTEMEDICO = L.ID_PARTEMEDICO
	WHERE PM.ID_JUGADOR = P_ID_JUGADOR
	AND L.ID_ESTADO = 1;

BEGIN
	OPEN C_LESIONES;
	FETCH C_LESIONES INTO V_TOTAL_LESIONES;
	CLOSE C_LESIONES;

	RETURN V_TOTAL_LESIONES;

END TOTAL_LESIONES_JUGADOR_FN;



/*Calcula el promedio de minutos jugados de un jugador*/

FUNCTION PROMEDIO_MINUTOS_JUGADOR_FN(
	P_ID_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER
IS
	V_PROMEDIO_MINUTOS NUMBER;

	CURSOR C_MINUTOS IS
	SELECT NVL(AVG(MINUTOS_JUGADOS), 0)
	FROM FIDE_ESTADISTICA_JUGADOR_TB
	WHERE ID_JUGADOR = P_ID_JUGADOR;

BEGIN
	OPEN C_MINUTOS;
	FETCH C_MINUTOS INTO V_PROMEDIO_MINUTOS;
	CLOSE C_MINUTOS;

	RETURN V_PROMEDIO_MINUTOS;

END PROMEDIO_MINUTOS_JUGADOR_FN;