-- TRIGGERS DE LOGICA DE NEGOCIO
-- Ejecutar despues del esquema, las tuplas de auditoria y el package
-- FIDE_PROYECTOFINALACADEMIALEIVA_PCK.

CREATE OR REPLACE TRIGGER FIDE_JUGADORES_EDAD_CATEGORIA_TRG
BEFORE INSERT OR UPDATE OF FECHA_NACIMIENTO, ID_CATEGORIA ON FIDE_JUGADORES_TB
FOR EACH ROW
BEGIN
    IF FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_JUGADORES_TB_VALIDAR_EDAD_CATEGORIA_FN(
        :NEW.FECHA_NACIMIENTO, :NEW.ID_CATEGORIA
    ) = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'La edad del jugador no corresponde a la categoria seleccionada.');
    END IF;
END FIDE_JUGADORES_EDAD_CATEGORIA_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ASISTENCIA_VALIDAR_JUGADOR_TRG
BEFORE INSERT OR UPDATE OF ID_PARTIDO, ID_JUGADOR, ID_ESTADO ON FIDE_ASISTENCIA_TB
FOR EACH ROW
DECLARE
    V_CATEGORIA_JUGADOR NUMBER;
    V_CATEGORIA_PARTIDO NUMBER;
    V_ESTADO_JUGADOR NUMBER;
BEGIN
    SELECT ID_CATEGORIA, ID_ESTADO INTO V_CATEGORIA_JUGADOR, V_ESTADO_JUGADOR
    FROM FIDE_JUGADORES_TB WHERE ID_JUGADOR = :NEW.ID_JUGADOR;

    SELECT ID_CATEGORIA INTO V_CATEGORIA_PARTIDO
    FROM FIDE_PARTIDOS_TB WHERE ID_PARTIDO = :NEW.ID_PARTIDO;

    IF V_ESTADO_JUGADOR <> 1 OR V_CATEGORIA_JUGADOR <> V_CATEGORIA_PARTIDO THEN
        RAISE_APPLICATION_ERROR(-20002, 'El jugador debe estar activo y pertenecer a la categoria del partido.');
    END IF;
END FIDE_ASISTENCIA_VALIDAR_JUGADOR_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADISTICA_JUGADOR_VALIDAR_TRG
BEFORE INSERT OR UPDATE OF ID_JUGADOR, ID_PARTIDO, PASES, PASES_EXITOSOS, REGATES,
    REGATES_EXITOSOS, TIROS, TIROS_EXITOSOS, ENTRADAS, ENTRADAS_EXITOSAS, ID_ESTADO
ON FIDE_ESTADISTICA_JUGADOR_TB
FOR EACH ROW
DECLARE
    V_CATEGORIA_JUGADOR NUMBER;
    V_CATEGORIA_PARTIDO NUMBER;
    V_ESTADO_JUGADOR NUMBER;
    V_ESTADO_PARTIDO NUMBER;
    V_ASISTIO NUMBER;
BEGIN
    IF NVL(:NEW.PASES_EXITOSOS, 0) > NVL(:NEW.PASES, 0)
       OR NVL(:NEW.REGATES_EXITOSOS, 0) > NVL(:NEW.REGATES, 0)
       OR NVL(:NEW.TIROS_EXITOSOS, 0) > NVL(:NEW.TIROS, 0)
       OR NVL(:NEW.ENTRADAS_EXITOSAS, 0) > NVL(:NEW.ENTRADAS, 0) THEN
        RAISE_APPLICATION_ERROR(-20003, 'Las acciones exitosas no pueden superar las acciones totales.');
    END IF;

    SELECT ID_CATEGORIA, ID_ESTADO INTO V_CATEGORIA_JUGADOR, V_ESTADO_JUGADOR
    FROM FIDE_JUGADORES_TB WHERE ID_JUGADOR = :NEW.ID_JUGADOR;
    SELECT ID_CATEGORIA, ID_ESTADO INTO V_CATEGORIA_PARTIDO, V_ESTADO_PARTIDO
    FROM FIDE_PARTIDOS_TB WHERE ID_PARTIDO = :NEW.ID_PARTIDO;
    SELECT COUNT(*) INTO V_ASISTIO FROM FIDE_ASISTENCIA_TB
    WHERE ID_PARTIDO = :NEW.ID_PARTIDO AND ID_JUGADOR = :NEW.ID_JUGADOR AND ID_ESTADO IN (1, 4);

    IF V_ESTADO_JUGADOR <> 1 OR V_CATEGORIA_JUGADOR <> V_CATEGORIA_PARTIDO OR V_ASISTIO = 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'El jugador debe estar activo, asistir y pertenecer a la categoria del partido.');
    END IF;
    IF V_ESTADO_PARTIDO <> 4 THEN
        RAISE_APPLICATION_ERROR(-20005, 'Solo se pueden registrar estadisticas para partidos completados.');
    END IF;
END FIDE_ESTADISTICA_JUGADOR_VALIDAR_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TARJETAS_VALIDAR_JUGADOR_TRG
BEFORE INSERT OR UPDATE OF ID_PARTIDO, ID_JUGADOR, ID_ESTADO ON FIDE_TARJETAS_TB
FOR EACH ROW
DECLARE
    V_CATEGORIA_JUGADOR NUMBER;
    V_CATEGORIA_PARTIDO NUMBER;
    V_ESTADO_JUGADOR NUMBER;
    V_ASISTIO NUMBER;
BEGIN
    SELECT ID_CATEGORIA, ID_ESTADO INTO V_CATEGORIA_JUGADOR, V_ESTADO_JUGADOR
    FROM FIDE_JUGADORES_TB WHERE ID_JUGADOR = :NEW.ID_JUGADOR;
    SELECT ID_CATEGORIA INTO V_CATEGORIA_PARTIDO FROM FIDE_PARTIDOS_TB WHERE ID_PARTIDO = :NEW.ID_PARTIDO;
    SELECT COUNT(*) INTO V_ASISTIO FROM FIDE_ASISTENCIA_TB
    WHERE ID_PARTIDO = :NEW.ID_PARTIDO AND ID_JUGADOR = :NEW.ID_JUGADOR AND ID_ESTADO IN (1, 4);

    IF V_ESTADO_JUGADOR <> 1 OR V_CATEGORIA_JUGADOR <> V_CATEGORIA_PARTIDO OR V_ASISTIO = 0 THEN
        RAISE_APPLICATION_ERROR(-20006, 'La tarjeta requiere un jugador activo, asistente y de la categoria del partido.');
    END IF;
END FIDE_TARJETAS_VALIDAR_JUGADOR_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PARTIDOS_COMPLETAR_VALIDAR_TRG
BEFORE INSERT OR UPDATE OF ID_ESTADO, GOLES_FAVOR, GOLES_CONTRA ON FIDE_PARTIDOS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_ESTADO = 4 AND (:NEW.GOLES_FAVOR IS NULL OR :NEW.GOLES_CONTRA IS NULL) THEN
        RAISE_APPLICATION_ERROR(-20007, 'Un partido completado debe tener ambos marcadores.');
    END IF;
END FIDE_PARTIDOS_COMPLETAR_VALIDAR_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADISTICA_JUGADOR_MARCADOR_TRG
AFTER INSERT OR UPDATE OF GOLES, ID_ESTADO, ID_PARTIDO OR DELETE ON FIDE_ESTADISTICA_JUGADOR_TB
FOR EACH ROW
DECLARE
    V_GOLES_OLD NUMBER := 0;
    V_GOLES_NEW NUMBER := 0;
BEGIN
    IF INSERTING OR UPDATING THEN
        V_GOLES_NEW := CASE WHEN :NEW.ID_ESTADO IN (1, 4) THEN NVL(:NEW.GOLES, 0) ELSE 0 END;
        UPDATE FIDE_PARTIDOS_TB
        SET GOLES_FAVOR = NVL(GOLES_FAVOR, 0) + V_GOLES_NEW
        WHERE ID_PARTIDO = :NEW.ID_PARTIDO;
    END IF;

    IF DELETING OR UPDATING THEN
        V_GOLES_OLD := CASE WHEN :OLD.ID_ESTADO IN (1, 4) THEN NVL(:OLD.GOLES, 0) ELSE 0 END;
        UPDATE FIDE_PARTIDOS_TB
        SET GOLES_FAVOR = GREATEST(NVL(GOLES_FAVOR, 0) - V_GOLES_OLD, 0)
        WHERE ID_PARTIDO = :OLD.ID_PARTIDO;
    END IF;
END FIDE_ESTADISTICA_JUGADOR_MARCADOR_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADISTICA_JUGADOR_EQUIPO_TRG
AFTER INSERT OR UPDATE OF PASES, PASES_EXITOSOS, TIROS, TIROS_EXITOSOS, ID_ESTADO, ID_PARTIDO OR DELETE ON FIDE_ESTADISTICA_JUGADOR_TB
FOR EACH ROW
DECLARE
    V_FACTOR_OLD NUMBER := 0;
    V_FACTOR_NEW NUMBER := 0;
BEGIN
    IF INSERTING OR UPDATING THEN
        V_FACTOR_NEW := CASE WHEN :NEW.ID_ESTADO IN (1, 4) THEN 1 ELSE 0 END;
        MERGE INTO FIDE_ESTADISTICA_EQUIPO_TB EE
        USING (SELECT :NEW.ID_PARTIDO AS ID_PARTIDO FROM DUAL) X ON (EE.ID_PARTIDO = X.ID_PARTIDO)
        WHEN MATCHED THEN UPDATE SET
            EE.TIROS = NVL(EE.TIROS, 0) + (NVL(:NEW.TIROS, 0) * V_FACTOR_NEW),
            EE.TIROS_PORTERIA = NVL(EE.TIROS_PORTERIA, 0) + (NVL(:NEW.TIROS_EXITOSOS, 0) * V_FACTOR_NEW),
            EE.PASES_EXITOSOS = NVL(EE.PASES_EXITOSOS, 0) + (NVL(:NEW.PASES_EXITOSOS, 0) * V_FACTOR_NEW),
            EE.PASES_FALLIDOS = NVL(EE.PASES_FALLIDOS, 0) + ((NVL(:NEW.PASES, 0) - NVL(:NEW.PASES_EXITOSOS, 0)) * V_FACTOR_NEW)
        WHEN NOT MATCHED THEN INSERT (ID_ESTADISTICA_EQUIPO, TIROS, TIROS_PORTERIA, PASES_EXITOSOS, PASES_FALLIDOS, ID_PARTIDO, ID_ESTADO)
            VALUES (ID_ESTADISTICA_EQUIPO_SEQ.NEXTVAL, NVL(:NEW.TIROS, 0) * V_FACTOR_NEW,
                NVL(:NEW.TIROS_EXITOSOS, 0) * V_FACTOR_NEW, NVL(:NEW.PASES_EXITOSOS, 0) * V_FACTOR_NEW,
                (NVL(:NEW.PASES, 0) - NVL(:NEW.PASES_EXITOSOS, 0)) * V_FACTOR_NEW, :NEW.ID_PARTIDO, 1);
    END IF;

    IF DELETING OR UPDATING THEN
        V_FACTOR_OLD := CASE WHEN :OLD.ID_ESTADO IN (1, 4) THEN 1 ELSE 0 END;
        UPDATE FIDE_ESTADISTICA_EQUIPO_TB
        SET TIROS = GREATEST(NVL(TIROS, 0) - (NVL(:OLD.TIROS, 0) * V_FACTOR_OLD), 0),
            TIROS_PORTERIA = GREATEST(NVL(TIROS_PORTERIA, 0) - (NVL(:OLD.TIROS_EXITOSOS, 0) * V_FACTOR_OLD), 0),
            PASES_EXITOSOS = GREATEST(NVL(PASES_EXITOSOS, 0) - (NVL(:OLD.PASES_EXITOSOS, 0) * V_FACTOR_OLD), 0),
            PASES_FALLIDOS = GREATEST(NVL(PASES_FALLIDOS, 0) - ((NVL(:OLD.PASES, 0) - NVL(:OLD.PASES_EXITOSOS, 0)) * V_FACTOR_OLD), 0)
        WHERE ID_PARTIDO = :OLD.ID_PARTIDO;
    END IF;
END FIDE_ESTADISTICA_JUGADOR_EQUIPO_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_LESIONES_VALIDAR_TRG
BEFORE INSERT OR UPDATE OF FECHA_RECUPERACION, ID_PARTEMEDICO ON FIDE_LESIONES_TB
FOR EACH ROW
DECLARE
    V_FECHA_PARTE DATE;
BEGIN
    SELECT FECHA INTO V_FECHA_PARTE FROM FIDE_PARTE_MEDICO_TB WHERE ID_PARTEMEDICO = :NEW.ID_PARTEMEDICO;
    IF :NEW.FECHA_RECUPERACION IS NOT NULL AND :NEW.FECHA_RECUPERACION < V_FECHA_PARTE THEN
        RAISE_APPLICATION_ERROR(-20008, 'La fecha de recuperacion no puede ser anterior al parte medico.');
    END IF;
END FIDE_LESIONES_VALIDAR_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURACION_PAGO_VALIDAR_TRG
BEFORE INSERT OR UPDATE OF ID_ESTADO, FECHA_PAGO ON FIDE_FACTURACION_INSCRIPCIONES_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_ESTADO = 8 AND :NEW.FECHA_PAGO IS NULL THEN
        RAISE_APPLICATION_ERROR(-20009, 'Una factura pagada debe tener fecha de pago.');
    ELSIF :NEW.ID_ESTADO = 9 AND :NEW.FECHA_PAGO IS NOT NULL THEN
        RAISE_APPLICATION_ERROR(-20010, 'Una factura pendiente no puede tener fecha de pago.');
    END IF;
END FIDE_FACTURACION_PAGO_VALIDAR_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_REVISION_FISICA_IMC_TRG
BEFORE INSERT OR UPDATE OF PESO, ALTURA, FECHA_REVISION ON FIDE_REVISION_FISICA_TB
FOR EACH ROW
BEGIN
    IF :NEW.FECHA_REVISION > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20011, 'La fecha de revision fisica no puede estar en el futuro.');
    END IF;
    :NEW.IMC := ROUND(:NEW.PESO / POWER(:NEW.ALTURA, 2), 2);
END FIDE_REVISION_FISICA_IMC_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ARTICULOS_DISPONIBILIDAD_TRG
BEFORE INSERT OR UPDATE OF CANTIDAD ON FIDE_ARTICULOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := CASE WHEN :NEW.CANTIDAD = 0 THEN 11 ELSE 10 END;
END FIDE_ARTICULOS_DISPONIBILIDAD_TRG;
/
