
CREATE TABLE FIDE_ESTADOS_TB (
    ID_ESTADO NUMBER NOT NULL,
    NOMBRE_ESTADO VARCHAR2(100),
    CONSTRAINT ESTADOS_ID_ESTADO_PK
        PRIMARY KEY (ID_ESTADO)
);

CREATE TABLE FIDE_TIPOTARJETAS_TB (
    ID_TIPOTARJETA NUMBER NOT NULL,
    COLOR VARCHAR2(100),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT TIPOTARJETAS_ID_TIPOTARJETA_PK
        PRIMARY KEY (ID_TIPOTARJETA),
    CONSTRAINT TIPOTARJETAS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_CANTONES_TB (
    ID_CANTON NUMBER NOT NULL,
    NOMBRE_CANTON VARCHAR2(100),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT CANTONES_ID_CANTON_PK
        PRIMARY KEY (ID_CANTON),
    CONSTRAINT CANTONES_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_CARGOS_TB (
    ID_CARGO NUMBER NOT NULL,
    NOMBRE_CARGO VARCHAR2(100),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT CARGOS_ID_CARGO_PK
        PRIMARY KEY (ID_CARGO),
    CONSTRAINT CARGOS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT CARGOS_NOMBRE_UK
        UNIQUE (NOMBRE_CARGO)
);

CREATE TABLE FIDE_CATEGORIAS_TB (
    ID_CATEGORIA NUMBER NOT NULL,
    NOMBRE_CATEGORIA VARCHAR2(100),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT CATEGORIAS_ID_CATEGORIA_PK
        PRIMARY KEY (ID_CATEGORIA),
    CONSTRAINT CATEGORIAS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT CATEGORIAS_NOMBRE_UK
        UNIQUE (NOMBRE_CATEGORIA)
);

CREATE TABLE FIDE_CATEGORIA_INVENTARIO_TB (
    ID_CATEGORIAINVENTARIO NUMBER NOT NULL,
    NOMBRE_CATEGORIA_INVENTARIO VARCHAR2(100),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT CATEGORIA_INVENTARIO_ID_CATEGORIAINVENTARIO_PK
        PRIMARY KEY (ID_CATEGORIAINVENTARIO),
    CONSTRAINT CATEGORIA_INVENTARIO_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_DISTRITOS_TB (
    ID_DISTRITO NUMBER NOT NULL,
    NOMBRE_DISTRITO VARCHAR2(100),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT DISTRITOS_ID_DISTRITO_PK
        PRIMARY KEY (ID_DISTRITO),
    CONSTRAINT DISTRITOS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_ESPECIALIDADES_TB (
    ID_ESPECIALIDAD NUMBER NOT NULL,
    NOMBRE_ESPECIALIDAD VARCHAR2(100),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT ESPECIALIDADES_ID_ESPECIALIDAD_PK
        PRIMARY KEY (ID_ESPECIALIDAD),
    CONSTRAINT ESPECIALIDADES_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT ESPECIALIDADES_NOMBRE_UK
        UNIQUE (NOMBRE_ESPECIALIDAD)
);

CREATE TABLE FIDE_POSICIONES_TB (
    ID_POSICION NUMBER NOT NULL,
    NOMBRE_POSICION VARCHAR2(100),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT POSICIONES_ID_POSICION_PK
        PRIMARY KEY (ID_POSICION),
    CONSTRAINT POSICIONES_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT POSICIONES_NOMBRE_UK
        UNIQUE (NOMBRE_POSICION)
);

CREATE TABLE FIDE_PROVINCIAS_TB (
    ID_PROVINCIA NUMBER NOT NULL,
    NOMBRE_PROVINCIA VARCHAR2(100),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT PROVINCIAS_ID_PROVINCIA_PK
        PRIMARY KEY (ID_PROVINCIA),
    CONSTRAINT PROVINCIAS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_TEMPORADAS_TB (
    ID_TEMPORADA NUMBER NOT NULL,
    TIPO_TEMPORADA VARCHAR2(100),
    ANIO NUMBER(4),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT TEMPORADAS_ID_TEMPORADA_PK
        PRIMARY KEY (ID_TEMPORADA),
    CONSTRAINT TEMPORADAS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_TIPOLESION_TB (
    ID_TIPOLESION NUMBER NOT NULL,
    NOMBRE_TIPO_LESION VARCHAR2(100),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT TIPOLESION_ID_TIPOLESION_PK
        PRIMARY KEY (ID_TIPOLESION),
    CONSTRAINT TIPOLESION_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_TIPO_PARTIDOS_TB (
    ID_TIPOPARTIDOS NUMBER NOT NULL,
    TIPO_DE_PARTIDO VARCHAR2(100),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT TIPO_PARTIDOS_ID_TIPOPARTIDOS_PK
        PRIMARY KEY (ID_TIPOPARTIDOS),
    CONSTRAINT TIPO_PARTIDOS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT TIPO_PARTIDOS_NOMBRE_UK
        UNIQUE (TIPO_DE_PARTIDO)
);

CREATE TABLE FIDE_ARTICULOS_TB (
    ID_ARTICULO NUMBER NOT NULL,
    ID_CATEGORIAINVENTARIO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CANTIDAD NUMBER,
    NOMBRE_ARTICULO VARCHAR2(100),
    CONSTRAINT ARTICULOS_ID_ARTICULO_PK
        PRIMARY KEY (ID_ARTICULO),
    CONSTRAINT ARTICULOS_ID_CATEGORIAINVENTARIO_FK
        FOREIGN KEY (ID_CATEGORIAINVENTARIO) REFERENCES FIDE_CATEGORIA_INVENTARIO_TB(ID_CATEGORIAINVENTARIO),
    CONSTRAINT ARTICULOS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT ARTICULOS_CANTIDAD_CK
        CHECK (CANTIDAD >= 0),
    CONSTRAINT ARTICULOS_CATEGORIA_NOMBRE_UK
        UNIQUE (ID_CATEGORIAINVENTARIO, NOMBRE_ARTICULO)
);

CREATE TABLE FIDE_DIRECCION_EXACTA_TB (
    ID_DIRECCION_EXACTA NUMBER NOT NULL,
    OTRAS_SENIAS VARCHAR2(255),
    ID_DISTRITO NUMBER NOT NULL,
    ID_CANTON NUMBER NOT NULL,
    ID_PROVINCIA NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT DIRECCION_EXACTA_ID_DIRECCION_EXACTA_PK
        PRIMARY KEY (ID_DIRECCION_EXACTA),
    CONSTRAINT DIRECCION_EXACTA_ID_DISTRITO_FK
        FOREIGN KEY (ID_DISTRITO) REFERENCES FIDE_DISTRITOS_TB(ID_DISTRITO),
    CONSTRAINT DIRECCION_EXACTA_ID_CANTON_FK
        FOREIGN KEY (ID_CANTON) REFERENCES FIDE_CANTONES_TB(ID_CANTON),
    CONSTRAINT DIRECCION_EXACTA_ID_PROVINCIA_FK
        FOREIGN KEY (ID_PROVINCIA) REFERENCES FIDE_PROVINCIAS_TB(ID_PROVINCIA),
    CONSTRAINT DIRECCION_EXACTA_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_MEDICOS_TB (
    ID_MEDICO NUMBER NOT NULL,
    NOMBRE VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    ID_ESPECIALIDAD NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT MEDICOS_ID_MEDICO_PK
        PRIMARY KEY (ID_MEDICO),
    CONSTRAINT MEDICOS_ID_ESPECIALIDAD_FK
        FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES FIDE_ESPECIALIDADES_TB(ID_ESPECIALIDAD),
    CONSTRAINT MEDICOS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_EMPLEADOS_TB (
    ID_EMPLEADO NUMBER NOT NULL,
    NOMBRE VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    EDAD NUMBER,
    NOMBRE_DE_USUARIO VARCHAR2(100),
    CONTRASENIA VARCHAR2(100),
    ID_CARGO NUMBER NOT NULL,
    ID_DIRECCION_EXACTA NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT EMPLEADOS_ID_EMPLEADO_PK
        PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT EMPLEADOS_ID_CARGO_FK
        FOREIGN KEY (ID_CARGO) REFERENCES FIDE_CARGOS_TB(ID_CARGO),
    CONSTRAINT EMPLEADOS_ID_DIRECCION_EXACTA_FK
        FOREIGN KEY (ID_DIRECCION_EXACTA) REFERENCES FIDE_DIRECCION_EXACTA_TB(ID_DIRECCION_EXACTA),
    CONSTRAINT EMPLEADOS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_JUGADORES_TB (
    ID_JUGADOR NUMBER NOT NULL,
    ID_CATEGORIA NUMBER NOT NULL,
    NOMBRE VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100),
    DORSAL NUMBER,
    EDAD NUMBER,
    ID_ESTADO NUMBER NOT NULL,
    ID_DIRECCION_EXACTA NUMBER NOT NULL,
    CONSTRAINT JUGADORES_ID_JUGADOR_PK
        PRIMARY KEY (ID_JUGADOR),
    CONSTRAINT JUGADORES_ID_CATEGORIA_FK
        FOREIGN KEY (ID_CATEGORIA) REFERENCES FIDE_CATEGORIAS_TB(ID_CATEGORIA),
    CONSTRAINT JUGADORES_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT JUGADORES_ID_DIRECCION_EXACTA_FK
        FOREIGN KEY (ID_DIRECCION_EXACTA) REFERENCES FIDE_DIRECCION_EXACTA_TB(ID_DIRECCION_EXACTA),
    CONSTRAINT JUGADORES_EDAD_CK
        CHECK (EDAD >= 0),
    CONSTRAINT JUGADORES_DORSAL_CK
        CHECK (DORSAL BETWEEN 1 AND 99),
    CONSTRAINT JUGADORES_CATEGORIA_DORSAL_UK
        UNIQUE (ID_CATEGORIA,DORSAL)
);


CREATE TABLE FIDE_FACTURACION_INSCRIPCIONES_TB (
    ID_FACTURACION_INSCRIPCION NUMBER NOT NULL,
    ID_JUGADOR NUMBER NOT NULL,
    MES NUMBER NOT NULL,
    ANIO NUMBER(4) NOT NULL,
    MONTO NUMBER(10,2) NOT NULL,
    FECHA_PAGO DATE,
    ID_ESTADO NUMBER NOT NULL,
    OBSERVACIONES VARCHAR2(255),
    CONSTRAINT FACTURACION_INSCRIPCIONES_ID_FACTURACION_INSCRIPCION_PK
        PRIMARY KEY (ID_FACTURACION_INSCRIPCION),
    CONSTRAINT FACTURACION_INSCRIPCIONES_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR)
        REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT FACTURACION_INSCRIPCIONES_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FACTURACION_INSCRIPCIONES_MES_CK
        CHECK (MES BETWEEN 1 AND 12),
    CONSTRAINT FACTURACION_INSCRIPCIONES_ANIO_CK
        CHECK (ANIO >= 2000),
    CONSTRAINT FACTURACION_INSCRIPCIONES_MONTO_CK
        CHECK (MONTO >= 0),
    CONSTRAINT FACTURACION_INSCRIPCIONES_JUGADOR_MES_ANIO_UK
        UNIQUE (ID_JUGADOR, MES, ANIO)
);


CREATE TABLE FIDE_SEDES_TB (
    ID_SEDE NUMBER NOT NULL,
    NOMBRE_SEDE VARCHAR2(100),
    ID_DIRECCION_EXACTA NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT SEDES_ID_SEDE_PK
        PRIMARY KEY (ID_SEDE),
    CONSTRAINT SEDES_ID_DIRECCION_EXACTA_FK
        FOREIGN KEY (ID_DIRECCION_EXACTA) REFERENCES FIDE_DIRECCION_EXACTA_TB(ID_DIRECCION_EXACTA),
    CONSTRAINT SEDES_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_JUGADOR_POSICIONES_TB (
    ID_JUGADOR NUMBER NOT NULL,
    ID_POSICION NUMBER NOT NULL,
    CONSTRAINT JUGADOR_POSICIONES_ID_JUGADOR_ID_POSICION_PK
        PRIMARY KEY (ID_JUGADOR, ID_POSICION),
    CONSTRAINT JUGADOR_POSICIONES_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT JUGADOR_POSICIONES_ID_POSICION_FK
        FOREIGN KEY (ID_POSICION) REFERENCES FIDE_POSICIONES_TB(ID_POSICION)
);

CREATE TABLE FIDE_PARTE_MEDICO_TB (
    ID_PARTEMEDICO NUMBER NOT NULL,
    ID_JUGADOR NUMBER NOT NULL,
    OBSERVACIONES VARCHAR2(255),
    FECHA DATE,
    ID_MEDICO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT PARTE_MEDICO_ID_PARTEMEDICO_PK
        PRIMARY KEY (ID_PARTEMEDICO),
    CONSTRAINT PARTE_MEDICO_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT PARTE_MEDICO_ID_MEDICO_FK
        FOREIGN KEY (ID_MEDICO) REFERENCES FIDE_MEDICOS_TB(ID_MEDICO),
    CONSTRAINT PARTE_MEDICO_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_PARTIDOS_TB (
    ID_PARTIDO NUMBER NOT NULL,
    ID_CATEGORIA NUMBER NOT NULL,
    ID_TIPOPARTIDOS NUMBER NOT NULL,
    ID_TEMPORADA NUMBER NOT NULL,
    FECHA DATE,
    RIVAL VARCHAR2(100),
    GOLES_FAVOR NUMBER,
    GOLES_CONTRA NUMBER,
    ID_SEDE NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT PARTIDOS_ID_PARTIDO_PK
        PRIMARY KEY (ID_PARTIDO),
    CONSTRAINT PARTIDOS_ID_CATEGORIA_FK
        FOREIGN KEY (ID_CATEGORIA) REFERENCES FIDE_CATEGORIAS_TB(ID_CATEGORIA),
    CONSTRAINT PARTIDOS_ID_TIPOPARTIDOS_FK
        FOREIGN KEY (ID_TIPOPARTIDOS) REFERENCES FIDE_TIPO_PARTIDOS_TB(ID_TIPOPARTIDOS),
    CONSTRAINT PARTIDOS_ID_TEMPORADA_FK
        FOREIGN KEY (ID_TEMPORADA) REFERENCES FIDE_TEMPORADAS_TB(ID_TEMPORADA),
    CONSTRAINT PARTIDOS_ID_SEDE_FK
        FOREIGN KEY (ID_SEDE) REFERENCES FIDE_SEDES_TB(ID_SEDE),
    CONSTRAINT PARTIDOS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT PARTIDOS_GOLES_FAVOR_CK
        CHECK(GOLES_FAVOR >= 0),
    CONSTRAINT PARTIDOS_GOLES_CONTRA_CK
        CHECK(GOLES_CONTRA >= 0)
);

CREATE TABLE FIDE_REVISION_FISICA_TB (
    ID_REVISION NUMBER NOT NULL,
    ID_JUGADOR NUMBER NOT NULL,
    PESO NUMBER(8,2),
    IMC NUMBER(8,2),
    ALTURA NUMBER(8,2),
    FECHA_REVISION DATE,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT REVISION_FISICA_ID_REVISION_PK
        PRIMARY KEY (ID_REVISION),
    CONSTRAINT REVISION_FISICA_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT REVISION_FISICA_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT REVISION_FISICA_PESO_CK
        CHECK (PESO > 0),
    CONSTRAINT REVISION_FISICA_ALTURA_CK
        CHECK (ALTURA > 0),
    CONSTRAINT REVISION_FISICA_IMC_CK
        CHECK (IMC > 0)
            
);

CREATE TABLE FIDE_TELEFONOS_TB (
    ID_TELEFONO NUMBER NOT NULL,
    NUMERO_TELEFONO VARCHAR2(20),
    ID_EMPLEADO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT TELEFONOS_ID_TELEFONO_PK
        PRIMARY KEY (ID_TELEFONO),
    CONSTRAINT TELEFONOS_ID_EMPLEADO_FK
        FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADOS_TB(ID_EMPLEADO),
    CONSTRAINT TELEFONOS_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT TELEFONOS_NUMERO_UK
        UNIQUE (NUMERO_TELEFONO),
    CONSTRAINT TELEFONOS_NUMERO_CK
        CHECK (LENGTH(NUMERO_TELEFONO) >= 8)
);

CREATE TABLE FIDE_ASISTENCIA_TB (
    ID_PARTIDO NUMBER NOT NULL,
    ID_JUGADOR NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT ASISTENCIA_ID_PARTIDO_ID_JUGADOR_PK
        PRIMARY KEY (ID_PARTIDO, ID_JUGADOR),
    CONSTRAINT ASISTENCIA_ID_PARTIDO_FK
        FOREIGN KEY (ID_PARTIDO) REFERENCES FIDE_PARTIDOS_TB(ID_PARTIDO),
    CONSTRAINT ASISTENCIA_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT ASISTENCIA_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_ESTADISTICA_EQUIPO_TB (
    ID_ESTADISTICA_EQUIPO NUMBER NOT NULL,
    TIROS NUMBER,
    TIROS_PORTERIA NUMBER,
    PASES_EXITOSOS NUMBER,
    PASES_FALLIDOS NUMBER,
    POSESION_BALON NUMBER(8,2),
    ID_PARTIDO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT ESTADISTICA_EQUIPO_ID_ESTADISTICA_EQUIPO_PK
        PRIMARY KEY (ID_ESTADISTICA_EQUIPO),
    CONSTRAINT ESTADISTICA_EQUIPO_ID_PARTIDO_FK
        FOREIGN KEY (ID_PARTIDO) REFERENCES FIDE_PARTIDOS_TB(ID_PARTIDO),
    CONSTRAINT ESTADISTICA_EQUIPO_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT ESTADISTICA_EQUIPO_POSESION_CK
        CHECK (POSESION_BALON BETWEEN 0 AND 100),
    CONSTRAINT ESTADISTICA_EQUIPO_TIROS_PORTERIA_CK
        CHECK (TIROS_PORTERIA >= 0),
    CONSTRAINT ESTADISTICA_EQUIPO_TIROS_CK
        CHECK (TIROS >= 0),
    CONSTRAINT ESTADISTICA_EQUIPO_PARTIDO_UK
        UNIQUE (ID_PARTIDO)
    
);

CREATE TABLE FIDE_ESTADISTICA_JUGADOR_TB (
    ID_ESTADISTICA_JUGADOR NUMBER NOT NULL,
    ID_JUGADOR NUMBER NOT NULL,
    ID_PARTIDO NUMBER NOT NULL,
    PASES NUMBER,
    PASES_EXITOSOS NUMBER,
    REGATES NUMBER,
    REGATES_EXITOSOS NUMBER,
    TIROS NUMBER,
    TIROS_EXITOSOS NUMBER,
    ENTRADAS NUMBER,
    ENTRADAS_EXITOSAS NUMBER,
    MINUTOS_JUGADOS NUMBER,
    GOLES NUMBER,
    ASISTENCIAS NUMBER,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT ESTADISTICA_JUGADOR_ID_ESTADISTICA_JUGADOR_PK
        PRIMARY KEY (ID_ESTADISTICA_JUGADOR),
    CONSTRAINT ESTADISTICA_JUGADOR_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT ESTADISTICA_JUGADOR_ID_PARTIDO_FK
        FOREIGN KEY (ID_PARTIDO) REFERENCES FIDE_PARTIDOS_TB(ID_PARTIDO),
    CONSTRAINT ESTADISTICA_JUGADOR_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT ESTADISTICA_JUGADOR_JUGADOR_PARTIDO_UQ
        UNIQUE (ID_JUGADOR,ID_PARTIDO),
    CONSTRAINT ESTADISTICA_JUGADOR_PASES_CK
        CHECK (PASES >= 0),
    CONSTRAINT ESTADISTICA_JUGADOR_PASES_EXITOSOS_CK
        CHECK (PASES_EXITOSOS >= 0),
    CONSTRAINT ESTADISTICA_JUGADOR_REGATES_CK
        CHECK (REGATES >= 0),
    CONSTRAINT ESTADISTICA_JUGADOR_REGATES_EXITOSOS_CK
        CHECK (REGATES_EXITOSOS >= 0),
    CONSTRAINT ESTADISTICA_JUGADOR_TIROS_CK
        CHECK (TIROS >= 0),
    CONSTRAINT ESTADISTICA_JUGADOR_TIROS_EXITOSOS_CK
        CHECK (TIROS_EXITOSOS >= 0),
    CONSTRAINT ESTADISTICA_JUGADOR_ENTRADAS_CK
        CHECK (ENTRADAS >= 0),
    CONSTRAINT ESTADISTICA_JUGADOR_ENTRADAS_EXITOSAS_CK
        CHECK (ENTRADAS_EXITOSAS >= 0),
    CONSTRAINT ESTADISTICA_JUGADOR_MINUTOS_CK
        CHECK (MINUTOS_JUGADOS BETWEEN 0 AND 120),
    CONSTRAINT ESTADISTICA_JUGADOR_GOLES_CK
        CHECK (GOLES >= 0),
    CONSTRAINT ESTADISTICA_JUGADOR_ASISTENCIAS_CK
        CHECK (ASISTENCIAS >= 0)
        
);

CREATE TABLE FIDE_LESIONES_TB (
    ID_LESION NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(255),
    FECHA_RECUPERACION DATE,
    ID_TIPOLESION NUMBER NOT NULL,
    ID_PARTEMEDICO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT LESIONES_ID_LESION_PK
        PRIMARY KEY (ID_LESION),
    CONSTRAINT LESIONES_ID_TIPOLESION_FK
        FOREIGN KEY (ID_TIPOLESION) REFERENCES FIDE_TIPOLESION_TB(ID_TIPOLESION),
    CONSTRAINT LESIONES_ID_PARTEMEDICO_FK
        FOREIGN KEY (ID_PARTEMEDICO) REFERENCES FIDE_PARTE_MEDICO_TB(ID_PARTEMEDICO),
    CONSTRAINT LESIONES_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_TARJETAS_TB (
    ID_PARTIDO NUMBER NOT NULL,
    ID_JUGADOR NUMBER NOT NULL,
    ID_TIPOTARJETA NUMBER NOT NULL,
    CANTIDAD_TARJETAS NUMBER,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT TARJETAS_ID_PARTIDO_ID_JUGADOR_ID_TIPOTARJETA_PK
        PRIMARY KEY (ID_PARTIDO, ID_JUGADOR, ID_TIPOTARJETA),
    CONSTRAINT TARJETAS_ID_PARTIDO_FK
        FOREIGN KEY (ID_PARTIDO) REFERENCES FIDE_PARTIDOS_TB(ID_PARTIDO),
    CONSTRAINT TARJETAS_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT TARJETAS_ID_TIPOTARJETA_FK
        FOREIGN KEY (ID_TIPOTARJETA) REFERENCES FIDE_TIPOTARJETAS_TB(ID_TIPOTARJETA),
    CONSTRAINT TARJETAS_CANTIDAD_CK
        CHECK (CANTIDAD_TARJETAS BETWEEN 0 AND 2),
    CONSTRAINT TAJETAS_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
