CREATE SEQUENCE ID_ESTADO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_TIPOTARJETA_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_CANTON_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_CARGO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_CATEGORIA_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_CATEGORIAINVENTARIO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_DISTRITO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_ESPECIALIDAD_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_POSICION_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_PROVINCIA_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_TEMPORADA_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_TIPOLESION_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_TIPOPARTIDOS_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_ARTICULO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_DIRECCION_EXACTA_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_MEDICO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_EMPLEADO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_JUGADOR_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_FACTURACION_INSCRIPCION_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_SEDE_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_PARTEMEDICO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_PARTIDO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_REVISION_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_TELEFONO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_CORREO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_ESTADISTICA_EQUIPO_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_ESTADISTICA_JUGADOR_SEQ
START WITH 8570
INCREMENT BY 1;

CREATE SEQUENCE ID_LESION_SEQ
START WITH 8570
INCREMENT BY 1;
