-- TRIGGERS DE AUDITORIA PARA UPDATE

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_ESTADOS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPOTARJETAS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPOTARJETAS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_TIPOTARJETAS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CANTONES_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_CANTONES_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CARGOS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_CARGOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_CARGOS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_CATEGORIAS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_INVENTARIO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_CATEGORIA_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_CATEGORIA_INVENTARIO_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_DISTRITOS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESPECIALIDADES_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ESPECIALIDADES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_ESPECIALIDADES_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_POSICIONES_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_POSICIONES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_POSICIONES_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_PROVINCIAS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TEMPORADAS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_TEMPORADAS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_TEMPORADAS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPOLESION_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPOLESION_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_TIPOLESION_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_PARTIDOS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_PARTIDOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_TIPO_PARTIDOS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ARTICULOS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ARTICULOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_ARTICULOS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_EXACTA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_DIRECCION_EXACTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_DIRECCION_EXACTA_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MEDICOS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_MEDICOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_MEDICOS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EMPLEADOS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_EMPLEADOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_EMPLEADOS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_JUGADORES_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_JUGADORES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_JUGADORES_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURACION_INSCRIPCIONES_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_FACTURACION_INSCRIPCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_FACTURACION_INSCRIPCIONES_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEDES_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_SEDES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_SEDES_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_JUGADOR_POSICIONES_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_JUGADOR_POSICIONES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_JUGADOR_POSICIONES_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PARTE_MEDICO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_PARTE_MEDICO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_PARTE_MEDICO_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PARTIDOS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_PARTIDOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_PARTIDOS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_REVISION_FISICA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_REVISION_FISICA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_REVISION_FISICA_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TELEFONOS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_TELEFONOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_TELEFONOS_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ASISTENCIA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ASISTENCIA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_ASISTENCIA_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADISTICA_EQUIPO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ESTADISTICA_EQUIPO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_ESTADISTICA_EQUIPO_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADISTICA_JUGADOR_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ESTADISTICA_JUGADOR_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_ESTADISTICA_JUGADOR_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_LESIONES_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_LESIONES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_LESIONES_TB_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TARJETAS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_TARJETAS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'UPDATE';
END FIDE_TARJETAS_TB_UPDATE_TRG;
/


--- TRIGGERS DE AUDITORIA PARA INSERT


-- TRIGGERS DE AUDITORIA PARA INSERT

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ESTADOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPOTARJETAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TIPOTARJETAS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TIPOTARJETAS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CANTONES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_CANTONES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CARGOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CARGOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_CARGOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_CATEGORIAS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_INVENTARIO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CATEGORIA_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_CATEGORIA_INVENTARIO_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_DISTRITOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESPECIALIDADES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ESPECIALIDADES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ESPECIALIDADES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_POSICIONES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_POSICIONES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_POSICIONES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_PROVINCIAS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TEMPORADAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TEMPORADAS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TEMPORADAS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPOLESION_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TIPOLESION_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TIPOLESION_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_PARTIDOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_PARTIDOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TIPO_PARTIDOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ARTICULOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ARTICULOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ARTICULOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_EXACTA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_DIRECCION_EXACTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_DIRECCION_EXACTA_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MEDICOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_MEDICOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_MEDICOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EMPLEADOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_EMPLEADOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_EMPLEADOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_JUGADORES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_JUGADORES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_JUGADORES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURACION_INSCRIPCIONES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_FACTURACION_INSCRIPCIONES_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_FACTURACION_INSCRIPCION IS NULL THEN
        :NEW.ID_FACTURACION_INSCRIPCION :=
            FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_FACTURACION_INSCRIPCIONES_TB_GENERAR_SEQUENCIA_NUM_SEQ_FN;
    END IF;
END;
/


CREATE OR REPLACE TRIGGER FIDE_SEDES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_SEDES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_SEDES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_JUGADOR_POSICIONES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_JUGADOR_POSICIONES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_JUGADOR_POSICIONES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PARTE_MEDICO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_PARTE_MEDICO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_PARTE_MEDICO_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PARTIDOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_PARTIDOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_PARTIDOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_REVISION_FISICA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_REVISION_FISICA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_REVISION_FISICA_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TELEFONOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TELEFONOS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TELEFONOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ASISTENCIA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ASISTENCIA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ASISTENCIA_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADISTICA_EQUIPO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADISTICA_EQUIPO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ESTADISTICA_EQUIPO_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADISTICA_JUGADOR_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADISTICA_JUGADOR_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ESTADISTICA_JUGADOR_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_LESIONES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_LESIONES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_LESIONES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TARJETAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TARJETAS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TARJETAS_TB_INSERT_TRG;
/
