ALTER TABLE FIDE_ESTADOS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_TIPOTARJETAS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_CANTONES_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_CARGOS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_CATEGORIAS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_CATEGORIA_INVENTARIO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_DISTRITOS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_ESPECIALIDADES_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_POSICIONES_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_PROVINCIAS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_TEMPORADAS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_TIPOLESION_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_TIPO_PARTIDOS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_ARTICULOS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_DIRECCION_EXACTA_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_MEDICOS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_EMPLEADOS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_JUGADORES_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_FACTURACION_INSCRIPCIONES_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_SEDES_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_JUGADOR_POSICIONES_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_PARTE_MEDICO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_PARTIDOS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_REVISION_FISICA_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_TELEFONOS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_CORREOS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_ASISTENCIA_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_ESTADISTICA_EQUIPO_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_ESTADISTICA_JUGADOR_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_LESIONES_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);

ALTER TABLE FIDE_TARJETAS_TB ADD (
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100)
);
