-- Pegue este contenido dentro de FIDE_PROYECTOFINALACADEMIALEIVA_PCK,
-- antes del END final del PACKAGE BODY. Todas devuelven un arreglo JSON en CLOB.

FUNCTION FIDE_JUGADORES_TB_VALIDAR_EDAD_CATEGORIA_FN(P_FECHA_NACIMIENTO DATE, P_ID_CATEGORIA NUMBER) RETURN NUMBER IS
    V_NOMBRE_CATEGORIA FIDE_CATEGORIAS_TB.NOMBRE_CATEGORIA%TYPE;
    V_EDAD NUMBER;
    V_EDAD_MINIMA NUMBER;
    V_EDAD_MAXIMA NUMBER;
BEGIN
    SELECT UPPER(NOMBRE_CATEGORIA) INTO V_NOMBRE_CATEGORIA
    FROM FIDE_CATEGORIAS_TB
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;

    V_EDAD := TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE), P_FECHA_NACIMIENTO) / 12);
    IF V_NOMBRE_CATEGORIA = 'TERCERA DIVISION' THEN
        RETURN CASE WHEN V_EDAD >= 18 THEN 1 ELSE 0 END;
    END IF;

    IF NOT REGEXP_LIKE(V_NOMBRE_CATEGORIA, '^U-[0-9]+$') THEN
        RETURN 0;
    END IF;

    V_EDAD_MAXIMA := TO_NUMBER(REGEXP_SUBSTR(V_NOMBRE_CATEGORIA, '[0-9]+'));
    V_EDAD_MINIMA := CASE
        WHEN V_EDAD_MAXIMA = 5 THEN 0
        WHEN V_EDAD_MAXIMA = 20 THEN 18
        ELSE V_EDAD_MAXIMA - 1
    END;

    RETURN CASE WHEN V_EDAD BETWEEN V_EDAD_MINIMA AND V_EDAD_MAXIMA THEN 1 ELSE 0 END;
END FIDE_JUGADORES_TB_VALIDAR_EDAD_CATEGORIA_FN;

FUNCTION FIDE_CONSULTAS_TEMPORADAS_LISTAR_FN RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT('ID_TEMPORADA' VALUE ID_TEMPORADA, 'TIPO_TEMPORADA' VALUE TIPO_TEMPORADA, 'ANIO' VALUE ANIO) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM FIDE_TEMPORADAS_V;
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_TEMPORADAS_LISTAR_FN;

FUNCTION FIDE_CONSULTAS_CATEGORIAS_LISTAR_FN RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT('ID_CATEGORIA' VALUE ID_CATEGORIA, 'NOMBRE_CATEGORIA' VALUE NOMBRE_CATEGORIA) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM FIDE_CATEGORIAS_V WHERE ID_ESTADO = 1;
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_CATEGORIAS_LISTAR_FN;

FUNCTION FIDE_CONSULTAS_POSICIONES_LISTAR_FN RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT('ID_POSICION' VALUE ID_POSICION, 'NOMBRE_POSICION' VALUE NOMBRE_POSICION) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM FIDE_POSICIONES_V WHERE ID_ESTADO = 1;
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_POSICIONES_LISTAR_FN;

FUNCTION FIDE_CONSULTAS_PARTIDOS_BUSCAR_FN(P_ANIO NUMBER, P_TEMPORADA NUMBER, P_RIVAL VARCHAR2, P_FECHA VARCHAR2, P_RESULTADO VARCHAR2) RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT(
        'ID_PARTIDO' VALUE ID_PARTIDO, 'FECHA' VALUE TO_CHAR(FECHA, 'YYYY-MM-DD'), 'RIVAL' VALUE RIVAL,
        'GOLES_FAVOR' VALUE GOLES_FAVOR, 'GOLES_CONTRA' VALUE GOLES_CONTRA, 'RESULTADO' VALUE RESULTADO,
        'TIPO_TEMPORADA' VALUE TIPO_TEMPORADA, 'TEMPORADA_ANIO' VALUE ANIO,
        'TOTAL_ASISTENCIA' VALUE TOTAL_ASISTENCIA) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM (
        SELECT P.*, T.TIPO_TEMPORADA, T.ANIO,
            CASE WHEN P.GOLES_FAVOR > P.GOLES_CONTRA THEN 'Victoria' WHEN P.GOLES_FAVOR < P.GOLES_CONTRA THEN 'Derrota' ELSE 'Empate' END AS RESULTADO,
            (SELECT COUNT(*) FROM FIDE_ASISTENCIA_TB A WHERE A.ID_PARTIDO = P.ID_PARTIDO AND A.ID_ESTADO IN (1, 4)) AS TOTAL_ASISTENCIA
        FROM FIDE_PARTIDOS_V P
        JOIN FIDE_TEMPORADAS_TB T ON T.ID_TEMPORADA = P.ID_TEMPORADA
        WHERE P.ID_ESTADO IN (1, 4)
          AND (P_ANIO IS NULL OR T.ANIO = P_ANIO)
          AND (P_TEMPORADA IS NULL OR P.ID_TEMPORADA = P_TEMPORADA)
          AND (P_RIVAL IS NULL OR UPPER(P.RIVAL) LIKE '%' || UPPER(P_RIVAL) || '%')
          AND (P_FECHA IS NULL OR TO_CHAR(P.FECHA, 'YYYY-MM-DD') = P_FECHA)
          AND (P_RESULTADO IS NULL OR LOWER(CASE WHEN P.GOLES_FAVOR > P.GOLES_CONTRA THEN 'Victoria' WHEN P.GOLES_FAVOR < P.GOLES_CONTRA THEN 'Derrota' ELSE 'Empate' END) = P_RESULTADO)
    );
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_PARTIDOS_BUSCAR_FN;

FUNCTION FIDE_CONSULTAS_JUGADORES_BUSCAR_FN(P_NOMBRE VARCHAR2, P_CATEGORIA NUMBER, P_CEDULA VARCHAR2, P_POSICION NUMBER) RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT(
        'ID_JUGADOR' VALUE ID_JUGADOR, 'NOMBRE' VALUE NOMBRE, 'APELLIDO_PATERNO' VALUE APELLIDO_PATERNO,
        'APELLIDO_MATERNO' VALUE APELLIDO_MATERNO, 'CEDULA' VALUE CEDULA, 'DORSAL' VALUE DORSAL,
        'NOMBRE_CATEGORIA' VALUE CATEGORIA, 'POSICIONES' VALUE POSICIONES,
        'PARTIDOS_JUGADOS' VALUE PARTIDOS_JUGADOS, 'LESIONES' VALUE LESIONES) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM (
        SELECT J.*, JP.POSICIONES,
            (SELECT COUNT(*) FROM FIDE_ASISTENCIA_TB A WHERE A.ID_JUGADOR = J.ID_JUGADOR AND A.ID_ESTADO IN (1, 4)) PARTIDOS_JUGADOS,
            (SELECT COUNT(*) FROM FIDE_LESIONES_V L JOIN FIDE_PARTE_MEDICO_TB PM ON PM.ID_PARTEMEDICO = L.ID_PARTEMEDICO WHERE PM.ID_JUGADOR = J.ID_JUGADOR AND L.ID_ESTADO = 1) LESIONES
        FROM FIDE_JUGADORES_V J LEFT JOIN FIDE_JUGADOR_POSICIONES_V JP ON JP.ID_JUGADOR = J.ID_JUGADOR
        WHERE J.ID_ESTADO = 1
          AND (P_NOMBRE IS NULL OR UPPER(J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO) LIKE '%' || UPPER(P_NOMBRE) || '%')
          AND (P_CATEGORIA IS NULL OR J.ID_CATEGORIA = P_CATEGORIA)
          AND (P_CEDULA IS NULL OR J.CEDULA LIKE '%' || P_CEDULA || '%')
          AND (P_POSICION IS NULL OR EXISTS (SELECT 1 FROM FIDE_JUGADOR_POSICIONES_TB X WHERE X.ID_JUGADOR = J.ID_JUGADOR AND X.ID_POSICION = P_POSICION AND X.ID_ESTADO = 1))
    );
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_JUGADORES_BUSCAR_FN;

FUNCTION FIDE_CONSULTAS_JUGADOR_RESUMEN_FN(P_JUGADOR NUMBER) RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT(
        'ID_JUGADOR' VALUE J.ID_JUGADOR, 'NOMBRE' VALUE J.NOMBRE, 'APELLIDO_PATERNO' VALUE J.APELLIDO_PATERNO, 'APELLIDO_MATERNO' VALUE J.APELLIDO_MATERNO,
        'CEDULA' VALUE J.CEDULA, 'DORSAL' VALUE J.DORSAL, 'FECHA_NACIMIENTO' VALUE TO_CHAR(J.FECHA_NACIMIENTO, 'YYYY-MM-DD'), 'NOMBRE_CATEGORIA' VALUE J.CATEGORIA,
        'POSICIONES' VALUE JP.POSICIONES, 'GOLES' VALUE NVL(SUM(E.GOLES),0), 'ASISTENCIAS' VALUE NVL(SUM(E.ASISTENCIAS),0), 'PARTIDOS_JUGADOS' VALUE COUNT(E.ID_PARTIDO),
        'PASES_TOTALES' VALUE NVL(SUM(E.PASES),0), 'PASES_EXITOSOS_TOTALES' VALUE NVL(SUM(E.PASES_EXITOSOS),0), 'PROMEDIO_PASES_EXITOSOS' VALUE NVL(ROUND(AVG(E.PASES_EXITOSOS),2),0),
        'REGATES_TOTALES' VALUE NVL(SUM(E.REGATES),0), 'PROMEDIO_REGATES_EXITOSOS' VALUE NVL(ROUND(AVG(E.REGATES_EXITOSOS),2),0), 'TIROS_TOTALES' VALUE NVL(SUM(E.TIROS),0),
        'PROMEDIO_TIROS_EXITOSOS' VALUE NVL(ROUND(AVG(E.TIROS_EXITOSOS),2),0), 'ENTRADAS_TOTALES' VALUE NVL(SUM(E.ENTRADAS),0), 'PROMEDIO_ENTRADAS_EXITOSAS' VALUE NVL(ROUND(AVG(E.ENTRADAS_EXITOSAS),2),0),
        'MINUTOS_TOTALES' VALUE NVL(SUM(E.MINUTOS_JUGADOS),0), 'PROMEDIO_MINUTOS' VALUE NVL(ROUND(AVG(E.MINUTOS_JUGADOS),2),0),
        'TARJETAS' VALUE (SELECT NVL(SUM(T.CANTIDAD_TARJETAS),0) FROM FIDE_TARJETAS_TB T WHERE T.ID_JUGADOR = J.ID_JUGADOR AND T.ID_ESTADO = 1),
        'TARJETAS_AMARILLAS' VALUE (SELECT NVL(SUM(T.CANTIDAD_TARJETAS),0) FROM FIDE_TARJETAS_TB T JOIN FIDE_TIPOTARJETAS_TB TT ON TT.ID_TIPOTARJETA=T.ID_TIPOTARJETA WHERE T.ID_JUGADOR=J.ID_JUGADOR AND T.ID_ESTADO=1 AND UPPER(TT.COLOR)='AMARILLA'),
        'TARJETAS_ROJAS' VALUE (SELECT NVL(SUM(T.CANTIDAD_TARJETAS),0) FROM FIDE_TARJETAS_TB T JOIN FIDE_TIPOTARJETAS_TB TT ON TT.ID_TIPOTARJETA=T.ID_TIPOTARJETA WHERE T.ID_JUGADOR=J.ID_JUGADOR AND T.ID_ESTADO=1 AND UPPER(TT.COLOR)='ROJA'),
        'LESIONES' VALUE (SELECT COUNT(*) FROM FIDE_LESIONES_V L JOIN FIDE_PARTE_MEDICO_TB PM ON PM.ID_PARTEMEDICO=L.ID_PARTEMEDICO WHERE PM.ID_JUGADOR=J.ID_JUGADOR AND L.ID_ESTADO=1),
        'MONTO_PAGADO' VALUE (SELECT NVL(SUM(F.MONTO),0) FROM FIDE_FACTURACION_INSCRIPCIONES_TB F WHERE F.ID_JUGADOR=J.ID_JUGADOR AND F.ID_ESTADO=8)) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM FIDE_JUGADORES_V J LEFT JOIN FIDE_JUGADOR_POSICIONES_V JP ON JP.ID_JUGADOR=J.ID_JUGADOR LEFT JOIN FIDE_ESTADISTICA_JUGADOR_V E ON E.ID_JUGADOR=J.ID_JUGADOR AND E.ID_ESTADO IN (1, 4)
    WHERE J.ID_JUGADOR=P_JUGADOR AND J.ID_ESTADO=1 GROUP BY J.ID_JUGADOR,J.NOMBRE,J.APELLIDO_PATERNO,J.APELLIDO_MATERNO,J.CEDULA,J.DORSAL,J.FECHA_NACIMIENTO,J.CATEGORIA,JP.POSICIONES;
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_JUGADOR_RESUMEN_FN;

FUNCTION FIDE_CONSULTAS_DASHBOARD_FN(P_TEMPORADA NUMBER, P_CATEGORIA NUMBER) RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT JSON_ARRAY(JSON_OBJECT(
        'TOTAL_JUGADORES' VALUE (SELECT COUNT(*) FROM FIDE_JUGADORES_TB J WHERE J.ID_ESTADO=1 AND (P_CATEGORIA IS NULL OR J.ID_CATEGORIA=P_CATEGORIA)),
        'TOTAL_PARTIDOS' VALUE (SELECT COUNT(*) FROM FIDE_PARTIDOS_TB P WHERE P.ID_ESTADO IN (1, 4) AND (P_TEMPORADA IS NULL OR P.ID_TEMPORADA=P_TEMPORADA) AND (P_CATEGORIA IS NULL OR P.ID_CATEGORIA=P_CATEGORIA)),
        'PARTIDOS_GANADOS' VALUE (SELECT COUNT(*) FROM FIDE_PARTIDOS_TB P WHERE P.ID_ESTADO IN (1, 4) AND P.GOLES_FAVOR>P.GOLES_CONTRA AND (P_TEMPORADA IS NULL OR P.ID_TEMPORADA=P_TEMPORADA) AND (P_CATEGORIA IS NULL OR P.ID_CATEGORIA=P_CATEGORIA)),
        'GOLES_FAVOR' VALUE (SELECT NVL(SUM(P.GOLES_FAVOR),0) FROM FIDE_PARTIDOS_TB P WHERE P.ID_ESTADO IN (1, 4) AND (P_TEMPORADA IS NULL OR P.ID_TEMPORADA=P_TEMPORADA) AND (P_CATEGORIA IS NULL OR P.ID_CATEGORIA=P_CATEGORIA)),
        'TOTAL_ASISTENCIAS' VALUE (SELECT COUNT(*) FROM FIDE_ASISTENCIA_TB A JOIN FIDE_PARTIDOS_TB P ON P.ID_PARTIDO=A.ID_PARTIDO WHERE A.ID_ESTADO IN (1, 4) AND P.ID_ESTADO IN (1, 4) AND (P_TEMPORADA IS NULL OR P.ID_TEMPORADA=P_TEMPORADA) AND (P_CATEGORIA IS NULL OR P.ID_CATEGORIA=P_CATEGORIA)),
        'TOTAL_LESIONES' VALUE (SELECT COUNT(*) FROM FIDE_LESIONES_TB L JOIN FIDE_PARTE_MEDICO_TB PM ON PM.ID_PARTEMEDICO=L.ID_PARTEMEDICO JOIN FIDE_JUGADORES_TB J ON J.ID_JUGADOR=PM.ID_JUGADOR WHERE L.ID_ESTADO=1 AND (P_CATEGORIA IS NULL OR J.ID_CATEGORIA=P_CATEGORIA)),
        'TOP_GOLEADOR_NOMBRE' VALUE (SELECT NOMBRE_COMPLETO FROM (SELECT J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS NOMBRE_COMPLETO, SUM(E.GOLES) GOLES FROM FIDE_ESTADISTICA_JUGADOR_TB E JOIN FIDE_JUGADORES_TB J ON J.ID_JUGADOR=E.ID_JUGADOR JOIN FIDE_PARTIDOS_TB P ON P.ID_PARTIDO=E.ID_PARTIDO WHERE E.ID_ESTADO IN (1, 4) AND (P_TEMPORADA IS NULL OR P.ID_TEMPORADA=P_TEMPORADA) AND (P_CATEGORIA IS NULL OR P.ID_CATEGORIA=P_CATEGORIA) GROUP BY J.NOMBRE,J.APELLIDO_PATERNO ORDER BY GOLES DESC) WHERE ROWNUM=1),
        'TOP_GOLEADOR_GOLES' VALUE (SELECT GOLES FROM (SELECT SUM(E.GOLES) GOLES FROM FIDE_ESTADISTICA_JUGADOR_TB E JOIN FIDE_PARTIDOS_TB P ON P.ID_PARTIDO=E.ID_PARTIDO WHERE E.ID_ESTADO IN (1, 4) AND (P_TEMPORADA IS NULL OR P.ID_TEMPORADA=P_TEMPORADA) AND (P_CATEGORIA IS NULL OR P.ID_CATEGORIA=P_CATEGORIA) GROUP BY E.ID_JUGADOR ORDER BY GOLES DESC) WHERE ROWNUM=1),
        'TOP_ASISTENTE_NOMBRE' VALUE (SELECT NOMBRE_COMPLETO FROM (SELECT J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS NOMBRE_COMPLETO, SUM(E.ASISTENCIAS) ASISTENCIAS FROM FIDE_ESTADISTICA_JUGADOR_TB E JOIN FIDE_JUGADORES_TB J ON J.ID_JUGADOR=E.ID_JUGADOR JOIN FIDE_PARTIDOS_TB P ON P.ID_PARTIDO=E.ID_PARTIDO WHERE E.ID_ESTADO IN (1, 4) AND (P_TEMPORADA IS NULL OR P.ID_TEMPORADA=P_TEMPORADA) AND (P_CATEGORIA IS NULL OR P.ID_CATEGORIA=P_CATEGORIA) GROUP BY J.NOMBRE,J.APELLIDO_PATERNO ORDER BY ASISTENCIAS DESC) WHERE ROWNUM=1),
        'TOP_ASISTENTE_ASISTENCIAS' VALUE (SELECT ASISTENCIAS FROM (SELECT SUM(E.ASISTENCIAS) ASISTENCIAS FROM FIDE_ESTADISTICA_JUGADOR_TB E JOIN FIDE_PARTIDOS_TB P ON P.ID_PARTIDO=E.ID_PARTIDO WHERE E.ID_ESTADO IN (1, 4) AND (P_TEMPORADA IS NULL OR P.ID_TEMPORADA=P_TEMPORADA) AND (P_CATEGORIA IS NULL OR P.ID_CATEGORIA=P_CATEGORIA) GROUP BY E.ID_JUGADOR ORDER BY ASISTENCIAS DESC) WHERE ROWNUM=1),
        'TOTAL_DISPONIBLES' VALUE (SELECT COUNT(*) FROM FIDE_JUGADORES_TB J WHERE J.ID_ESTADO=1 AND (P_CATEGORIA IS NULL OR J.ID_CATEGORIA=P_CATEGORIA) AND NOT EXISTS (SELECT 1 FROM FIDE_LESIONES_TB L JOIN FIDE_PARTE_MEDICO_TB PM ON PM.ID_PARTEMEDICO=L.ID_PARTEMEDICO WHERE PM.ID_JUGADOR=J.ID_JUGADOR AND L.ID_ESTADO=1))
    ) RETURNING CLOB) INTO V_RESULTADO FROM DUAL;
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_DASHBOARD_FN;

FUNCTION FIDE_CONSULTAS_JUGADORES_COMPARAR_FN(P_JUGADOR_1 NUMBER, P_JUGADOR_2 NUMBER, P_JUGADOR_3 NUMBER) RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT('ID_JUGADOR' VALUE ID_JUGADOR, 'NOMBRE' VALUE NOMBRE, 'APELLIDO_PATERNO' VALUE APELLIDO_PATERNO, 'APELLIDO_MATERNO' VALUE APELLIDO_MATERNO, 'PARTIDOS_JUGADOS' VALUE PARTIDOS_JUGADOS, 'GOLES' VALUE GOLES, 'ASISTENCIAS' VALUE ASISTENCIAS, 'PROMEDIO_PASES_EXITOSOS' VALUE PROMEDIO_PASES_EXITOSOS, 'PROMEDIO_ENTRADAS_EXITOSAS' VALUE PROMEDIO_ENTRADAS_EXITOSAS, 'PROMEDIO_MINUTOS' VALUE PROMEDIO_MINUTOS) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM JSON_TABLE(FIDE_CONSULTAS_JUGADOR_RESUMEN_FN(P_JUGADOR_1), '$[*]' COLUMNS (ID_JUGADOR NUMBER PATH '$.ID_JUGADOR', NOMBRE VARCHAR2(100) PATH '$.NOMBRE', APELLIDO_PATERNO VARCHAR2(100) PATH '$.APELLIDO_PATERNO', APELLIDO_MATERNO VARCHAR2(100) PATH '$.APELLIDO_MATERNO', PARTIDOS_JUGADOS NUMBER PATH '$.PARTIDOS_JUGADOS', GOLES NUMBER PATH '$.GOLES', ASISTENCIAS NUMBER PATH '$.ASISTENCIAS', PROMEDIO_PASES_EXITOSOS NUMBER PATH '$.PROMEDIO_PASES_EXITOSOS', PROMEDIO_ENTRADAS_EXITOSAS NUMBER PATH '$.PROMEDIO_ENTRADAS_EXITOSAS', PROMEDIO_MINUTOS NUMBER PATH '$.PROMEDIO_MINUTOS'));
    -- Se agregan los otros jugadores reutilizando el mismo resumen.
    V_RESULTADO := '[' || SUBSTR(V_RESULTADO, 2, LENGTH(V_RESULTADO)-2) || ',' || SUBSTR(FIDE_CONSULTAS_JUGADOR_RESUMEN_FN(P_JUGADOR_2), 2, LENGTH(FIDE_CONSULTAS_JUGADOR_RESUMEN_FN(P_JUGADOR_2))-2) || ',' || SUBSTR(FIDE_CONSULTAS_JUGADOR_RESUMEN_FN(P_JUGADOR_3), 2, LENGTH(FIDE_CONSULTAS_JUGADOR_RESUMEN_FN(P_JUGADOR_3))-2) || ']';
    RETURN REPLACE(REPLACE(V_RESULTADO, '[,', '['), ',]', ']');
END FIDE_CONSULTAS_JUGADORES_COMPARAR_FN;

FUNCTION FIDE_CONSULTAS_PARTIDO_DETALLE_FN(P_PARTIDO NUMBER) RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT(
        'ID_PARTIDO' VALUE P.ID_PARTIDO, 'NOMBRE_CATEGORIA' VALUE P.CATEGORIA, 'RIVAL' VALUE P.RIVAL, 'FECHA' VALUE TO_CHAR(P.FECHA,'YYYY-MM-DD'),
        'GOLES_FAVOR' VALUE P.GOLES_FAVOR, 'GOLES_CONTRA' VALUE P.GOLES_CONTRA, 'TIPO_TEMPORADA' VALUE T.TIPO_TEMPORADA, 'TEMPORADA_ANIO' VALUE T.ANIO,
        'RESULTADO' VALUE CASE WHEN P.GOLES_FAVOR>P.GOLES_CONTRA THEN 'Victoria' WHEN P.GOLES_FAVOR<P.GOLES_CONTRA THEN 'Derrota' ELSE 'Empate' END,
        'TIROS' VALUE NVL(E.TIROS,0), 'TIROS_PORTERIA' VALUE NVL(E.TIROS_PORTERIA,0), 'PASES_EXITOSOS' VALUE NVL(E.PASES_EXITOSOS,0), 'PASES_FALLIDOS' VALUE NVL(E.PASES_FALLIDOS,0), 'POSESION_BALON' VALUE NVL(E.POSESION_BALON,0),
        'TOTAL_ASISTENCIA' VALUE (SELECT COUNT(*) FROM FIDE_ASISTENCIA_TB A WHERE A.ID_PARTIDO=P.ID_PARTIDO AND A.ID_ESTADO IN (1, 4))) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM FIDE_PARTIDOS_V P JOIN FIDE_TEMPORADAS_TB T ON T.ID_TEMPORADA=P.ID_TEMPORADA LEFT JOIN FIDE_ESTADISTICA_EQUIPO_TB E ON E.ID_PARTIDO=P.ID_PARTIDO AND E.ID_ESTADO IN (1, 4)
    WHERE P.ID_PARTIDO=P_PARTIDO;
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_PARTIDO_DETALLE_FN;

FUNCTION FIDE_CONSULTAS_PARTIDO_JUGADORES_FN(P_PARTIDO NUMBER) RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT('ID_JUGADOR' VALUE J.ID_JUGADOR, 'ID_PARTIDO' VALUE P_PARTIDO,
        'NOMBRE_COMPLETO' VALUE J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO, 'POSICIONES' VALUE JP.POSICIONES,
        'MINUTOS_JUGADOS' VALUE NVL(E.MINUTOS_JUGADOS,0), 'GOLES' VALUE NVL(E.GOLES,0), 'ASISTENCIAS' VALUE NVL(E.ASISTENCIAS,0), 'PASES_EXITOSOS' VALUE NVL(E.PASES_EXITOSOS,0), 'ENTRADAS_EXITOSAS' VALUE NVL(E.ENTRADAS_EXITOSAS,0)) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM FIDE_ESTADISTICA_JUGADOR_TB E JOIN FIDE_JUGADORES_TB J ON J.ID_JUGADOR=E.ID_JUGADOR LEFT JOIN FIDE_JUGADOR_POSICIONES_V JP ON JP.ID_JUGADOR=J.ID_JUGADOR
    WHERE E.ID_PARTIDO=P_PARTIDO AND E.ID_ESTADO IN (1, 4);
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_PARTIDO_JUGADORES_FN;

FUNCTION FIDE_CONSULTAS_JUGADOR_PARTIDO_FN(P_JUGADOR NUMBER, P_PARTIDO NUMBER) RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT('ID_JUGADOR' VALUE E.ID_JUGADOR, 'ID_PARTIDO' VALUE E.ID_PARTIDO,
        'NOMBRE_COMPLETO' VALUE J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO,
        'NOMBRE_CATEGORIA' VALUE C.NOMBRE_CATEGORIA, 'RIVAL' VALUE P.RIVAL, 'FECHA' VALUE TO_CHAR(P.FECHA, 'YYYY-MM-DD'),
        'RESULTADO' VALUE CASE WHEN P.GOLES_FAVOR > P.GOLES_CONTRA THEN 'Victoria' WHEN P.GOLES_FAVOR < P.GOLES_CONTRA THEN 'Derrota' ELSE 'Empate' END,
        'PASES' VALUE E.PASES, 'PASES_EXITOSOS' VALUE E.PASES_EXITOSOS,
        'REGATES' VALUE E.REGATES, 'REGATES_EXITOSOS' VALUE E.REGATES_EXITOSOS, 'TIROS' VALUE E.TIROS, 'TIROS_EXITOSOS' VALUE E.TIROS_EXITOSOS,
        'ENTRADAS' VALUE E.ENTRADAS, 'ENTRADAS_EXITOSAS' VALUE E.ENTRADAS_EXITOSAS, 'MINUTOS_JUGADOS' VALUE E.MINUTOS_JUGADOS, 'GOLES' VALUE E.GOLES, 'ASISTENCIAS' VALUE E.ASISTENCIAS) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM FIDE_ESTADISTICA_JUGADOR_TB E
    JOIN FIDE_JUGADORES_TB J ON J.ID_JUGADOR = E.ID_JUGADOR
    JOIN FIDE_PARTIDOS_TB P ON P.ID_PARTIDO = E.ID_PARTIDO
    JOIN FIDE_CATEGORIAS_TB C ON C.ID_CATEGORIA = P.ID_CATEGORIA
    WHERE E.ID_JUGADOR=P_JUGADOR AND E.ID_PARTIDO=P_PARTIDO AND E.ID_ESTADO IN (1, 4);
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_JUGADOR_PARTIDO_FN;

FUNCTION FIDE_CONSULTAS_DISPONIBILIDAD_FN(P_CATEGORIA NUMBER) RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT('ID_JUGADOR' VALUE J.ID_JUGADOR, 'NOMBRE_COMPLETO' VALUE J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO,
        'NOMBRE_CATEGORIA' VALUE J.CATEGORIA, 'LESIONES' VALUE (SELECT COUNT(*) FROM FIDE_LESIONES_V L JOIN FIDE_PARTE_MEDICO_TB PM ON PM.ID_PARTEMEDICO=L.ID_PARTEMEDICO WHERE PM.ID_JUGADOR=J.ID_JUGADOR AND L.ID_ESTADO=1),
        'TARJETAS_AMARILLAS' VALUE 0, 'TARJETAS_ROJAS' VALUE 0, 'ESTADO' VALUE J.ESTADO) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM FIDE_JUGADORES_V J WHERE J.ID_ESTADO=1 AND (P_CATEGORIA IS NULL OR J.ID_CATEGORIA=P_CATEGORIA);
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_DISPONIBILIDAD_FN;

FUNCTION FIDE_CONSULTAS_JUGADOR_LESIONES_FN(P_JUGADOR NUMBER) RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT('ID_LESION' VALUE L.ID_LESION, 'NOMBRE_TIPO_LESION' VALUE L.TIPO_LESION, 'DESCRIPCION' VALUE L.DESCRIPCION,
        'FECHA_PARTE_MEDICO' VALUE TO_CHAR(PM.FECHA,'YYYY-MM-DD'), 'FECHA_RECUPERACION' VALUE TO_CHAR(L.FECHA_RECUPERACION,'YYYY-MM-DD'), 'MEDICO' VALUE M.NOMBRE || ' ' || M.APELLIDO_PATERNO) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM FIDE_LESIONES_V L
    JOIN FIDE_PARTE_MEDICO_TB PM ON PM.ID_PARTEMEDICO=L.ID_PARTEMEDICO
    JOIN FIDE_MEDICOS_TB M ON M.ID_MEDICO=PM.ID_MEDICO
    WHERE PM.ID_JUGADOR=P_JUGADOR AND L.ID_ESTADO=1;
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_JUGADOR_LESIONES_FN;

FUNCTION FIDE_CONSULTAS_JUGADOR_PARTIDOS_FN(P_JUGADOR NUMBER) RETURN CLOB IS V_RESULTADO CLOB;
BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT('ID_PARTIDO' VALUE P.ID_PARTIDO, 'FECHA' VALUE TO_CHAR(P.FECHA,'YYYY-MM-DD'), 'RIVAL' VALUE P.RIVAL,
        'GOLES_FAVOR' VALUE P.GOLES_FAVOR, 'GOLES_CONTRA' VALUE P.GOLES_CONTRA, 'RESULTADO' VALUE CASE WHEN P.GOLES_FAVOR>P.GOLES_CONTRA THEN 'Victoria' WHEN P.GOLES_FAVOR<P.GOLES_CONTRA THEN 'Derrota' ELSE 'Empate' END,
        'MINUTOS_JUGADOS' VALUE E.MINUTOS_JUGADOS, 'GOLES' VALUE E.GOLES, 'ASISTENCIAS' VALUE E.ASISTENCIAS) RETURNING CLOB), TO_CLOB('[]')) INTO V_RESULTADO
    FROM FIDE_ESTADISTICA_JUGADOR_TB E JOIN FIDE_PARTIDOS_TB P ON P.ID_PARTIDO=E.ID_PARTIDO WHERE E.ID_JUGADOR=P_JUGADOR AND E.ID_ESTADO IN (1, 4) AND P.ID_ESTADO IN (1, 4);
    RETURN V_RESULTADO;
END FIDE_CONSULTAS_JUGADOR_PARTIDOS_FN;
