

CREATE TABLE FIDE_ESTADOS_TB (
    ID_ESTADO NUMBER,
    NOMBRE_ESTADO VARCHAR2(100) CONSTRAINT FIDE_ESTADOS_TB_NOMBRE_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_ESTADOS_TB_ID_ESTADO_PK
        PRIMARY KEY (ID_ESTADO),
    CONSTRAINT FIDE_ESTADOS_TB_NOMBRE_ESTADO_UK
        UNIQUE (NOMBRE_ESTADO)
);

CREATE TABLE FIDE_TIPOTARJETAS_TB (
    ID_TIPOTARJETA NUMBER,
    COLOR VARCHAR2(100) CONSTRAINT FIDE_TIPOTARJETAS_TB_COLOR_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_TIPOTARJETAS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_TIPOTARJETAS_TB_ID_TIPOTARJETA_PK
        PRIMARY KEY (ID_TIPOTARJETA),
    CONSTRAINT FIDE_TIPOTARJETAS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_TIPOTARJETAS_TB_COLOR_UK
        UNIQUE (COLOR)
);

CREATE TABLE FIDE_CANTONES_TB (
    ID_CANTON NUMBER,
    NOMBRE_CANTON VARCHAR2(100),
    ID_ESTADO NUMBER CONSTRAINT FIDE_CANTONES_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_CANTONES_TB_ID_CANTON_PK
        PRIMARY KEY (ID_CANTON),
    CONSTRAINT FIDE_CANTONES_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_CARGOS_TB (
    ID_CARGO NUMBER,
    NOMBRE_CARGO VARCHAR2(100) CONSTRAINT FIDE_CARGOS_TB_NOMBRE_CARGO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_CARGOS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_CARGOS_TB_ID_CARGO_PK
        PRIMARY KEY (ID_CARGO),
    CONSTRAINT FIDE_CARGOS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_CARGOS_TB_NOMBRE_CARGO_UK
        UNIQUE (NOMBRE_CARGO)
);

CREATE TABLE FIDE_CATEGORIAS_TB (
    ID_CATEGORIA NUMBER,
    NOMBRE_CATEGORIA VARCHAR2(100) CONSTRAINT FIDE_CATEGORIAS_TB_NOMBRE_CATEGORIA_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_CATEGORIAS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_CATEGORIAS_TB_ID_CATEGORIA_PK
        PRIMARY KEY (ID_CATEGORIA),
    CONSTRAINT FIDE_CATEGORIAS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_CATEGORIAS_TB_NOMBRE_CATEGORIA_UK
        UNIQUE (NOMBRE_CATEGORIA)
);

CREATE TABLE FIDE_CATEGORIA_INVENTARIO_TB (
    ID_CATEGORIAINVENTARIO NUMBER,
    NOMBRE_CATEGORIA_INVENTARIO VARCHAR2(100) CONSTRAINT FIDE_CATEGORIA_INVENTARIO_TB_NOMBRE_CATEGORIA_INVENTARIO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_CATEGORIA_INVENTARIO_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_CATEGORIA_INVENTARIO_TB_ID_CATEGORIAINVENTARIO_PK
        PRIMARY KEY (ID_CATEGORIAINVENTARIO),
    CONSTRAINT FIDE_CATEGORIA_INVENTARIO_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_DISTRITOS_TB (
    ID_DISTRITO NUMBER,
    NOMBRE_DISTRITO VARCHAR2(100) CONSTRAINT FIDE_DISTRITOS_TB_NOMBRE_DISTRITO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_DISTRITOS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_DISTRITOS_TB_ID_DISTRITO_PK
        PRIMARY KEY (ID_DISTRITO),
    CONSTRAINT FIDE_DISTRITOS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_ESPECIALIDADES_TB (
    ID_ESPECIALIDAD NUMBER,
    NOMBRE_ESPECIALIDAD VARCHAR2(100) CONSTRAINT FIDE_ESPECIALIDADES_TB_NOMBRE_ESPECIALIDAD_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_ESPECIALIDADES_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_ESPECIALIDADES_TB_ID_ESPECIALIDAD_PK
        PRIMARY KEY (ID_ESPECIALIDAD),
    CONSTRAINT FIDE_ESPECIALIDADES_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_ESPECIALIDADES_TB_NOMBRE_ESPECIALIDAD_UK
        UNIQUE (NOMBRE_ESPECIALIDAD)
);

CREATE TABLE FIDE_POSICIONES_TB (
    ID_POSICION NUMBER,
    NOMBRE_POSICION VARCHAR2(100) CONSTRAINT FIDE_POSICIONES_TB_NOMBRE_POSICION_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_POSICIONES_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_POSICIONES_TB_ID_POSICION_PK
        PRIMARY KEY (ID_POSICION),
    CONSTRAINT FIDE_POSICIONES_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_POSICIONES_TB_NOMBRE_POSICION_UK
        UNIQUE (NOMBRE_POSICION)
);

CREATE TABLE FIDE_PROVINCIAS_TB (
    ID_PROVINCIA NUMBER ,
    NOMBRE_PROVINCIA VARCHAR2(100) CONSTRAINT FIDE_PROVINCIAS_TB_NOMBRE_PROVINCIA_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER  CONSTRAINT FIDE_PROVINCIAS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_PROVINCIAS_TB_ID_PROVINCIA_PK
        PRIMARY KEY (ID_PROVINCIA),
    CONSTRAINT FIDE_PROVINCIAS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
CREATE TABLE FIDE_TEMPORADAS_TB (
    ID_TEMPORADA NUMBER,
    TIPO_TEMPORADA VARCHAR2(100)  CONSTRAINT FIDE_TEMPORADAS_TB_TIPO_TEMPORADA_NOT_NULL NOT NULL,
    ANIO NUMBER(4) CONSTRAINT FIDE_TEMPORADAS_TB_ANIO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_TEMPORADAS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_TEMPORADAS_TB_ID_TEMPORADA_PK
        PRIMARY KEY (ID_TEMPORADA),
    CONSTRAINT FIDE_TEMPORADAS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_TIPOLESION_TB (
    ID_TIPOLESION NUMBER,
    NOMBRE_TIPO_LESION VARCHAR2(100) CONSTRAINT FIDE_TIPOLESION_TB_NOMBRE_TIPO_LESION_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_TIPOLESION_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_TIPOLESION_TB_ID_TIPOLESION_PK
        PRIMARY KEY (ID_TIPOLESION),
    CONSTRAINT FIDE_TIPOLESION_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_TIPO_PARTIDOS_TB (
    ID_TIPOPARTIDOS NUMBER ,
    TIPO_DE_PARTIDO VARCHAR2(100) CONSTRAINT FIDE_TIPO_PARTIDOS_TB_TIPO_DE_PARTIDO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_TIPO_PARTIDOS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_TIPO_PARTIDOS_TB_ID_TIPOPARTIDOS_PK
        PRIMARY KEY (ID_TIPOPARTIDOS),
    CONSTRAINT FIDE_TIPO_PARTIDOS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_TIPO_PARTIDOS_TB_TIPO_DE_PARTIDO_UK
        UNIQUE (TIPO_DE_PARTIDO)
);

CREATE TABLE FIDE_ARTICULOS_TB (
    ID_ARTICULO NUMBER ,
    ID_CATEGORIAINVENTARIO NUMBER CONSTRAINT FIDE_ARTICULOS_TB_ID_CATEGORIAINVENTARIO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_ARTICULOS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CANTIDAD NUMBER CONSTRAINT FIDE_ARTICULOS_TB_CANTIDAD_NOT_NULL NOT NULL,
    NOMBRE_ARTICULO VARCHAR2(100) CONSTRAINT FIDE_ARTICULOS_TB_NOMBRE_ARTICULO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_ARTICULOS_TB_ID_ARTICULO_PK
        PRIMARY KEY (ID_ARTICULO),
    CONSTRAINT FIDE_ARTICULOS_TB_ID_CATEGORIAINVENTARIO_FK
        FOREIGN KEY (ID_CATEGORIAINVENTARIO) REFERENCES FIDE_CATEGORIA_INVENTARIO_TB(ID_CATEGORIAINVENTARIO),
    CONSTRAINT FIDE_ARTICULOS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_ARTICULOS_TB_CANTIDAD_CK
        CHECK (CANTIDAD >= 0),
    CONSTRAINT FIDE_ARTICULOS_TB_CATEGORIA_INVENTARIO_NOMBRE_ARTICULO_UK
        UNIQUE (ID_CATEGORIAINVENTARIO, NOMBRE_ARTICULO)
);

CREATE TABLE FIDE_DIRECCION_EXACTA_TB (
    ID_DIRECCION_EXACTA NUMBER,
    OTRAS_SENIAS VARCHAR2(255),
    ID_DISTRITO NUMBER CONSTRAINT FIDE_DIRECCION_EXACTA_TB_ID_DISTRITO_NOT_NULL NOT NULL,
    ID_CANTON NUMBER CONSTRAINT FIDE_DIRECCION_EXACTA_TB_ID_CANTON_NOT_NULL NOT NULL,
    ID_PROVINCIA NUMBER CONSTRAINT FIDE_DIRECCION_EXACTA_TB_ID_PROVINCIA_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_DIRECCION_EXACTA_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_DIRECCION_EXACTA_TB_ID_DIRECCION_EXACTA_PK
        PRIMARY KEY (ID_DIRECCION_EXACTA),
    CONSTRAINT FIDE_DIRECCION_EXACTA_TB_ID_DISTRITO_FK
        FOREIGN KEY (ID_DISTRITO) REFERENCES FIDE_DISTRITOS_TB(ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCION_EXACTA_TB_ID_CANTON_FK
        FOREIGN KEY (ID_CANTON) REFERENCES FIDE_CANTONES_TB(ID_CANTON),
    CONSTRAINT FIDE_DIRECCION_EXACTA_TB_ID_PROVINCIA_FK
        FOREIGN KEY (ID_PROVINCIA) REFERENCES FIDE_PROVINCIAS_TB(ID_PROVINCIA),
    CONSTRAINT FIDE_DIRECCION_EXACTA_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_MEDICOS_TB (
    ID_MEDICO NUMBER,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_MEDICOS_TB_NOMBRE_NOT_NULL NOT NULL,
    APELLIDO_PATERNO VARCHAR2(100) CONSTRAINT FIDE_MEDICOS_TB_APELLIDO_PATERNO_NOT_NULL NOT NULL,
    APELLIDO_MATERNO VARCHAR2(100),
    ID_ESPECIALIDAD NUMBER CONSTRAINT FIDE_MEDICOS_TB_ID_ESPECIALIDAD_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_MEDICOS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_MEDICOS_TB_ID_MEDICO_PK
        PRIMARY KEY (ID_MEDICO),
    CONSTRAINT FIDE_MEDICOS_TB_ID_ESPECIALIDAD_FK
        FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES FIDE_ESPECIALIDADES_TB(ID_ESPECIALIDAD),
    CONSTRAINT FIDE_MEDICOS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_EMPLEADOS_TB (
    ID_EMPLEADO NUMBER,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_EMPLEADOS_TB_NOMBRE_NOT_NULL NOT NULL,
    APELLIDO_PATERNO VARCHAR2(100) CONSTRAINT FIDE_EMPLEADOS_TB_APELLIDO_PATERNO_NOT_NULL NOT NULL,
    APELLIDO_MATERNO VARCHAR2(100),
    EDAD NUMBER CONSTRAINT FIDE_EMPLEADOS_TB_EDAD_NOT_NULL NOT NULL,
    NOMBRE_DE_USUARIO VARCHAR2(100) CONSTRAINT FIDE_EMPLEADOS_TB_NOMBRE_DE_USUARIO_NOT_NULL NOT NULL,
    CONTRASENIA VARCHAR2(100)  CONSTRAINT FIDE_EMPLEADOS_TB_CONTRASENIA_NOT_NULL NOT NULL,
    ID_CARGO NUMBER  CONSTRAINT FIDE_EMPLEADOS_TB_ID_CARGO_NOT_NULL NOT NULL ,
    ID_DIRECCION_EXACTA NUMBER CONSTRAINT FIDE_EMPLEADOS_TB_ID_DIRECCION_EXACTA_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_EMPLEADOS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_EMPLEADOS_TB_ID_EMPLEADO_PK
        PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT FIDE_EMPLEADOS_TB_ID_CARGO_FK
        FOREIGN KEY (ID_CARGO) REFERENCES FIDE_CARGOS_TB(ID_CARGO),
    CONSTRAINT FIDE_EMPLEADOS_TB_ID_DIRECCION_EXACTA_FK
        FOREIGN KEY (ID_DIRECCION_EXACTA) REFERENCES FIDE_DIRECCION_EXACTA_TB(ID_DIRECCION_EXACTA),
    CONSTRAINT FIDE_EMPLEADOS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_JUGADORES_TB (
    ID_JUGADOR NUMBER,
    CEDULA VARCHAR2(50) CONSTRAINT FIDE_JUGADORES_TB_CEDULA_NOT_NULL NOT NULL,
    ID_CATEGORIA NUMBER  CONSTRAINT FIDE_JUGADORES_TB_ID_CATEGORIA_NOT_NULL NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_JUGADORES_TB_NOMBRE_NOT_NULL NOT NULL,
    APELLIDO_MATERNO VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100) CONSTRAINT FIDE_JUGADORES_TB_APELLIDO_PATERNO_NOT_NULL NOT NULL,
    DORSAL NUMBER,
    FECHA_NACIMIENTO DATE CONSTRAINT FIDE_JUGADORES_TB_FECHA_NACIMIENTO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_JUGADORES_TB_ID_ESTADO_NOT_NULL NOT NULL,
    ID_DIRECCION_EXACTA NUMBER CONSTRAINT FIDE_JUGADORES_TB_ID_DIRECCION_EXACTA_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_JUGADORES_TB_ID_JUGADOR_PK
        PRIMARY KEY (ID_JUGADOR),
    CONSTRAINT FIDE_JUGADORES_TB_CEDULA_UK
        UNIQUE (CEDULA),
    CONSTRAINT FIDE_JUGADORES_TB_ID_CATEGORIA_FK
        FOREIGN KEY (ID_CATEGORIA) REFERENCES FIDE_CATEGORIAS_TB(ID_CATEGORIA),
    CONSTRAINT FIDE_JUGADORES_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_JUGADORES_TB_ID_DIRECCION_EXACTA_FK
        FOREIGN KEY (ID_DIRECCION_EXACTA) REFERENCES FIDE_DIRECCION_EXACTA_TB(ID_DIRECCION_EXACTA),
    CONSTRAINT FIDE_JUGADORES_TB_DORSAL_CK
        CHECK (DORSAL BETWEEN 1 AND 99),
    CONSTRAINT FIDE_JUGADORES_TB_ID_CATEGORIA_DORSAL_UK
        UNIQUE (ID_CATEGORIA,DORSAL)
);

CREATE TABLE FIDE_FACTURACION_INSCRIPCIONES_TB (
    ID_FACTURACION_INSCRIPCION NUMBER,
    ID_JUGADOR NUMBER CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_ID_JUGADOR_NOT_NULL NOT NULL,
    MES NUMBER CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_MES_NOT_NULL NOT NULL,
    ANIO NUMBER(4) CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_ANIO_NOT_NULL NOT NULL,
    MONTO NUMBER(10,2) CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_MONTO_NOT_NULL NOT NULL,
    FECHA_PAGO DATE,
    ID_ESTADO NUMBER CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_ID_ESTADO_NOT_NULL NOT NULL,
    OBSERVACIONES VARCHAR2(255),
    CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_ID_FACTURACION_INSCRIPCION_PK
        PRIMARY KEY (ID_FACTURACION_INSCRIPCION),
    CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR)
        REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_MES_CK
        CHECK (MES BETWEEN 1 AND 12),
    CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_ANIO_CK
        CHECK (ANIO >= 2000),
    CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_MONTO_CK
        CHECK (MONTO >= 0),
    CONSTRAINT FIDE_FACTURACION_INSCRIPCIONES_TB_ID_JUGADOR_MES_ANIO_UK
        UNIQUE (ID_JUGADOR, MES, ANIO)
);

CREATE TABLE FIDE_SEDES_TB (
    ID_SEDE NUMBER ,
    NOMBRE_SEDE VARCHAR2(100) CONSTRAINT FIDE_SEDES_TB_NOMBRE_SEDE_NOT_NULL NOT NULL,
    ID_DIRECCION_EXACTA NUMBER CONSTRAINT FIDE_SEDES_TB_ID_DIRECCION_EXACTA_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_SEDES_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_SEDES_TB_ID_SEDE_PK
        PRIMARY KEY (ID_SEDE),
    CONSTRAINT FIDE_SEDES_TB_ID_DIRECCION_EXACTA_FK
        FOREIGN KEY (ID_DIRECCION_EXACTA) REFERENCES FIDE_DIRECCION_EXACTA_TB(ID_DIRECCION_EXACTA),
    CONSTRAINT FIDE_SEDES_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_JUGADOR_POSICIONES_TB (
    ID_JUGADOR NUMBER,
    ID_POSICION NUMBER,
    ID_ESTADO NUMBER CONSTRAINT FIDE_JUGADOR_POSICIONES_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_JUGADOR_POSICIONES_TB_ID_JUGADOR_ID_POSICION_PK
        PRIMARY KEY (ID_JUGADOR, ID_POSICION),
    CONSTRAINT FIDE_JUGADOR_POSICIONES_TB_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT FIDE_JUGADOR_POSICIONES_TB_ID_POSICION_FK
        FOREIGN KEY (ID_POSICION) REFERENCES FIDE_POSICIONES_TB(ID_POSICION),
    CONSTRAINT FIDE_JUGADOR_POSICIONES_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_PARTE_MEDICO_TB (
    ID_PARTEMEDICO NUMBER,
    ID_JUGADOR NUMBER CONSTRAINT FIDE_PARTE_MEDICO_TB_ID_JUGADOR_NOT_NULL NOT NULL,
    OBSERVACIONES VARCHAR2(255),
    FECHA DATE CONSTRAINT FIDE_PARTE_MEDICO_TB_FECHA_NOT_NULL NOT NULL,
    ID_MEDICO NUMBER CONSTRAINT FIDE_PARTE_MEDICO_TB_ID_MEDICO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_PARTE_MEDICO_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_PARTE_MEDICO_TB_ID_PARTEMEDICO_PK
        PRIMARY KEY (ID_PARTEMEDICO),
    CONSTRAINT FIDE_PARTE_MEDICO_TB_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT FIDE_PARTE_MEDICO_TB_ID_MEDICO_FK
        FOREIGN KEY (ID_MEDICO) REFERENCES FIDE_MEDICOS_TB(ID_MEDICO),
    CONSTRAINT FIDE_PARTE_MEDICO_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_PARTIDOS_TB (
    ID_PARTIDO NUMBER ,
    ID_CATEGORIA NUMBER CONSTRAINT FIDE_PARTIDOS_TB_ID_CATEGORIA_NOT_NULL NOT NULL,
    ID_TIPOPARTIDOS NUMBER CONSTRAINT FIDE_PARTIDOS_TB_ID_TIPOPARTIDOS_NOT_NULL NOT NULL,
    ID_TEMPORADA NUMBER CONSTRAINT FIDE_PARTIDOS_TB_ID_TEMPORADA_NOT_NULL NOT NULL,
    FECHA DATE CONSTRAINT FIDE_PARTIDOS_TB_FECHA_NOT_NULL NOT NULL,
    RIVAL VARCHAR2(100) CONSTRAINT FIDE_PARTIDOS_TB_RIVAL_NOT_NULL NOT NULL,
    GOLES_FAVOR NUMBER,
    GOLES_CONTRA NUMBER,
    ID_SEDE NUMBER CONSTRAINT FIDE_PARTIDOS_TB_ID_SEDE_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_PARTIDOS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_PARTIDOS_TB_ID_PARTIDO_PK
        PRIMARY KEY (ID_PARTIDO),
    CONSTRAINT FIDE_PARTIDOS_TB_ID_CATEGORIA_FK
        FOREIGN KEY (ID_CATEGORIA) REFERENCES FIDE_CATEGORIAS_TB(ID_CATEGORIA),
    CONSTRAINT FIDE_PARTIDOS_TB_ID_TIPOPARTIDOS_FK
        FOREIGN KEY (ID_TIPOPARTIDOS) REFERENCES FIDE_TIPO_PARTIDOS_TB(ID_TIPOPARTIDOS),
    CONSTRAINT FIDE_PARTIDOS_TB_ID_TEMPORADA_FK
        FOREIGN KEY (ID_TEMPORADA) REFERENCES FIDE_TEMPORADAS_TB(ID_TEMPORADA),
    CONSTRAINT FIDE_PARTIDOS_TB_ID_SEDE_FK
        FOREIGN KEY (ID_SEDE) REFERENCES FIDE_SEDES_TB(ID_SEDE),
    CONSTRAINT FIDE_PARTIDOS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_PARTIDOS_TS_GOLES_FAVOR_CK
        CHECK(GOLES_FAVOR >= 0),
    CONSTRAINT FIDE_PARTIDOS_TB_GOLES_CONTRA_CK
        CHECK(GOLES_CONTRA >= 0)
);

CREATE TABLE FIDE_REVISION_FISICA_TB (
    ID_REVISION NUMBER ,
    ID_JUGADOR NUMBER CONSTRAINT FIDE_REVISION_FISICA_TB_ID_JUGADOR_NOT_NULL NOT NULL,
    PESO NUMBER(8,2) CONSTRAINT FIDE_REVISION_FISICA_TB_PESO_NOT_NULL NOT NULL,
    IMC NUMBER(8,2) CONSTRAINT FIDE_REVISION_FISICA_TB_IMC_NOT_NULL NOT NULL,
    ALTURA NUMBER(8,2) CONSTRAINT FIDE_REVISION_FISICA_TB_ALTURA_NOT_NULL NOT NULL,
    FECHA_REVISION DATE CONSTRAINT FIDE_REVISION_FISICA_TB_FECHA_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER  CONSTRAINT FIDE_REVISION_FISICA_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_REVISION_FISICA_TB_ID_REVISION_PK
        PRIMARY KEY (ID_REVISION),
    CONSTRAINT FIDE_REVISION_FISICA_TB_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT FIDE_REVISION_FISICA_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_REVISION_FISICA_TB_PESO_CK
        CHECK (PESO > 0),
    CONSTRAINT FIDE_REVISION_FISICA_TB_ALTURA_CK
        CHECK (ALTURA > 0),
    CONSTRAINT FIDE_REVISION_FISICA_TB_IMC_CK
        CHECK (IMC > 0)
            
);

CREATE TABLE FIDE_TELEFONOS_TB (
    ID_TELEFONO NUMBER,
    NUMERO_TELEFONO VARCHAR2(20) CONSTRAINT FIDE_TELEFONOS_TB_NUMERO_TELEFONO_NOT_NULL NOT NULL,
    ID_EMPLEADO NUMBER CONSTRAINT FIDE_TELEFONOS_TB_ID_EMPLEADO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_TELEFONOS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_TELEFONOS_TB_ID_TELEFONO_PK
        PRIMARY KEY (ID_TELEFONO),
    CONSTRAINT FIDE_TELEFONOS_TB_ID_EMPLEADO_FK
        FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADOS_TB(ID_EMPLEADO),
    CONSTRAINT FIDE_TELEFONOS_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_TELEFONOS_TB_NUMERO_TELEFONO_UK
        UNIQUE (NUMERO_TELEFONO),
    CONSTRAINT FIDE_TELEFONOS_TB_NUMERO_TELEFONO_CK
        CHECK (LENGTH(NUMERO_TELEFONO) >= 8)
);

CREATE TABLE FIDE_ASISTENCIA_TB (
    ID_PARTIDO NUMBER,
    ID_JUGADOR NUMBER,
    ID_ESTADO NUMBER CONSTRAINT FIDE_ASISTENCIA_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_ASISTENCIA_TB_ID_PARTIDO_ID_JUGADOR_PK
        PRIMARY KEY (ID_PARTIDO, ID_JUGADOR),
    CONSTRAINT FIDE_ASISTENCIA_TB_ID_PARTIDO_FK
        FOREIGN KEY (ID_PARTIDO) REFERENCES FIDE_PARTIDOS_TB(ID_PARTIDO),
    CONSTRAINT FIDE_ASISTENCIA_TB_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT FIDE_ASISTENCIA_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_ESTADISTICA_EQUIPO_TB (
    ID_ESTADISTICA_EQUIPO NUMBER,
    TIROS NUMBER,
    TIROS_PORTERIA NUMBER,
    PASES_EXITOSOS NUMBER,
    PASES_FALLIDOS NUMBER,
    POSESION_BALON NUMBER(8,2),
    ID_PARTIDO NUMBER CONSTRAINT FIDE_ESTADISTICA_EQUIPO_TB_ID_PARTIDO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_ESTADISTICA_EQUIPO_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_ESTADISTICA_EQUIPO_TB_ID_ESTADISTICA_EQUIPO_PK
        PRIMARY KEY (ID_ESTADISTICA_EQUIPO),
    CONSTRAINT FIDE_ESTADISTICA_EQUIPO_TB_ID_PARTIDO_FK
        FOREIGN KEY (ID_PARTIDO) REFERENCES FIDE_PARTIDOS_TB(ID_PARTIDO),
    CONSTRAINT FIDE_ESTADISTICA_EQUIPO_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT FIDE_ESTADISTICA_EQUIPO_TB_POSESION_BALON_CK
        CHECK (POSESION_BALON BETWEEN 0 AND 100),
    CONSTRAINT FIDE_ESTADISTICA_EQUIPO_TB_TIROS_PORTERIA_CK
        CHECK (TIROS_PORTERIA >= 0),
    CONSTRAINT FIDE_ESTADISTICA_EQUIPO_TB_TIROS_CK
        CHECK (TIROS >= 0),
    CONSTRAINT FIDE_ESTADISTICA_EQUIPO_TB_ID_PARTIDO_UK
        UNIQUE (ID_PARTIDO)
    
);

CREATE TABLE FIDE_ESTADISTICA_JUGADOR_TB (
    ID_ESTADISTICA_JUGADOR NUMBER,
    ID_JUGADOR NUMBER CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_ID_JUGADOR_NOT_NULL NOT NULL,
    ID_PARTIDO NUMBER CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_ID_PARTIDO_NOT_NULL NOT NULL,
    PASES NUMBER,
    PASES_EXITOSOS NUMBER,
    REGATES NUMBER,
    REGATES_EXITOSOS NUMBER,
    TIROS NUMBER,
    TIROS_EXITOSOS NUMBER,
    ENTRADAS NUMBER,
    ENTRADAS_EXITOSAS NUMBER,
    MINUTOS_JUGADOS NUMBER,
    GOLES NUMBER,
    ASISTENCIAS NUMBER,
    ID_ESTADO NUMBER CONSTRAINT FIDE_ESTADISTICA_JUGADOR_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_ID_ESTADISTICA_JUGADOR_PK
        PRIMARY KEY (ID_ESTADISTICA_JUGADOR),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_ID_PARTIDO_FK
        FOREIGN KEY (ID_PARTIDO) REFERENCES FIDE_PARTIDOS_TB(ID_PARTIDO),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT EFIDE_ESTADISTICA_JUGADOR_TB_ID_JUGADOR_ID_PARTIDO_UK
        UNIQUE (ID_JUGADOR,ID_PARTIDO),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_PASES_CK
        CHECK (PASES >= 0),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_PASES_EXITOSOS_CK
        CHECK (PASES_EXITOSOS >= 0),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_REGATES_CK
        CHECK (REGATES >= 0),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_REGATES_EXITOSOS_CK
        CHECK (REGATES_EXITOSOS >= 0),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_TIROS_CK
        CHECK (TIROS >= 0),
    CONSTRAINT EFIDE_ESTADISTICA_JUGADOR_TB_TIROS_EXITOSOS_CK
        CHECK (TIROS_EXITOSOS >= 0),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_ENTRADAS_CK
        CHECK (ENTRADAS >= 0),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_ENTRADAS_EXITOSAS_CK
        CHECK (ENTRADAS_EXITOSAS >= 0),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_MINUTOS_JUGADOS_CK
        CHECK (MINUTOS_JUGADOS BETWEEN 0 AND 120),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_GOLES_CK
        CHECK (GOLES >= 0),
    CONSTRAINT FIDE_ESTADISTICA_JUGADOR_TB_ASISTENCIAS_CK
        CHECK (ASISTENCIAS >= 0)
        
);

CREATE TABLE FIDE_LESIONES_TB (
    ID_LESION NUMBER,
    DESCRIPCION VARCHAR2(255),
    FECHA_RECUPERACION DATE,
    ID_TIPOLESION NUMBER  CONSTRAINT FIDE_LESIONES_TB_ID_TIPOLESION_NOT_NULL NOT NULL,
    ID_PARTEMEDICO NUMBER CONSTRAINT FIDE_LESIONES_TB_ID_PARTEMEDICO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_LESIONES_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_LESIONES_TB_ID_LESION_PK
        PRIMARY KEY (ID_LESION),
    CONSTRAINT FIDE_LESIONES_TB_ID_TIPOLESION_FK
        FOREIGN KEY (ID_TIPOLESION) REFERENCES FIDE_TIPOLESION_TB(ID_TIPOLESION),
    CONSTRAINT FIDE_LESIONES_TB_ID_PARTEMEDICO_FK
        FOREIGN KEY (ID_PARTEMEDICO) REFERENCES FIDE_PARTE_MEDICO_TB(ID_PARTEMEDICO),
    CONSTRAINT FIDE_LESIONES_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_TARJETAS_TB (
    ID_PARTIDO NUMBER ,
    ID_JUGADOR NUMBER ,
    ID_TIPOTARJETA NUMBER,
    CANTIDAD_TARJETAS NUMBER CONSTRAINT FIDE_TARJETAS_TB_CANTIDAD_TARJETAS_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_TARJETAS_TB_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_TARJETAS_TB_ID_PARTIDO_ID_JUGADOR_ID_TIPOTARJETA_PK
        PRIMARY KEY (ID_PARTIDO, ID_JUGADOR, ID_TIPOTARJETA),
    CONSTRAINT FIDE_TARJETAS_TB_ID_PARTIDO_FK
        FOREIGN KEY (ID_PARTIDO) REFERENCES FIDE_PARTIDOS_TB(ID_PARTIDO),
    CONSTRAINT FIDE_TARJETAS_TB_ID_JUGADOR_FK
        FOREIGN KEY (ID_JUGADOR) REFERENCES FIDE_JUGADORES_TB(ID_JUGADOR),
    CONSTRAINT FIDE_TARJETAS_TBS_ID_TIPOTARJETA_FK
        FOREIGN KEY (ID_TIPOTARJETA) REFERENCES FIDE_TIPOTARJETAS_TB(ID_TIPOTARJETA),
    CONSTRAINT FIDE_TARJETAS_TB_CANTIDAD_TARJETAS_CK
        CHECK (CANTIDAD_TARJETAS BETWEEN 0 AND 2),
    CONSTRAINT FIDE_TARJETAS_TB_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
