CREATE OR REPLACE PROCEDURE FIDE_FACTURACION_INSCRIPCIONES_TB_GENERAR_MENSUALES_SP
IS
    V_ID_ESTADO_ACTIVO    NUMBER;
    V_ID_ESTADO_PENDIENTE NUMBER;
BEGIN
    -- IDs fijos del catálogo de estados: 1 = Activo, 9 = Pendiente de pago.
    V_ID_ESTADO_ACTIVO := 1;
    V_ID_ESTADO_PENDIENTE := 9;

    INSERT INTO FIDE_FACTURACION_INSCRIPCIONES_TB (
        ID_JUGADOR,
        MES,
        ANIO,
        MONTO,
        FECHA_PAGO,
        ID_ESTADO,
        OBSERVACIONES
    )
    SELECT
        J.ID_JUGADOR,
        EXTRACT(MONTH FROM SYSDATE),
        EXTRACT(YEAR FROM SYSDATE),
        10000,
        NULL,
        V_ID_ESTADO_PENDIENTE,
        'MENSUALIDAD CORRESPONDIENTE AL MES ACTUAL'
    FROM FIDE_JUGADORES_TB J
    WHERE J.ID_ESTADO = V_ID_ESTADO_ACTIVO
    AND NOT EXISTS (
        SELECT 1
        FROM FIDE_FACTURACION_INSCRIPCIONES_TB F
        WHERE F.ID_JUGADOR = J.ID_JUGADOR
        AND F.MES = EXTRACT(MONTH FROM SYSDATE)
        AND F.ANIO = EXTRACT(YEAR FROM SYSDATE)
    );

END FIDE_FACTURACION_INSCRIPCIONES_TB_GENERAR_MENSUALES_SP;
/

BEGIN
    SYS.DBMS_SCHEDULER.CREATE_JOB(
        JOB_NAME        => 'GENERAR_FACTURAS_MENSUALES',
        START_DATE      => SYSTIMESTAMP,
        JOB_TYPE        => 'PLSQL_BLOCK',
        REPEAT_INTERVAL => 'FREQ=MONTHLY;BYMONTHDAY=1;BYHOUR=0;BYMINUTE=0;BYSECOND=0',
        END_DATE        => NULL,
        JOB_CLASS       => 'DEFAULT_JOB_CLASS',
        JOB_ACTION      => 'BEGIN FIDE_FACTURACION_INSCRIPCIONES_TB_GENERAR_MENSUALES_SP(); END;',
        COMMENTS        => 'GENERA LAS FACTURAS DE LOS JUGADORES ACTIVOS EL PRIMER DÍA DE CADA MES',
        ENABLED         => TRUE
    );
END;
/
