CREATE OR REPLACE VIEW FIDE_ESTADOS_V AS
SELECT
    ID_ESTADO,
    NOMBRE_ESTADO
FROM FIDE_ESTADOS_TB;


CREATE OR REPLACE VIEW FIDE_TIPOTARJETAS_V AS
SELECT
    ID_TIPOTARJETA,
    COLOR,
    ID_ESTADO
FROM FIDE_TIPOTARJETAS_TB;


CREATE OR REPLACE VIEW FIDE_CANTONES_V AS
SELECT
    ID_CANTON,
    NOMBRE_CANTON,
    ID_ESTADO
FROM FIDE_CANTONES_TB;

/

CREATE OR REPLACE VIEW FIDE_CARGOS_V AS
SELECT
    ID_CARGO,
    NOMBRE_CARGO,
    ID_ESTADO
FROM FIDE_CARGOS_TB;

/

CREATE OR REPLACE VIEW FIDE_CATEGORIAS_V AS
SELECT
    ID_CATEGORIA,
    NOMBRE_CATEGORIA,
    ID_ESTADO
FROM FIDE_CATEGORIAS_TB;

/

CREATE OR REPLACE VIEW FIDE_CATEGORIA_INVENTARIO_V AS
SELECT
    ID_CATEGORIAINVENTARIO,
    NOMBRE_CATEGORIA_INVENTARIO,
    ID_ESTADO
FROM FIDE_CATEGORIA_INVENTARIO_TB;

/

CREATE OR REPLACE VIEW FIDE_DISTRITOS_V AS
SELECT
    ID_DISTRITO,
    NOMBRE_DISTRITO,
    ID_ESTADO
FROM FIDE_DISTRITOS_TB;

/


CREATE OR REPLACE VIEW FIDE_ESPECIALIDADES_V AS
SELECT
    ID_ESPECIALIDAD,
    NOMBRE_ESPECIALIDAD,
    ID_ESTADO
FROM FIDE_ESPECIALIDADES_TB;


/

CREATE OR REPLACE VIEW FIDE_POSICIONES_V AS
SELECT
    ID_POSICION,
    NOMBRE_POSICION,
    ID_ESTADO
FROM FIDE_POSICIONES_TB;

/

CREATE OR REPLACE VIEW FIDE_PROVINCIAS_V AS
SELECT
    ID_PROVINCIA,
    NOMBRE_PROVINCIA,
    ID_ESTADO
FROM FIDE_PROVINCIAS_TB;


/

CREATE OR REPLACE VIEW FIDE_TEMPORADAS_V AS
SELECT
    ID_TEMPORADA,
    TIPO_TEMPORADA,
    ANIO,
    ID_ESTADO
FROM FIDE_TEMPORADAS_TB;

/

CREATE OR REPLACE VIEW FIDE_TIPOLESION_V AS
SELECT
    ID_TIPOLESION,
    NOMBRE_TIPO_LESION,
    ID_ESTADO
FROM FIDE_TIPOLESION_TB;


/

CREATE OR REPLACE VIEW FIDE_TIPO_PARTIDOS_V AS
SELECT
    ID_TIPOPARTIDOS,
    TIPO_DE_PARTIDO,
    ID_ESTADO
FROM FIDE_TIPO_PARTIDOS_TB;

/

CREATE OR REPLACE VIEW FIDE_ARTICULOS_V AS
SELECT
    ID_ARTICULO,
    ID_CATEGORIAINVENTARIO,
    ID_ESTADO,
    CANTIDAD,
    NOMBRE_ARTICULO
FROM FIDE_ARTICULOS_TB;

/


CREATE OR REPLACE VIEW FIDE_DIRECCION_EXACTA_V AS
SELECT
    ID_DIRECCION_EXACTA,
    OTRAS_SENIAS,
    ID_DISTRITO,
    ID_CANTON,
    ID_PROVINCIA,
    ID_ESTADO
FROM FIDE_DIRECCION_EXACTA_TB;

/


CREATE OR REPLACE VIEW FIDE_MEDICOS_V AS
SELECT
    M.ID_MEDICO,
    M.NOMBRE,
    M.APELLIDO_PATERNO,
    M.APELLIDO_MATERNO,
    M.NOMBRE || ' ' || M.APELLIDO_PATERNO || ' ' || M.APELLIDO_MATERNO AS MEDICO_OPCION,
    M.ID_ESPECIALIDAD,
    ES.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD,
    M.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_MEDICOS_TB M
INNER JOIN FIDE_ESPECIALIDADES_TB ES
    ON M.ID_ESPECIALIDAD = ES.ID_ESPECIALIDAD
INNER JOIN FIDE_ESTADOS_TB E
    ON M.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_EMPLEADOS_V AS
SELECT
    EM.ID_EMPLEADO,
    EM.NOMBRE,
    EM.APELLIDO_PATERNO,
    EM.APELLIDO_MATERNO,
    EM.NOMBRE || ' ' || EM.APELLIDO_PATERNO || ' ' || EM.APELLIDO_MATERNO AS EMPLEADO_OPCION,
    EM.EDAD,
    EM.NOMBRE_DE_USUARIO,
    EM.CONTRASENIA,
    C.NOMBRE_CARGO AS CARGO,
    EM.ID_CARGO,
    EM.ID_DIRECCION_EXACTA,
    EM.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_EMPLEADOS_TB EM
INNER JOIN FIDE_CARGOS_TB C ON EM.ID_CARGO = C.ID_CARGO
INNER JOIN FIDE_DIRECCION_EXACTA_TB DE ON EM.ID_DIRECCION_EXACTA = DE.ID_DIRECCION_EXACTA
INNER JOIN FIDE_ESTADOS_TB E ON EM.ID_ESTADO = E.ID_ESTADO;

/



CREATE OR REPLACE VIEW FIDE_JUGADORES_V AS
SELECT
    J.ID_JUGADOR,
    J.CEDULA,
    C.NOMBRE_CATEGORIA AS CATEGORIA,
    J.ID_CATEGORIA,
    J.NOMBRE,
    J.APELLIDO_MATERNO,
    J.APELLIDO_PATERNO,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO || ' - Cedula: ' || J.CEDULA AS JUGADOR_OPCION,
    J.DORSAL,
    J.FECHA_NACIMIENTO,
    E.NOMBRE_ESTADO AS ESTADO,
    J.ID_ESTADO,
    J.ID_DIRECCION_EXACTA,
    DE.OTRAS_SENIAS AS DIRECCION_EXACTA
FROM FIDE_JUGADORES_TB J
INNER JOIN FIDE_CATEGORIAS_TB C ON J.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FIDE_ESTADOS_TB E ON J.ID_ESTADO = E.ID_ESTADO
INNER JOIN FIDE_DIRECCION_EXACTA_TB DE ON J.ID_DIRECCION_EXACTA = DE.ID_DIRECCION_EXACTA;

/



CREATE OR REPLACE VIEW FIDE_FACTURACION_INSCRIPCIONES_V AS
SELECT
    F.ID_FACTURACION_INSCRIPCION,
    F.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO AS JUGADOR,
    J.CEDULA,
    F.MES,
    CASE F.MES
        WHEN 1 THEN 'Enero'
        WHEN 2 THEN 'Febrero'
        WHEN 3 THEN 'Marzo'
        WHEN 4 THEN 'Abril'
        WHEN 5 THEN 'Mayo'
        WHEN 6 THEN 'Junio'
        WHEN 7 THEN 'Julio'
        WHEN 8 THEN 'Agosto'
        WHEN 9 THEN 'Septiembre'
        WHEN 10 THEN 'Octubre'
        WHEN 11 THEN 'Noviembre'
        WHEN 12 THEN 'Diciembre'
    END AS NOMBRE_MES,
    F.ANIO,
    F.MONTO,
    F.FECHA_PAGO,
    F.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO,
    F.OBSERVACIONES
FROM FIDE_FACTURACION_INSCRIPCIONES_TB F
INNER JOIN FIDE_JUGADORES_TB J ON F.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_ESTADOS_TB E ON F.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_SEDES_V AS
SELECT
    ID_SEDE,
    NOMBRE_SEDE,
    ID_DIRECCION_EXACTA,
    ID_ESTADO
FROM FIDE_SEDES_TB;

/


CREATE OR REPLACE VIEW FIDE_JUGADOR_POSICIONES_V AS
SELECT
    JP.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS JUGADOR,
    LISTAGG(P.NOMBRE_POSICION, ', ')
        WITHIN GROUP (ORDER BY P.NOMBRE_POSICION) AS POSICIONES
FROM FIDE_JUGADOR_POSICIONES_TB JP
INNER JOIN FIDE_JUGADORES_TB J
    ON JP.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_POSICIONES_TB P
    ON JP.ID_POSICION = P.ID_POSICION
GROUP BY
    JP.ID_JUGADOR,
    J.NOMBRE,
    J.APELLIDO_PATERNO;

/


CREATE OR REPLACE VIEW FIDE_PARTE_MEDICO_V AS
SELECT
    PM.ID_PARTEMEDICO,
    PM.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS JUGADOR,
    PM.OBSERVACIONES,
    PM.FECHA,
    PM.ID_MEDICO,
    M.NOMBRE || ' ' || M.APELLIDO_PATERNO AS MEDICO,
    PM.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_PARTE_MEDICO_TB PM
INNER JOIN FIDE_JUGADORES_TB J
    ON PM.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_MEDICOS_TB M
    ON PM.ID_MEDICO = M.ID_MEDICO
INNER JOIN FIDE_ESTADOS_TB E
    ON PM.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_PARTIDOS_V AS
SELECT
    P.ID_PARTIDO,
    P.ID_CATEGORIA,
    C.NOMBRE_CATEGORIA AS CATEGORIA,
    P.ID_TIPOPARTIDOS,
    TP.TIPO_DE_PARTIDO AS TIPO_PARTIDO,
    P.ID_TEMPORADA,
    T.TIPO_TEMPORADA || ' ' || T.ANIO AS TEMPORADA,
    P.FECHA,
    P.RIVAL,
    P.FECHA || ' - ' || P.RIVAL || ' - ' || T.TIPO_TEMPORADA || ' ' || T.ANIO AS PARTIDO_OPCION,
    P.GOLES_FAVOR,
    P.GOLES_CONTRA,
    P.ID_SEDE,
    S.NOMBRE_SEDE AS SEDE,
    P.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_PARTIDOS_TB P
INNER JOIN FIDE_CATEGORIAS_TB C
    ON P.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FIDE_TIPO_PARTIDOS_TB TP
    ON P.ID_TIPOPARTIDOS = TP.ID_TIPOPARTIDOS
INNER JOIN FIDE_TEMPORADAS_TB T
    ON P.ID_TEMPORADA = T.ID_TEMPORADA
INNER JOIN FIDE_SEDES_TB S
    ON P.ID_SEDE = S.ID_SEDE
INNER JOIN FIDE_ESTADOS_TB E
    ON P.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_REVISION_FISICA_V AS
SELECT
    RF.ID_REVISION,
    RF.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS JUGADOR,
    RF.PESO,
    RF.IMC,
    RF.ALTURA,
    RF.FECHA_REVISION,
    RF.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_REVISION_FISICA_TB RF
INNER JOIN FIDE_JUGADORES_TB J
    ON RF.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_ESTADOS_TB E
    ON RF.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_TELEFONOS_V AS
SELECT
    T.ID_TELEFONO,
    T.NUMERO_TELEFONO,
    T.ID_EMPLEADO,
    EM.NOMBRE || ' ' || EM.APELLIDO_PATERNO AS EMPLEADO,
    T.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_TELEFONOS_TB T
INNER JOIN FIDE_EMPLEADOS_TB EM ON T.ID_EMPLEADO = EM.ID_EMPLEADO
INNER JOIN FIDE_ESTADOS_TB E ON T.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_ASISTENCIA_V AS
SELECT
    A.ID_PARTIDO,
    P.FECHA || ' - ' || P.RIVAL || ' - ' || T.TIPO_TEMPORADA || ' ' || T.ANIO AS PARTIDO,
    A.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS JUGADOR,
    A.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_ASISTENCIA_TB A
INNER JOIN FIDE_PARTIDOS_TB P ON A.ID_PARTIDO = P.ID_PARTIDO
INNER JOIN FIDE_TEMPORADAS_TB T ON P.ID_TEMPORADA = T.ID_TEMPORADA
INNER JOIN FIDE_JUGADORES_TB J ON A.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_ESTADOS_TB E ON A.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_ESTADISTICA_EQUIPO_V AS
SELECT
    EE.ID_ESTADISTICA_EQUIPO,
    EE.TIROS,
    EE.TIROS_PORTERIA,
    EE.PASES_EXITOSOS,
    EE.PASES_FALLIDOS,
    EE.POSESION_BALON,
    EE.ID_PARTIDO,
    P.FECHA || ' - ' || P.RIVAL AS PARTIDO,
    EE.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_ESTADISTICA_EQUIPO_TB EE
INNER JOIN FIDE_PARTIDOS_TB P ON EE.ID_PARTIDO = P.ID_PARTIDO
INNER JOIN FIDE_ESTADOS_TB E ON EE.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_ESTADISTICA_JUGADOR_V AS
SELECT
    EJ.ID_ESTADISTICA_JUGADOR,
    EJ.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS JUGADOR,
    EJ.ID_PARTIDO,
    P.FECHA || ' - ' || P.RIVAL AS PARTIDO,
    EJ.PASES,
    EJ.PASES_EXITOSOS,
    EJ.REGATES,
    EJ.REGATES_EXITOSOS,
    EJ.TIROS,
    EJ.TIROS_EXITOSOS,
    EJ.ENTRADAS,
    EJ.ENTRADAS_EXITOSAS,
    EJ.MINUTOS_JUGADOS,
    EJ.GOLES,
    EJ.ASISTENCIAS,
    EJ.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_ESTADISTICA_JUGADOR_TB EJ
INNER JOIN FIDE_JUGADORES_TB J ON EJ.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_PARTIDOS_TB P ON EJ.ID_PARTIDO = P.ID_PARTIDO
INNER JOIN FIDE_ESTADOS_TB E ON EJ.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_LESIONES_V AS
SELECT
    L.ID_LESION,
    L.DESCRIPCION,
    L.FECHA_RECUPERACION,
    L.ID_TIPOLESION,
    TL.NOMBRE_TIPO_LESION AS TIPO_LESION,
    L.ID_PARTEMEDICO,
    PM.OBSERVACIONES AS PARTE_MEDICO,
    L.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_LESIONES_TB L
INNER JOIN FIDE_TIPOLESION_TB TL
    ON L.ID_TIPOLESION = TL.ID_TIPOLESION
INNER JOIN FIDE_PARTE_MEDICO_TB PM
    ON L.ID_PARTEMEDICO = PM.ID_PARTEMEDICO
INNER JOIN FIDE_ESTADOS_TB E
    ON L.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_TARJETAS_V AS
SELECT
    T.ID_PARTIDO,
    P.FECHA || ' - ' || P.RIVAL AS PARTIDO,
    T.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS JUGADOR,
    T.ID_TIPOTARJETA,
    TT.COLOR AS TIPO_TARJETA,
    T.CANTIDAD_TARJETAS,
    T.ID_ESTADO,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_TARJETAS_TB T
INNER JOIN FIDE_PARTIDOS_TB P ON T.ID_PARTIDO = P.ID_PARTIDO
INNER JOIN FIDE_JUGADORES_TB J ON T.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_TIPOTARJETAS_TB TT ON T.ID_TIPOTARJETA = TT.ID_TIPOTARJETA
INNER JOIN FIDE_ESTADOS_TB E ON T.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_DETALLE_JUGADORES_V AS
SELECT 
    J.ID_JUGADOR,
    J.NOMBRE,
    J.APELLIDO_PATERNO,
    J.APELLIDO_MATERNO,
    J.DORSAL,
    J.FECHA_NACIMIENTO,
    C.NOMBRE_CATEGORIA,
    E.NOMBRE_ESTADO
FROM FIDE_JUGADORES_TB J
INNER JOIN FIDE_CATEGORIAS_TB C
    ON J.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FIDE_ESTADOS_TB E
    ON J.ID_ESTADO = E.ID_ESTADO;

/


CREATE OR REPLACE VIEW FIDE_DETALLE_PARTIDOS_V AS
SELECT
    P.ID_PARTIDO,
    P.FECHA,
    P.RIVAL,
    P.GOLES_FAVOR,
    P.GOLES_CONTRA,
    C.NOMBRE_CATEGORIA,
    T.TIPO_DE_PARTIDO,
    TE.TIPO_TEMPORADA,
    TE.ANIO,
    S.NOMBRE_SEDE,
    E.NOMBRE_ESTADO
FROM FIDE_PARTIDOS_TB P
INNER JOIN FIDE_CATEGORIAS_TB C
    ON P.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FIDE_TIPO_PARTIDOS_TB T
    ON P.ID_TIPOPARTIDOS = T.ID_TIPOPARTIDOS
INNER JOIN FIDE_TEMPORADAS_TB TE
    ON P.ID_TEMPORADA = TE.ID_TEMPORADA
INNER JOIN FIDE_SEDES_TB S
    ON P.ID_SEDE = S.ID_SEDE
INNER JOIN FIDE_ESTADOS_TB E
    ON P.ID_ESTADO = E.ID_ESTADO;
   
   / 
    
CREATE OR REPLACE VIEW FIDE_DETALLE_ESTADISTICAS_JUGADOR_V AS
SELECT
    EJ.ID_ESTADISTICA_JUGADOR,
    J.ID_JUGADOR,
    J.NOMBRE,
    J.APELLIDO_PATERNO,
    J.APELLIDO_MATERNO,
    P.ID_PARTIDO,
    P.FECHA,
    P.RIVAL,
    EJ.MINUTOS_JUGADOS,
    EJ.GOLES,
    EJ.ASISTENCIAS,
    EJ.PASES,
    EJ.PASES_EXITOSOS,
    EJ.REGATES,
    EJ.REGATES_EXITOSOS,
    EJ.TIROS,
    EJ.TIROS_EXITOSOS,
    EJ.ENTRADAS,
    EJ.ENTRADAS_EXITOSAS,
    E.NOMBRE_ESTADO
FROM FIDE_ESTADISTICA_JUGADOR_TB EJ
INNER JOIN FIDE_JUGADORES_TB J
    ON EJ.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_PARTIDOS_TB P
    ON EJ.ID_PARTIDO = P.ID_PARTIDO
INNER JOIN FIDE_ESTADOS_TB E
    ON EJ.ID_ESTADO = E.ID_ESTADO;
  
  /
    
CREATE OR REPLACE VIEW FIDE_FACTURACION_JUGADORES_V AS
SELECT
    F.ID_FACTURACION_INSCRIPCION,
    J.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS JUGADOR,
    C.NOMBRE_CATEGORIA,
    F.MES,
    F.ANIO,
    F.MONTO,
    F.FECHA_PAGO,
    F.OBSERVACIONES,
    E.NOMBRE_ESTADO
FROM FIDE_FACTURACION_INSCRIPCIONES_TB F
INNER JOIN FIDE_JUGADORES_TB J
    ON F.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_CATEGORIAS_TB C
    ON J.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FIDE_ESTADOS_TB E
    ON F.ID_ESTADO = E.ID_ESTADO;
   
 /  
    
CREATE OR REPLACE VIEW FIDE_LESIONES_JUGADORES_V AS
SELECT
    L.ID_LESION,
    J.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO AS JUGADOR,
    TL.NOMBRE_TIPO_LESION,
    L.DESCRIPCION,
    PM.FECHA AS FECHA_PARTE_MEDICO,
    L.FECHA_RECUPERACION,
    M.NOMBRE || ' ' || M.APELLIDO_PATERNO AS MEDICO,
    ESP.NOMBRE_ESPECIALIDAD,
    E.NOMBRE_ESTADO
FROM FIDE_LESIONES_TB L
INNER JOIN FIDE_TIPOLESION_TB TL
    ON L.ID_TIPOLESION = TL.ID_TIPOLESION
INNER JOIN FIDE_PARTE_MEDICO_TB PM
    ON L.ID_PARTEMEDICO = PM.ID_PARTEMEDICO
INNER JOIN FIDE_JUGADORES_TB J
    ON PM.ID_JUGADOR = J.ID_JUGADOR
INNER JOIN FIDE_MEDICOS_TB M
    ON PM.ID_MEDICO = M.ID_MEDICO
INNER JOIN FIDE_ESPECIALIDADES_TB ESP
    ON M.ID_ESPECIALIDAD = ESP.ID_ESPECIALIDAD
INNER JOIN FIDE_ESTADOS_TB E
    ON L.ID_ESTADO = E.ID_ESTADO;

/

CREATE OR REPLACE VIEW FIDE_CALENDARIO_PARTIDOS_V AS
SELECT
    P.ID_PARTIDO,
    P.FECHA,
    P.RIVAL,
    P.GOLES_FAVOR,
    P.GOLES_CONTRA,
    CASE
        WHEN P.GOLES_FAVOR > P.GOLES_CONTRA THEN 'Victoria'
        WHEN P.GOLES_FAVOR < P.GOLES_CONTRA THEN 'Derrota'
        ELSE 'Empate'
    END AS RESULTADO,
    C.NOMBRE_CATEGORIA,
    TP.TIPO_DE_PARTIDO,
    T.TIPO_TEMPORADA,
    T.ANIO,
    S.NOMBRE_SEDE,
    E.NOMBRE_ESTADO
FROM FIDE_PARTIDOS_TB P
INNER JOIN FIDE_CATEGORIAS_TB C
    ON P.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FIDE_TIPO_PARTIDOS_TB TP
    ON P.ID_TIPOPARTIDOS = TP.ID_TIPOPARTIDOS
INNER JOIN FIDE_TEMPORADAS_TB T
    ON P.ID_TEMPORADA = T.ID_TEMPORADA
INNER JOIN FIDE_SEDES_TB S
    ON P.ID_SEDE = S.ID_SEDE
INNER JOIN FIDE_ESTADOS_TB E
    ON P.ID_ESTADO = E.ID_ESTADO;

