create or replace PACKAGE FIDE_PROYECTOFINALACADEMIALEIVA_PCK AS 

PROCEDURE FIDE_ESTADOS_TB_INSERTAR_SP(
    P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE
);
PROCEDURE FIDE_ESTADOS_TB_MODIFICAR_SP(
    P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE, 
    P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE
);
PROCEDURE FIDE_ESTADOS_TB_ELIMINAR_SP(
    P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE, 
    P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE
);

PROCEDURE FIDE_TIPOTARJETAS_TB_INSERTAR_SP( 
    P_COLOR IN FIDE_TIPOTARJETAS_TB.COLOR%TYPE, P_ID_ESTADO IN FIDE_TIPOTARJETAS_TB.ID_ESTADO%TYPE
);
    
PROCEDURE FIDE_TIPOTARJETAS_TB_MODIFICAR_SP(
    P_ID_TIPOTARJETA IN FIDE_TIPOTARJETAS_TB.ID_TIPOTARJETA%TYPE, 
    P_COLOR IN FIDE_TIPOTARJETAS_TB.COLOR%TYPE, 
    P_ID_ESTADO IN FIDE_TIPOTARJETAS_TB.ID_ESTADO%TYPE
);


PROCEDURE FIDE_TIPOTARJETAS_TB_ELIMINAR_SP(
    P_ID_TIPOTARJETA IN FIDE_TIPOTARJETAS_TB.ID_TIPOTARJETA%TYPE, 
    P_ID_ESTADO IN FIDE_TIPOTARJETAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CANTONES_TB_INSERTAR_SP(
    P_NOMBRE_CANTON IN FIDE_CANTONES_TB.NOMBRE_CANTON%TYPE, 
    P_ID_ESTADO IN FIDE_CANTONES_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CANTONES_TB_MODIFICAR_SP(
    P_ID_CANTON IN FIDE_CANTONES_TB.ID_CANTON%TYPE, 
    P_NOMBRE_CANTON IN FIDE_CANTONES_TB.NOMBRE_CANTON%TYPE, 
    P_ID_ESTADO IN FIDE_CANTONES_TB.ID_ESTADO%TYPE
);
PROCEDURE FIDE_CANTONES_TB_ELIMINAR_SP(
    P_ID_CANTON IN FIDE_CANTONES_TB.ID_CANTON%TYPE, 
    P_ID_ESTADO IN FIDE_CANTONES_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CARGOS_TB_INSERTAR_SP(
    P_NOMBRE_CARGO IN FIDE_CARGOS_TB.NOMBRE_CARGO%TYPE, 
    P_ID_ESTADO IN FIDE_CARGOS_TB.ID_ESTADO%TYPE
);
PROCEDURE FIDE_CARGOS_TB_MODIFICAR_SP(
    P_ID_CARGO IN FIDE_CARGOS_TB.ID_CARGO%TYPE, 
    P_NOMBRE_CARGO IN FIDE_CARGOS_TB.NOMBRE_CARGO%TYPE,
    P_ID_ESTADO IN FIDE_CARGOS_TB.ID_ESTADO%TYPE
);
PROCEDURE FIDE_CARGOS_TB_ELIMINAR_SP(
    P_ID_CARGO IN FIDE_CARGOS_TB.ID_CARGO%TYPE, 
    P_ID_ESTADO IN FIDE_CARGOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CATEGORIAS_TB_INSERTAR_SP(
    P_NOMBRE_CATEGORIA IN FIDE_CATEGORIAS_TB.NOMBRE_CATEGORIA%TYPE, 
    P_ID_ESTADO IN FIDE_CATEGORIAS_TB.ID_ESTADO%TYPE
);
PROCEDURE FIDE_CATEGORIAS_TB_MODIFICAR_SP(
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE, 
    P_NOMBRE_CATEGORIA IN FIDE_CATEGORIAS_TB.NOMBRE_CATEGORIA%TYPE, 
    P_ID_ESTADO IN FIDE_CATEGORIAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CATEGORIAS_TB_ELIMINAR_SP(
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE,
    P_ID_ESTADO IN FIDE_CATEGORIAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CATEGORIA_INVENTARIO_TB_INSERTAR_SP(
    P_NOMBRE_CATEGORIA_INVENTARIO IN FIDE_CATEGORIA_INVENTARIO_TB.NOMBRE_CATEGORIA_INVENTARIO%TYPE, 
    P_ID_ESTADO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CATEGORIA_INVENTARIO_TB_MODIFICAR_SP(
    P_ID_CATEGORIAINVENTARIO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_CATEGORIAINVENTARIO%TYPE, 
    P_NOMBRE_CATEGORIA_INVENTARIO IN FIDE_CATEGORIA_INVENTARIO_TB.NOMBRE_CATEGORIA_INVENTARIO%TYPE, 
    P_ID_ESTADO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CATEGORIA_INVENTARIO_TB_ELIMINAR_SP(
    P_ID_CATEGORIAINVENTARIO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_CATEGORIAINVENTARIO%TYPE, 
    P_ID_ESTADO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_DISTRITOS_TB_INSERTAR_SP(
    P_NOMBRE_DISTRITO IN FIDE_DISTRITOS_TB.NOMBRE_DISTRITO%TYPE, 
    P_ID_ESTADO IN FIDE_DISTRITOS_TB.ID_ESTADO%TYPE
);
PROCEDURE FIDE_DISTRITOS_TB_MODIFICAR_SP(
    P_ID_DISTRITO IN FIDE_DISTRITOS_TB.ID_DISTRITO%TYPE, 
    P_NOMBRE_DISTRITO IN FIDE_DISTRITOS_TB.NOMBRE_DISTRITO%TYPE, 
    P_ID_ESTADO IN FIDE_DISTRITOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_DISTRITOS_TB_ELIMINAR_SP(
    P_ID_DISTRITO IN FIDE_DISTRITOS_TB.ID_DISTRITO%TYPE, 
    P_ID_ESTADO IN FIDE_DISTRITOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_ESPECIALIDADES_TB_INSERTAR_SP(
    P_NOMBRE_ESPECIALIDAD IN FIDE_ESPECIALIDADES_TB.NOMBRE_ESPECIALIDAD%TYPE, 
    P_ID_ESTADO IN FIDE_ESPECIALIDADES_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_ESPECIALIDADES_TB_MODIFICAR_SP(
    P_ID_ESPECIALIDAD IN FIDE_ESPECIALIDADES_TB.ID_ESPECIALIDAD%TYPE, 
    P_NOMBRE_ESPECIALIDAD IN FIDE_ESPECIALIDADES_TB.NOMBRE_ESPECIALIDAD%TYPE, 
    P_ID_ESTADO IN FIDE_ESPECIALIDADES_TB.ID_ESTADO%TYPE
);
PROCEDURE FIDE_ESPECIALIDADES_TB_ELIMINAR_SP(
    P_ID_ESPECIALIDAD IN FIDE_ESPECIALIDADES_TB.ID_ESPECIALIDAD%TYPE, 
    P_ID_ESTADO IN FIDE_ESPECIALIDADES_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_POSICIONES_TB_INSERTAR_SP(
    P_NOMBRE_POSICION IN FIDE_POSICIONES_TB.NOMBRE_POSICION%TYPE, 
    P_ID_ESTADO IN FIDE_POSICIONES_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_POSICIONES_TB_MODIFICAR_SP(
    P_ID_POSICION IN FIDE_POSICIONES_TB.ID_POSICION%TYPE, 
    P_NOMBRE_POSICION IN FIDE_POSICIONES_TB.NOMBRE_POSICION%TYPE, 
    P_ID_ESTADO IN FIDE_POSICIONES_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_POSICIONES_TB_ELIMINAR_SP(
    P_ID_POSICION IN FIDE_POSICIONES_TB.ID_POSICION%TYPE, 
    P_ID_ESTADO IN FIDE_POSICIONES_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_PROVINCIAS_TB_INSERTAR_SP(
    P_NOMBRE_PROVINCIA IN FIDE_PROVINCIAS_TB.NOMBRE_PROVINCIA%TYPE, 
    P_ID_ESTADO IN FIDE_PROVINCIAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_PROVINCIAS_TB_MODIFICAR_SP(
    P_ID_PROVINCIA IN FIDE_PROVINCIAS_TB.ID_PROVINCIA%TYPE, 
    P_NOMBRE_PROVINCIA IN FIDE_PROVINCIAS_TB.NOMBRE_PROVINCIA%TYPE, 
    P_ID_ESTADO IN FIDE_PROVINCIAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_PROVINCIAS_TB_ELIMINAR_SP(
    P_ID_PROVINCIA IN FIDE_PROVINCIAS_TB.ID_PROVINCIA%TYPE, 
    P_ID_ESTADO IN FIDE_PROVINCIAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_TIPOLESION_TB_INSERTAR_SP(
	P_NOMBRE_TIPO_LESION IN FIDE_TIPOLESION_TB.NOMBRE_TIPO_LESION%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_TIPOLESION_TB_MODIFICAR_SP(
	P_ID_TIPOLESION IN FIDE_TIPOLESION_TB.ID_TIPOLESION%TYPE,
	P_NOMBRE_TIPO_LESION IN FIDE_TIPOLESION_TB.NOMBRE_TIPO_LESION%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_TIPOLESION_TB_ELIMINAR_SP(
	P_ID_TIPOLESION IN FIDE_TIPOLESION_TB.ID_TIPOLESION%TYPE
);

PROCEDURE FIDE_TEMPORADAS_TB_INSERTAR_SP(
	P_TIPO_TEMPORADA IN FIDE_TEMPORADAS_TB.TIPO_TEMPORADA%TYPE,
	P_ANIO IN FIDE_TEMPORADAS_TB.ANIO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_TEMPORADAS_TB_MODIFICAR_SP(
	P_ID_TEMPORADA IN FIDE_TEMPORADAS_TB.ID_TEMPORADA%TYPE,
	P_TIPO_TEMPORADA IN FIDE_TEMPORADAS_TB.TIPO_TEMPORADA%TYPE,
	P_ANIO IN FIDE_TEMPORADAS_TB.ANIO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_TEMPORADAS_TB_ELIMINAR_SP(
	P_ID_TEMPORADA IN FIDE_TEMPORADAS_TB.ID_TEMPORADA%TYPE
);

PROCEDURE FIDE_TIPO_PARTIDOS_TB_INSERTAR_SP(
	P_TIPO_DE_PARTIDO IN FIDE_TIPO_PARTIDOS_TB.TIPO_DE_PARTIDO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_TIPO_PARTIDOS_TB_MODIFICAR_SP(
	P_ID_TIPOPARTIDOS IN FIDE_TIPO_PARTIDOS_TB.ID_TIPOPARTIDOS%TYPE,
	P_TIPO_DE_PARTIDO IN FIDE_TIPO_PARTIDOS_TB.TIPO_DE_PARTIDO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_TIPO_PARTIDOS_TB_ELIMINAR_SP(
	P_ID_TIPOPARTIDOS IN FIDE_TIPO_PARTIDOS_TB.ID_TIPOPARTIDOS%TYPE
);

PROCEDURE FIDE_ARTICULOS_TB_INSERTAR_SP(
	P_ID_CATEGORIAINVENTARIO IN FIDE_ARTICULOS_TB.ID_CATEGORIAINVENTARIO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
	P_CANTIDAD IN FIDE_ARTICULOS_TB.CANTIDAD%TYPE,
	P_NOMBRE_ARTICULO IN FIDE_ARTICULOS_TB.NOMBRE_ARTICULO%TYPE
);

PROCEDURE FIDE_ARTICULOS_TB_MODIFICAR_SP(
	P_ID_ARTICULO IN FIDE_ARTICULOS_TB.ID_ARTICULO%TYPE,
	P_ID_CATEGORIAINVENTARIO IN FIDE_ARTICULOS_TB.ID_CATEGORIAINVENTARIO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
	P_CANTIDAD IN FIDE_ARTICULOS_TB.CANTIDAD%TYPE,
	P_NOMBRE_ARTICULO IN FIDE_ARTICULOS_TB.NOMBRE_ARTICULO%TYPE
);

PROCEDURE FIDE_ARTICULOS_TB_ELIMINAR_SP(
	P_ID_ARTICULO IN FIDE_ARTICULOS_TB.ID_ARTICULO%TYPE
);

PROCEDURE FIDE_DIRECCION_EXACTA_TB_INSERTAR_SP(
	P_OTRAS_SENIAS IN FIDE_DIRECCION_EXACTA_TB.OTRAS_SENIAS%TYPE,
	P_ID_DISTRITO IN FIDE_DIRECCION_EXACTA_TB.ID_DISTRITO%TYPE,
	P_ID_CANTON IN FIDE_DIRECCION_EXACTA_TB.ID_CANTON%TYPE,
	P_ID_PROVINCIA IN FIDE_DIRECCION_EXACTA_TB.ID_PROVINCIA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
    P_ID_DIRECCION_EXACTA OUT FIDE_DIRECCION_EXACTA_TB.ID_DIRECCION_EXACTA%TYPE
);

PROCEDURE FIDE_DIRECCION_EXACTA_TB_MODIFICAR_SP(
	P_ID_DIRECCION_EXACTA IN FIDE_DIRECCION_EXACTA_TB.ID_DIRECCION_EXACTA%TYPE,
	P_OTRAS_SENIAS IN FIDE_DIRECCION_EXACTA_TB.OTRAS_SENIAS%TYPE,
	P_ID_DISTRITO IN FIDE_DIRECCION_EXACTA_TB.ID_DISTRITO%TYPE,
	P_ID_CANTON IN FIDE_DIRECCION_EXACTA_TB.ID_CANTON%TYPE,
	P_ID_PROVINCIA IN FIDE_DIRECCION_EXACTA_TB.ID_PROVINCIA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_DIRECCION_EXACTA_TB_ELIMINAR_SP(
	P_ID_DIRECCION_EXACTA IN FIDE_DIRECCION_EXACTA_TB.ID_DIRECCION_EXACTA%TYPE
);

PROCEDURE FIDE_MEDICOS_TB_INSERTAR_SP(
	P_NOMBRE IN FIDE_MEDICOS_TB.NOMBRE%TYPE,
	P_APELLIDO_PATERNO IN FIDE_MEDICOS_TB.APELLIDO_PATERNO%TYPE,
	P_APELLIDO_MATERNO IN FIDE_MEDICOS_TB.APELLIDO_MATERNO%TYPE,
	P_ID_ESPECIALIDAD IN FIDE_MEDICOS_TB.ID_ESPECIALIDAD%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_MEDICOS_TB_MODIFICAR_SP(
	P_ID_MEDICO IN FIDE_MEDICOS_TB.ID_MEDICO%TYPE,
	P_NOMBRE IN FIDE_MEDICOS_TB.NOMBRE%TYPE,
	P_APELLIDO_PATERNO IN FIDE_MEDICOS_TB.APELLIDO_PATERNO%TYPE,
	P_APELLIDO_MATERNO IN FIDE_MEDICOS_TB.APELLIDO_MATERNO%TYPE,
	P_ID_ESPECIALIDAD IN FIDE_MEDICOS_TB.ID_ESPECIALIDAD%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_MEDICOS_TB_ELIMINAR_SP(
	P_ID_MEDICO IN FIDE_MEDICOS_TB.ID_MEDICO%TYPE
);

PROCEDURE FIDE_EMPLEADOS_TB_INSERTAR_SP(
	P_NOMBRE IN FIDE_EMPLEADOS_TB.NOMBRE%TYPE,
	P_APELLIDO_PATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_PATERNO%TYPE,
	P_APELLIDO_MATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_MATERNO%TYPE,
	P_EDAD IN FIDE_EMPLEADOS_TB.EDAD%TYPE,
	P_NOMBRE_DE_USUARIO IN FIDE_EMPLEADOS_TB.NOMBRE_DE_USUARIO%TYPE,
	P_CONTRASENIA IN FIDE_EMPLEADOS_TB.CONTRASENIA%TYPE,
	P_ID_CARGO IN FIDE_EMPLEADOS_TB.ID_CARGO%TYPE,
	P_ID_DIRECCION_EXACTA IN FIDE_EMPLEADOS_TB.ID_DIRECCION_EXACTA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_EMPLEADOS_TB_MODIFICAR_SP(
	P_ID_EMPLEADO IN FIDE_EMPLEADOS_TB.ID_EMPLEADO%TYPE,
	P_NOMBRE IN FIDE_EMPLEADOS_TB.NOMBRE%TYPE,
	P_APELLIDO_PATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_PATERNO%TYPE,
	P_APELLIDO_MATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_MATERNO%TYPE,
	P_EDAD IN FIDE_EMPLEADOS_TB.EDAD%TYPE,
	P_NOMBRE_DE_USUARIO IN FIDE_EMPLEADOS_TB.NOMBRE_DE_USUARIO%TYPE,
	P_CONTRASENIA IN FIDE_EMPLEADOS_TB.CONTRASENIA%TYPE,
	P_ID_CARGO IN FIDE_EMPLEADOS_TB.ID_CARGO%TYPE,
	P_ID_DIRECCION_EXACTA IN FIDE_EMPLEADOS_TB.ID_DIRECCION_EXACTA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_EMPLEADOS_TB_ELIMINAR_SP(
	P_ID_EMPLEADO IN FIDE_EMPLEADOS_TB.ID_EMPLEADO%TYPE
);

PROCEDURE FIDE_JUGADORES_TB_INSERTAR_SP(
    P_CEDULA IN FIDE_JUGADORES_TB.CEDULA%TYPE,
    P_ID_CATEGORIA IN FIDE_JUGADORES_TB.ID_CATEGORIA%TYPE,
    P_NOMBRE IN FIDE_JUGADORES_TB.NOMBRE%TYPE,
    P_APELLIDO_MATERNO IN FIDE_JUGADORES_TB.APELLIDO_MATERNO%TYPE,
    P_APELLIDO_PATERNO IN FIDE_JUGADORES_TB.APELLIDO_PATERNO%TYPE,
    P_DORSAL IN FIDE_JUGADORES_TB.DORSAL%TYPE,
    P_FECHA_NACIMIENTO IN FIDE_JUGADORES_TB.FECHA_NACIMIENTO%TYPE,
    P_ID_ESTADO IN FIDE_JUGADORES_TB.ID_ESTADO%TYPE,
    P_ID_DIRECCION_EXACTA IN FIDE_JUGADORES_TB.ID_DIRECCION_EXACTA%TYPE
);



PROCEDURE FIDE_JUGADORES_TB_MODIFICAR_SP(
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE,
    P_CEDULA IN FIDE_JUGADORES_TB.CEDULA%TYPE,
    P_ID_CATEGORIA IN FIDE_JUGADORES_TB.ID_CATEGORIA%TYPE,
    P_NOMBRE IN FIDE_JUGADORES_TB.NOMBRE%TYPE,
    P_APELLIDO_MATERNO IN FIDE_JUGADORES_TB.APELLIDO_MATERNO%TYPE,
    P_APELLIDO_PATERNO IN FIDE_JUGADORES_TB.APELLIDO_PATERNO%TYPE,
    P_DORSAL IN FIDE_JUGADORES_TB.DORSAL%TYPE,
    P_FECHA_NACIMIENTO IN FIDE_JUGADORES_TB.FECHA_NACIMIENTO%TYPE,
    P_ID_ESTADO IN FIDE_JUGADORES_TB.ID_ESTADO%TYPE,
    P_ID_DIRECCION_EXACTA IN FIDE_JUGADORES_TB.ID_DIRECCION_EXACTA%TYPE
);

PROCEDURE FIDE_JUGADORES_TB_ELIMINAR_SP(
	P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
);

PROCEDURE FIDE_SEDES_TB_INSERTAR_SP(
	P_NOMBRE_SEDE IN FIDE_SEDES_TB.NOMBRE_SEDE%TYPE,
	P_ID_DIRECCION_EXACTA IN FIDE_SEDES_TB.ID_DIRECCION_EXACTA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_SEDES_TB_MODIFICAR_SP(
	P_ID_SEDE IN FIDE_SEDES_TB.ID_SEDE%TYPE,
	P_NOMBRE_SEDE IN FIDE_SEDES_TB.NOMBRE_SEDE%TYPE,
	P_ID_DIRECCION_EXACTA IN FIDE_SEDES_TB.ID_DIRECCION_EXACTA%TYPE,
	P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_SEDES_TB_ELIMINAR_SP(
	P_ID_SEDE IN FIDE_SEDES_TB.ID_SEDE%TYPE
);

PROCEDURE FIDE_JUGADOR_POSICIONES_TB_INSERTAR_SP(
    P_ID_JUGADOR IN FIDE_JUGADOR_POSICIONES_TB.ID_JUGADOR%TYPE,
    P_ID_POSICION IN FIDE_JUGADOR_POSICIONES_TB.ID_POSICION%TYPE,
    P_ID_ESTADO IN FIDE_JUGADOR_POSICIONES_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_JUGADOR_POSICIONES_TB_MODIFICAR_SP(
	P_ID_JUGADOR IN FIDE_JUGADOR_POSICIONES_TB.ID_JUGADOR%TYPE,
	P_ID_POSICION_ACTUAL IN FIDE_JUGADOR_POSICIONES_TB.ID_POSICION%TYPE,
	P_ID_POSICION_NUEVA IN FIDE_JUGADOR_POSICIONES_TB.ID_POSICION%TYPE
);

PROCEDURE FIDE_JUGADOR_POSICIONES_TB_ELIMINAR_SP(
	P_ID_JUGADOR IN FIDE_JUGADOR_POSICIONES_TB.ID_JUGADOR%TYPE,
	P_ID_POSICION IN FIDE_JUGADOR_POSICIONES_TB.ID_POSICION%TYPE
);

PROCEDURE FIDE_PARTE_MEDICO_TB_INSERTAR_SP(
	P_ID_JUGADOR IN FIDE_PARTE_MEDICO_TB.ID_JUGADOR%TYPE,
	P_OBSERVACIONES IN FIDE_PARTE_MEDICO_TB.OBSERVACIONES%TYPE,
	P_FECHA IN FIDE_PARTE_MEDICO_TB.FECHA%TYPE,
	P_ID_MEDICO IN FIDE_PARTE_MEDICO_TB.ID_MEDICO%TYPE,
	P_ID_ESTADO IN FIDE_PARTE_MEDICO_TB.ID_ESTADO%TYPE
);


PROCEDURE FIDE_PARTE_MEDICO_TB_MODIFICAR_SP(
	P_ID_PARTEMEDICO IN FIDE_PARTE_MEDICO_TB.ID_PARTEMEDICO%TYPE,
	P_ID_JUGADOR IN FIDE_PARTE_MEDICO_TB.ID_JUGADOR%TYPE,
	P_OBSERVACIONES IN FIDE_PARTE_MEDICO_TB.OBSERVACIONES%TYPE,
	P_FECHA IN FIDE_PARTE_MEDICO_TB.FECHA%TYPE,
	P_ID_MEDICO IN FIDE_PARTE_MEDICO_TB.ID_MEDICO%TYPE,
	P_ID_ESTADO IN FIDE_PARTE_MEDICO_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_PARTE_MEDICO_TB_ELIMINAR_SP(
	P_ID_PARTEMEDICO IN FIDE_PARTE_MEDICO_TB.ID_PARTEMEDICO%TYPE
);

PROCEDURE FIDE_PARTIDOS_TB_INSERTAR_SP(
	P_ID_CATEGORIA IN FIDE_PARTIDOS_TB.ID_CATEGORIA%TYPE,
	P_ID_TIPOPARTIDOS IN FIDE_PARTIDOS_TB.ID_TIPOPARTIDOS%TYPE,
	P_ID_TEMPORADA IN FIDE_PARTIDOS_TB.ID_TEMPORADA%TYPE,
	P_FECHA IN FIDE_PARTIDOS_TB.FECHA%TYPE,
	P_RIVAL IN FIDE_PARTIDOS_TB.RIVAL%TYPE,
	P_GOLES_FAVOR IN FIDE_PARTIDOS_TB.GOLES_FAVOR%TYPE,
	P_GOLES_CONTRA IN FIDE_PARTIDOS_TB.GOLES_CONTRA%TYPE,
	P_ID_SEDE IN FIDE_PARTIDOS_TB.ID_SEDE%TYPE,
	P_ID_ESTADO IN FIDE_PARTIDOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_PARTIDOS_TB_MODIFICAR_SP(
	P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE,
	P_ID_CATEGORIA IN FIDE_PARTIDOS_TB.ID_CATEGORIA%TYPE,
	P_ID_TIPOPARTIDOS IN FIDE_PARTIDOS_TB.ID_TIPOPARTIDOS%TYPE,
	P_ID_TEMPORADA IN FIDE_PARTIDOS_TB.ID_TEMPORADA%TYPE,
	P_FECHA IN FIDE_PARTIDOS_TB.FECHA%TYPE,
	P_RIVAL IN FIDE_PARTIDOS_TB.RIVAL%TYPE,
	P_GOLES_FAVOR IN FIDE_PARTIDOS_TB.GOLES_FAVOR%TYPE,
	P_GOLES_CONTRA IN FIDE_PARTIDOS_TB.GOLES_CONTRA%TYPE,
	P_ID_SEDE IN FIDE_PARTIDOS_TB.ID_SEDE%TYPE,
	P_ID_ESTADO IN FIDE_PARTIDOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_PARTIDOS_TB_ELIMINAR_SP(
	P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE
);

PROCEDURE FIDE_REVISION_FISICA_TB_INSERTAR_SP(
	P_ID_JUGADOR IN FIDE_REVISION_FISICA_TB.ID_JUGADOR%TYPE,
	P_PESO IN FIDE_REVISION_FISICA_TB.PESO%TYPE,
	P_IMC IN FIDE_REVISION_FISICA_TB.IMC%TYPE,
	P_ALTURA IN FIDE_REVISION_FISICA_TB.ALTURA%TYPE,
	P_FECHA_REVISION IN FIDE_REVISION_FISICA_TB.FECHA_REVISION%TYPE,
	P_ID_ESTADO IN FIDE_REVISION_FISICA_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_REVISION_FISICA_TB_MODIFICAR_SP(
	P_ID_REVISION IN FIDE_REVISION_FISICA_TB.ID_REVISION%TYPE,
	P_ID_JUGADOR IN FIDE_REVISION_FISICA_TB.ID_JUGADOR%TYPE,
	P_PESO IN FIDE_REVISION_FISICA_TB.PESO%TYPE,
	P_IMC IN FIDE_REVISION_FISICA_TB.IMC%TYPE,
	P_ALTURA IN FIDE_REVISION_FISICA_TB.ALTURA%TYPE,
	P_FECHA_REVISION IN FIDE_REVISION_FISICA_TB.FECHA_REVISION%TYPE,
	P_ID_ESTADO IN FIDE_REVISION_FISICA_TB.ID_ESTADO%TYPE
);


PROCEDURE FIDE_REVISION_FISICA_TB_ELIMINAR_SP(
	P_ID_REVISION IN FIDE_REVISION_FISICA_TB.ID_REVISION%TYPE
);

PROCEDURE FIDE_TELEFONOS_TB_INSERTAR_SP(
	P_NUMERO_TELEFONO IN FIDE_TELEFONOS_TB.NUMERO_TELEFONO%TYPE,
	P_ID_EMPLEADO IN FIDE_TELEFONOS_TB.ID_EMPLEADO%TYPE,
	P_ID_ESTADO IN FIDE_TELEFONOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_TELEFONOS_TB_MODIFICAR_SP(
	P_ID_TELEFONO IN FIDE_TELEFONOS_TB.ID_TELEFONO%TYPE,
	P_NUMERO_TELEFONO IN FIDE_TELEFONOS_TB.NUMERO_TELEFONO%TYPE,
	P_ID_EMPLEADO IN FIDE_TELEFONOS_TB.ID_EMPLEADO%TYPE,
	P_ID_ESTADO IN FIDE_TELEFONOS_TB.ID_ESTADO%TYPE
);

PROCEDURE  FIDE_TELEFONOS_TB_ELIMINAR_SP(
	P_ID_TELEFONO IN FIDE_TELEFONOS_TB.ID_TELEFONO%TYPE
);

PROCEDURE FIDE_CORREOS_TB_INSERTAR_SP(
	P_CORREO_ELECTRONICO IN FIDE_CORREOS_TB.CORREO_ELECTRONICO%TYPE,
	P_ID_EMPLEADO IN FIDE_CORREOS_TB.ID_EMPLEADO%TYPE,
	P_ID_ESTADO IN FIDE_CORREOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CORREOS_TB_MODIFICAR_SP(
	P_ID_CORREO IN FIDE_CORREOS_TB.ID_CORREO%TYPE,
	P_CORREO_ELECTRONICO IN FIDE_CORREOS_TB.CORREO_ELECTRONICO%TYPE,
	P_ID_EMPLEADO IN FIDE_CORREOS_TB.ID_EMPLEADO%TYPE,
	P_ID_ESTADO IN FIDE_CORREOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CORREOS_TB_ELIMINAR_SP(
	P_ID_CORREO IN FIDE_CORREOS_TB.ID_CORREO%TYPE
);

PROCEDURE FIDE_ASISTENCIA_TB_INSERTAR_SP(
	P_ID_PARTIDO IN FIDE_ASISTENCIA_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_ASISTENCIA_TB.ID_JUGADOR%TYPE,
	P_ID_ESTADO IN FIDE_ASISTENCIA_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_ASISTENCIA_TB_MODIFICAR_SP(
	P_ID_PARTIDO IN FIDE_ASISTENCIA_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_ASISTENCIA_TB.ID_JUGADOR%TYPE,
	P_ID_ESTADO IN FIDE_ASISTENCIA_TB.ID_ESTADO%TYPE
);


PROCEDURE FIDE_ASISTENCIA_TB_ELIMINAR_SP(
	P_ID_PARTIDO IN FIDE_ASISTENCIA_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_ASISTENCIA_TB.ID_JUGADOR%TYPE
);

PROCEDURE FIDE_ESTADISTICA_EQUIPO_TB_INSERTAR_SP(
	P_TIROS IN FIDE_ESTADISTICA_EQUIPO_TB.TIROS%TYPE,
	P_TIROS_PORTERIA IN FIDE_ESTADISTICA_EQUIPO_TB.TIROS_PORTERIA%TYPE,
	P_PASES_EXITOSOS IN FIDE_ESTADISTICA_EQUIPO_TB.PASES_EXITOSOS%TYPE,
	P_PASES_FALLIDOS IN FIDE_ESTADISTICA_EQUIPO_TB.PASES_FALLIDOS%TYPE,
	P_POSESION_BALON IN FIDE_ESTADISTICA_EQUIPO_TB.POSESION_BALON%TYPE,
	P_ID_PARTIDO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_PARTIDO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_ESTADISTICA_EQUIPO_TB_MODIFICAR_SP(
	P_ID_ESTADISTICA_EQUIPO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_ESTADISTICA_EQUIPO%TYPE,
	P_TIROS IN FIDE_ESTADISTICA_EQUIPO_TB.TIROS%TYPE,
	P_TIROS_PORTERIA IN FIDE_ESTADISTICA_EQUIPO_TB.TIROS_PORTERIA%TYPE,
	P_PASES_EXITOSOS IN FIDE_ESTADISTICA_EQUIPO_TB.PASES_EXITOSOS%TYPE,
	P_PASES_FALLIDOS IN FIDE_ESTADISTICA_EQUIPO_TB.PASES_FALLIDOS%TYPE,
	P_POSESION_BALON IN FIDE_ESTADISTICA_EQUIPO_TB.POSESION_BALON%TYPE,
	P_ID_PARTIDO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_PARTIDO%TYPE,
	P_ID_ESTADO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_ESTADISTICA_EQUIPO_TB_ELIMINAR_SP(
	P_ID_ESTADISTICA_EQUIPO IN FIDE_ESTADISTICA_EQUIPO_TB.ID_ESTADISTICA_EQUIPO%TYPE
);

PROCEDURE FIDE_ESTADISTICA_JUGADOR_TB_INSERTAR_SP(
	P_ID_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_JUGADOR%TYPE,
	P_ID_PARTIDO IN FIDE_ESTADISTICA_JUGADOR_TB.ID_PARTIDO%TYPE,
	P_PASES IN FIDE_ESTADISTICA_JUGADOR_TB.PASES%TYPE,
	P_PASES_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.PASES_EXITOSOS%TYPE,
	P_REGATES IN FIDE_ESTADISTICA_JUGADOR_TB.REGATES%TYPE,
	P_REGATES_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.REGATES_EXITOSOS%TYPE,
	P_TIROS IN FIDE_ESTADISTICA_JUGADOR_TB.TIROS%TYPE,
	P_TIROS_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.TIROS_EXITOSOS%TYPE,
	P_ENTRADAS IN FIDE_ESTADISTICA_JUGADOR_TB.ENTRADAS%TYPE,
	P_ENTRADAS_EXITOSAS IN FIDE_ESTADISTICA_JUGADOR_TB.ENTRADAS_EXITOSAS%TYPE,
	P_MINUTOS_JUGADOS IN FIDE_ESTADISTICA_JUGADOR_TB.MINUTOS_JUGADOS%TYPE,
	P_GOLES IN FIDE_ESTADISTICA_JUGADOR_TB.GOLES%TYPE,
	P_ASISTENCIAS IN FIDE_ESTADISTICA_JUGADOR_TB.ASISTENCIAS%TYPE,
	P_ID_ESTADO IN FIDE_ESTADISTICA_JUGADOR_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_ESTADISTICA_JUGADOR_TB_MODIFICAR_SP(
	P_ID_ESTADISTICA_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_ESTADISTICA_JUGADOR%TYPE,
	P_ID_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_JUGADOR%TYPE,
	P_ID_PARTIDO IN FIDE_ESTADISTICA_JUGADOR_TB.ID_PARTIDO%TYPE,
	P_PASES IN FIDE_ESTADISTICA_JUGADOR_TB.PASES%TYPE,
	P_PASES_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.PASES_EXITOSOS%TYPE,
	P_REGATES IN FIDE_ESTADISTICA_JUGADOR_TB.REGATES%TYPE,
	P_REGATES_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.REGATES_EXITOSOS%TYPE,
	P_TIROS IN FIDE_ESTADISTICA_JUGADOR_TB.TIROS%TYPE,
	P_TIROS_EXITOSOS IN FIDE_ESTADISTICA_JUGADOR_TB.TIROS_EXITOSOS%TYPE,
	P_ENTRADAS IN FIDE_ESTADISTICA_JUGADOR_TB.ENTRADAS%TYPE,
	P_ENTRADAS_EXITOSAS IN FIDE_ESTADISTICA_JUGADOR_TB.ENTRADAS_EXITOSAS%TYPE,
	P_MINUTOS_JUGADOS IN FIDE_ESTADISTICA_JUGADOR_TB.MINUTOS_JUGADOS%TYPE,
	P_GOLES IN FIDE_ESTADISTICA_JUGADOR_TB.GOLES%TYPE,
	P_ASISTENCIAS IN FIDE_ESTADISTICA_JUGADOR_TB.ASISTENCIAS%TYPE,
	P_ID_ESTADO IN FIDE_ESTADISTICA_JUGADOR_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_ESTADISTICA_JUGADOR_TB_ELIMINAR_SP(
	P_ID_ESTADISTICA_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_ESTADISTICA_JUGADOR%TYPE
);

PROCEDURE FIDE_LESIONES_TB_INSERTAR_SP(
	P_DESCRIPCION IN FIDE_LESIONES_TB.DESCRIPCION%TYPE,
	P_FECHA_RECUPERACION IN FIDE_LESIONES_TB.FECHA_RECUPERACION%TYPE,
	P_ID_TIPOLESION IN FIDE_LESIONES_TB.ID_TIPOLESION%TYPE,
	P_ID_PARTEMEDICO IN FIDE_LESIONES_TB.ID_PARTEMEDICO%TYPE,
	P_ID_ESTADO IN FIDE_LESIONES_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_LESIONES_TB_MODIFICAR_SP(
	P_ID_LESION IN FIDE_LESIONES_TB.ID_LESION%TYPE,
	P_DESCRIPCION IN FIDE_LESIONES_TB.DESCRIPCION%TYPE,
	P_FECHA_RECUPERACION IN FIDE_LESIONES_TB.FECHA_RECUPERACION%TYPE,
	P_ID_TIPOLESION IN FIDE_LESIONES_TB.ID_TIPOLESION%TYPE,
	P_ID_PARTEMEDICO IN FIDE_LESIONES_TB.ID_PARTEMEDICO%TYPE,
	P_ID_ESTADO IN FIDE_LESIONES_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_LESIONES_TB_ELIMINAR_SP(
	P_ID_LESION IN FIDE_LESIONES_TB.ID_LESION%TYPE
);

PROCEDURE FIDE_TARJETAS_TB_INSERTAR_SP(
	P_ID_PARTIDO IN FIDE_TARJETAS_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_TARJETAS_TB.ID_JUGADOR%TYPE,
	P_ID_TIPOTARJETA IN FIDE_TARJETAS_TB.ID_TIPOTARJETA%TYPE,
	P_CANTIDAD_TARJETAS IN FIDE_TARJETAS_TB.CANTIDAD_TARJETAS%TYPE,
	P_ID_ESTADO IN FIDE_TARJETAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_TARJETAS_TB_MODIFICAR_SP(
	P_ID_PARTIDO IN FIDE_TARJETAS_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_TARJETAS_TB.ID_JUGADOR%TYPE,
	P_ID_TIPOTARJETA IN FIDE_TARJETAS_TB.ID_TIPOTARJETA%TYPE,
	P_CANTIDAD_TARJETAS IN FIDE_TARJETAS_TB.CANTIDAD_TARJETAS%TYPE,
	P_ID_ESTADO IN FIDE_TARJETAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_TARJETAS_TB_ELIMINAR_SP(
	P_ID_PARTIDO IN FIDE_TARJETAS_TB.ID_PARTIDO%TYPE,
	P_ID_JUGADOR IN FIDE_TARJETAS_TB.ID_JUGADOR%TYPE,
	P_ID_TIPOTARJETA IN FIDE_TARJETAS_TB.ID_TIPOTARJETA%TYPE
);

PROCEDURE FIDE_FACTURACION_INSCRIPCIONES_TB_INSERTAR_SP(
	P_ID_JUGADOR IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_JUGADOR%TYPE,
	P_MES IN FIDE_FACTURACION_INSCRIPCIONES_TB.MES%TYPE,
	P_ANIO IN FIDE_FACTURACION_INSCRIPCIONES_TB.ANIO%TYPE,
	P_MONTO IN FIDE_FACTURACION_INSCRIPCIONES_TB.MONTO%TYPE,
	P_FECHA_PAGO IN FIDE_FACTURACION_INSCRIPCIONES_TB.FECHA_PAGO%TYPE,
	P_ID_ESTADO IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_ESTADO%TYPE,
	P_OBSERVACIONES IN FIDE_FACTURACION_INSCRIPCIONES_TB.OBSERVACIONES%TYPE
);

PROCEDURE FIDE_FACTURACION_INSCRIPCIONES_TB_MODIFICAR_SP(
	P_ID_FACTURACION_INSCRIPCION IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_FACTURACION_INSCRIPCION%TYPE,
	P_ID_JUGADOR IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_JUGADOR%TYPE,
	P_MES IN FIDE_FACTURACION_INSCRIPCIONES_TB.MES%TYPE,
	P_ANIO IN FIDE_FACTURACION_INSCRIPCIONES_TB.ANIO%TYPE,
	P_MONTO IN FIDE_FACTURACION_INSCRIPCIONES_TB.MONTO%TYPE,
	P_FECHA_PAGO IN FIDE_FACTURACION_INSCRIPCIONES_TB.FECHA_PAGO%TYPE,
	P_ID_ESTADO IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_ESTADO%TYPE,
	P_OBSERVACIONES IN FIDE_FACTURACION_INSCRIPCIONES_TB.OBSERVACIONES%TYPE
);

PROCEDURE  FIDE_FACTURACION_INSCRIPCIONES_TB_ELIMINAR_SP(
	P_ID_FACTURACION_INSCRIPCION IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_FACTURACION_INSCRIPCION%TYPE
);


FUNCTION FIDE_CATEGORIAS_TB_CATEGORIAS_LISTAR_FN(
	P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE
)
RETURN VARCHAR2;


FUNCTION FIDE_ESPECIALIDADES_TB_ESPECIALIDADES_LISTAR_FN(
	P_ID_ESPECIALIDAD IN FIDE_ESPECIALIDADES_TB.ID_ESPECIALIDAD%TYPE
)
RETURN VARCHAR2;


FUNCTION FIDE_TIPOLESION_TB_TIPO_LESION_LISTAR_FN(
	P_ID_TIPOLESION IN FIDE_TIPOLESION_TB.ID_TIPOLESION%TYPE
)
RETURN VARCHAR2;

FUNCTION FIDE_TIPOTARJETAS_TB_TIPO_TARJETAS_LISTAR_FN(
	P_ID_TIPOTARJETA IN FIDE_TIPOTARJETAS_TB.ID_TIPOTARJETA%TYPE
)
RETURN VARCHAR2;
	
FUNCTION FIDE_CATEGORIA_INVENTARIO_TB_CATEGORIA_INVENTARIO_LISTAR_FN(
	P_ID_CATEGORIAINVENTARIO IN FIDE_CATEGORIA_INVENTARIO_TB.ID_CATEGORIAINVENTARIO%TYPE
)
RETURN VARCHAR2;

FUNCTION FIDE_POSICIONES_TB_POSICIONES_LISTAR_FN(
	P_ID_POSICION IN FIDE_POSICIONES_TB.ID_POSICION%TYPE
)
RETURN VARCHAR2;

FUNCTION FIDE_JUGADORES_TB_DORSALES_LISTAR_FN(
	P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER;

FUNCTION FIDE_PARTIDOS_TB_RESULTADO_PARTIDO_FN(
	P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE
)
RETURN VARCHAR2;


FUNCTION FIDE_ASISTENCIA_TB_TOTAL_ASISTENCIA_PARTIDO_FN(
	P_ID_PARTIDO IN FIDE_ASISTENCIA_TB.ID_PARTIDO%TYPE
)
RETURN NUMBER;

FUNCTION FIDE_ESTADISTICA_JUGADOR_TB_TOTAL_GOLES_JUGADOR_FN(
	P_ID_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER;

FUNCTION FIDE_ESTADISTICA_JUGADOR_TB_TOTAL_ASISTENCIAS_JUGADOR_FN(
	P_ID_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER;

FUNCTION FIDE_TARJETAS_TB_TOTAL_TARJETAS_JUGADOR_FN(
	P_ID_JUGADOR IN FIDE_TARJETAS_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER;

FUNCTION FIDE_FACTURACION_TB_MONTO_PAGADO_JUGADOR_FN(
	P_ID_JUGADOR IN FIDE_FACTURACION_INSCRIPCIONES_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER;

FUNCTION FIDE_PARTE_MEDICO_TB_TOTAL_LESIONES_JUGADOR_FN(
	P_ID_JUGADOR IN FIDE_PARTE_MEDICO_TB.ID_JUGADOR%TYPE
)
RETURN NUMBER;


FUNCTION FIDE_ESTADISTICA_JUGADOR_TB_PROMEDIO_MINUTOS_JUGADOS_FN(
	P_ID_JUGADOR IN FIDE_ESTADISTICA_JUGADOR_TB.ID_JUGADOR%TYPE
) RETURN NUMBER;

FUNCTION FIDE_EMPLEADOS_TB_VALIDAR_LOGIN_FN(
    P_USUARIO IN FIDE_EMPLEADOS_TB.NOMBRE_DE_USUARIO%TYPE,
    P_CONTRASENIA IN FIDE_EMPLEADOS_TB.CONTRASENIA%TYPE
) RETURN NUMBER;


FUNCTION FIDE_ESTADOS_TB_VALIDAR_NOMBRE_ESTADO_FN(
    P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE
) RETURN VARCHAR2;


FUNCTION FIDE_FACTURACION_INSCRIPCIONES_TB_GENERAR_SEQUENCIA_NUM_SEQ_FN
RETURN NUMBER;


PROCEDURE FIDE_FACTURACION_INSCRIPCIONES_TB_GENERAR_MENSUALES_SP;

PROCEDURE FIDE_FACTURACION_INSCRIPCIONES_TB_CREAR_INICIAL_SP (
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE,
    P_ID_ESTADO  IN FIDE_JUGADORES_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_JUGADORES_TB_DESACTIVAR_MOROSOS_SP;

PROCEDURE FIDE_JUGADORES_TB_REACTIVAR_MOROSOS_SP;

FUNCTION FIDE_CONSULTAS_TEMPORADAS_LISTAR_FN RETURN CLOB;
FUNCTION FIDE_CONSULTAS_CATEGORIAS_LISTAR_FN RETURN CLOB;
FUNCTION FIDE_CONSULTAS_POSICIONES_LISTAR_FN RETURN CLOB;
FUNCTION FIDE_CONSULTAS_PARTIDOS_BUSCAR_FN(P_ANIO NUMBER, P_TEMPORADA NUMBER, P_RIVAL VARCHAR2, P_FECHA VARCHAR2, P_RESULTADO VARCHAR2) RETURN CLOB;
FUNCTION FIDE_CONSULTAS_JUGADORES_BUSCAR_FN(P_NOMBRE VARCHAR2, P_CATEGORIA NUMBER, P_CEDULA VARCHAR2, P_POSICION NUMBER) RETURN CLOB;
FUNCTION FIDE_CONSULTAS_JUGADOR_RESUMEN_FN(P_JUGADOR NUMBER) RETURN CLOB;
FUNCTION FIDE_CONSULTAS_JUGADORES_COMPARAR_FN(P_JUGADOR_1 NUMBER, P_JUGADOR_2 NUMBER, P_JUGADOR_3 NUMBER) RETURN CLOB;
FUNCTION FIDE_CONSULTAS_PARTIDO_DETALLE_FN(P_PARTIDO NUMBER) RETURN CLOB;
FUNCTION FIDE_CONSULTAS_PARTIDO_JUGADORES_FN(P_PARTIDO NUMBER) RETURN CLOB;
FUNCTION FIDE_CONSULTAS_JUGADOR_PARTIDO_FN(P_JUGADOR NUMBER, P_PARTIDO NUMBER) RETURN CLOB;
FUNCTION FIDE_CONSULTAS_DISPONIBILIDAD_FN(P_CATEGORIA NUMBER) RETURN CLOB;
FUNCTION FIDE_CONSULTAS_JUGADOR_LESIONES_FN(P_JUGADOR NUMBER) RETURN CLOB;
FUNCTION FIDE_CONSULTAS_JUGADOR_PARTIDOS_FN(P_JUGADOR NUMBER) RETURN CLOB;
FUNCTION FIDE_JUGADORES_TB_VALIDAR_EDAD_CATEGORIA_FN(P_FECHA_NACIMIENTO DATE, P_ID_CATEGORIA NUMBER) RETURN NUMBER;

END;
