-- El backend reserva ID_DIRECCION_EXACTA_SEQ.NEXTVAL para relacionar
-- la direccion con jugadores, empleados o sedes.
-- Ejecutar este script en Oracle antes de probar esos formularios.

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_EXACTA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_DIRECCION_EXACTA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_DIRECCION_EXACTA IS NULL THEN
        :NEW.ID_DIRECCION_EXACTA := ID_DIRECCION_EXACTA_SEQ.NEXTVAL;
    END IF;

    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_DIRECCION_EXACTA_TB_INSERT_TRG;
/
