/*
    Consultas deportivas base.

    Las vistas de analisis se encuentran en consultas_analisis.sql.
    Ambos archivos pertenecen al mismo paquete:
    FIDE_PROYECTOFINALACADEMIALEIVA_PCK.
*/

CREATE OR REPLACE FORCE VIEW FIDE_JUGADORES_CONSULTA_V AS
SELECT
    J.ID_JUGADOR,
    J.CEDULA,
    J.ID_CATEGORIA,
    C.NOMBRE_CATEGORIA,
    J.NOMBRE,
    J.APELLIDO_PATERNO,
    J.APELLIDO_MATERNO,
    J.DORSAL,
    J.FECHA_NACIMIENTO,
    J.ID_ESTADO,
    J.ID_DIRECCION_EXACTA
FROM FIDE_JUGADORES_TB J
LEFT JOIN FIDE_CATEGORIAS_TB C ON C.ID_CATEGORIA = J.ID_CATEGORIA;

CREATE OR REPLACE FORCE VIEW FIDE_JUGADOR_POSICIONES_CONSULTA_V AS
SELECT
    JP.ID_JUGADOR,
    JP.ID_POSICION,
    P.NOMBRE_POSICION
FROM FIDE_JUGADOR_POSICIONES_TB JP
JOIN FIDE_POSICIONES_TB P ON P.ID_POSICION = JP.ID_POSICION
WHERE JP.ID_ESTADO = 1
  AND P.ID_ESTADO = 1;

CREATE OR REPLACE FORCE VIEW FIDE_ESTADISTICA_JUGADOR_CONSULTA_V AS
SELECT
    E.ID_JUGADOR,
    E.ID_PARTIDO,
    P.ID_TEMPORADA,
    E.PASES,
    E.PASES_EXITOSOS,
    E.REGATES,
    E.REGATES_EXITOSOS,
    E.TIROS,
    E.TIROS_EXITOSOS,
    E.ENTRADAS,
    E.ENTRADAS_EXITOSAS,
    E.MINUTOS_JUGADOS,
    E.GOLES,
    E.ASISTENCIAS
FROM FIDE_ESTADISTICA_JUGADOR_TB E
LEFT JOIN FIDE_PARTIDOS_TB P ON P.ID_PARTIDO = E.ID_PARTIDO
WHERE E.ID_ESTADO = 1;

/* ============================ PACKAGE SPEC ============================ */

FUNCTION FIDE_CONSULTAS_TEMPORADAS_LISTAR_FN RETURN CLOB;

FUNCTION FIDE_CONSULTAS_POSICIONES_LISTAR_FN RETURN CLOB;

FUNCTION FIDE_CONSULTAS_CATEGORIAS_LISTAR_FN RETURN CLOB;

FUNCTION FIDE_CONSULTAS_PARTIDOS_BUSCAR_FN(
    P_ANIO IN FIDE_TEMPORADAS_TB.ANIO%TYPE,
    P_ID_TEMPORADA IN FIDE_TEMPORADAS_TB.ID_TEMPORADA%TYPE,
    P_RIVAL IN FIDE_PARTIDOS_TB.RIVAL%TYPE,
    P_FECHA IN VARCHAR2,
    P_RESULTADO IN VARCHAR2
) RETURN CLOB;

FUNCTION FIDE_CONSULTAS_JUGADORES_BUSCAR_FN(
    P_NOMBRE IN FIDE_JUGADORES_TB.NOMBRE%TYPE,
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE,
    P_CEDULA IN FIDE_JUGADORES_TB.CEDULA%TYPE,
    P_ID_POSICION IN FIDE_POSICIONES_TB.ID_POSICION%TYPE
) RETURN CLOB;

FUNCTION FIDE_CONSULTAS_JUGADOR_RESUMEN_FN(
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
) RETURN CLOB;

/* ============================ PACKAGE BODY ============================ */

PROCEDURE FIDE_JSON_INICIAR(P_JSON OUT CLOB) IS
BEGIN
    DBMS_LOB.CREATETEMPORARY(P_JSON, TRUE);
    DBMS_LOB.WRITEAPPEND(P_JSON, 1, '[');
END FIDE_JSON_INICIAR;

PROCEDURE FIDE_JSON_AGREGAR(
    P_JSON IN OUT NOCOPY CLOB,
    P_ITEM IN CLOB,
    P_PRIMER_ITEM IN OUT BOOLEAN
) IS
BEGIN
    IF NOT P_PRIMER_ITEM THEN
        DBMS_LOB.WRITEAPPEND(P_JSON, 1, ',');
    END IF;

    DBMS_LOB.APPEND(P_JSON, P_ITEM);
    P_PRIMER_ITEM := FALSE;
END FIDE_JSON_AGREGAR;

PROCEDURE FIDE_JSON_CERRAR(P_JSON IN OUT NOCOPY CLOB) IS
BEGIN
    DBMS_LOB.WRITEAPPEND(P_JSON, 1, ']');
END FIDE_JSON_CERRAR;

FUNCTION FIDE_CONSULTAS_TEMPORADAS_LISTAR_FN RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_DATOS IS
        SELECT JSON_OBJECT(
            'ID_TEMPORADA' VALUE ID_TEMPORADA,
            'TIPO_TEMPORADA' VALUE TIPO_TEMPORADA,
            'ANIO' VALUE ANIO RETURNING CLOB
        ) AS ITEM
        FROM FIDE_TEMPORADAS_V
        WHERE ID_ESTADO = 1
        ORDER BY ANIO DESC;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR DATO IN C_DATOS LOOP
        FIDE_JSON_AGREGAR(V_JSON, DATO.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_TEMPORADAS_LISTAR_FN;

FUNCTION FIDE_CONSULTAS_POSICIONES_LISTAR_FN RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_DATOS IS
        SELECT JSON_OBJECT(
            'ID_POSICION' VALUE ID_POSICION,
            'NOMBRE_POSICION' VALUE NOMBRE_POSICION RETURNING CLOB
        ) AS ITEM
        FROM FIDE_POSICIONES_V
        WHERE ID_ESTADO = 1
        ORDER BY NOMBRE_POSICION;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR DATO IN C_DATOS LOOP
        FIDE_JSON_AGREGAR(V_JSON, DATO.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_POSICIONES_LISTAR_FN;

FUNCTION FIDE_CONSULTAS_CATEGORIAS_LISTAR_FN RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_DATOS IS
        SELECT JSON_OBJECT(
            'ID_CATEGORIA' VALUE ID_CATEGORIA,
            'NOMBRE_CATEGORIA' VALUE NOMBRE_CATEGORIA RETURNING CLOB
        ) AS ITEM
        FROM FIDE_CATEGORIAS_V
        WHERE ID_ESTADO = 1
        ORDER BY NOMBRE_CATEGORIA;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR DATO IN C_DATOS LOOP
        FIDE_JSON_AGREGAR(V_JSON, DATO.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_CATEGORIAS_LISTAR_FN;

FUNCTION FIDE_CONSULTAS_PARTIDOS_BUSCAR_FN(
    P_ANIO IN FIDE_TEMPORADAS_TB.ANIO%TYPE,
    P_ID_TEMPORADA IN FIDE_TEMPORADAS_TB.ID_TEMPORADA%TYPE,
    P_RIVAL IN FIDE_PARTIDOS_TB.RIVAL%TYPE,
    P_FECHA IN VARCHAR2,
    P_RESULTADO IN VARCHAR2
) RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_DATOS IS
        SELECT JSON_OBJECT(
            'ID_PARTIDO' VALUE P.ID_PARTIDO,
            'ID_CATEGORIA' VALUE P.ID_CATEGORIA,
            'ID_TEMPORADA' VALUE P.ID_TEMPORADA,
            'TIPO_TEMPORADA' VALUE P.TIPO_TEMPORADA,
            'TEMPORADA_ANIO' VALUE P.TEMPORADA_ANIO,
            'FECHA' VALUE P.FECHA,
            'RIVAL' VALUE P.RIVAL,
            'GOLES_FAVOR' VALUE P.GOLES_FAVOR,
            'GOLES_CONTRA' VALUE P.GOLES_CONTRA,
            'RESULTADO' VALUE P.RESULTADO,
            'TOTAL_ASISTENCIA' VALUE P.TOTAL_ASISTENCIA RETURNING CLOB
        ) AS ITEM
        FROM FIDE_PARTIDOS_RESUMEN_CONSULTA_V P
        WHERE P.ID_ESTADO = 1
          AND (P_ANIO IS NULL OR P.TEMPORADA_ANIO = P_ANIO)
          AND (P_ID_TEMPORADA IS NULL OR P.ID_TEMPORADA = P_ID_TEMPORADA)
          AND (P_RIVAL IS NULL OR UPPER(P.RIVAL) LIKE '%' || UPPER(P_RIVAL) || '%')
          AND (P_FECHA IS NULL OR TRUNC(P.FECHA) = TO_DATE(P_FECHA, 'YYYY-MM-DD'))
          AND (P_RESULTADO IS NULL OR P.RESULTADO = P_RESULTADO)
        ORDER BY P.FECHA DESC, P.ID_PARTIDO DESC;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR DATO IN C_DATOS LOOP
        FIDE_JSON_AGREGAR(V_JSON, DATO.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_PARTIDOS_BUSCAR_FN;

FUNCTION FIDE_CONSULTAS_JUGADORES_BUSCAR_FN(
    P_NOMBRE IN FIDE_JUGADORES_TB.NOMBRE%TYPE,
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE,
    P_CEDULA IN FIDE_JUGADORES_TB.CEDULA%TYPE,
    P_ID_POSICION IN FIDE_POSICIONES_TB.ID_POSICION%TYPE
) RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_DATOS IS
        SELECT JSON_OBJECT(
            'ID_JUGADOR' VALUE J.ID_JUGADOR,
            'CEDULA' VALUE J.CEDULA,
            'ID_CATEGORIA' VALUE J.ID_CATEGORIA,
            'NOMBRE_CATEGORIA' VALUE J.NOMBRE_CATEGORIA,
            'NOMBRE' VALUE J.NOMBRE,
            'APELLIDO_PATERNO' VALUE J.APELLIDO_PATERNO,
            'APELLIDO_MATERNO' VALUE J.APELLIDO_MATERNO,
            'DORSAL' VALUE J.DORSAL,
            'PARTIDOS_JUGADOS' VALUE J.PARTIDOS_JUGADOS,
            'LESIONES' VALUE J.LESIONES,
            'POSICIONES' VALUE J.POSICIONES RETURNING CLOB
        ) AS ITEM
        FROM FIDE_JUGADORES_BUSQUEDA_CONSULTA_V J
        WHERE J.ID_ESTADO = 1
          AND (P_NOMBRE IS NULL OR UPPER(J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO) LIKE '%' || UPPER(P_NOMBRE) || '%')
          AND (P_ID_CATEGORIA IS NULL OR J.ID_CATEGORIA = P_ID_CATEGORIA)
          AND (P_CEDULA IS NULL OR UPPER(J.CEDULA) LIKE '%' || UPPER(P_CEDULA) || '%')
          AND (P_ID_POSICION IS NULL OR EXISTS (
              SELECT 1
              FROM FIDE_JUGADOR_POSICIONES_TB JP
              WHERE JP.ID_JUGADOR = J.ID_JUGADOR
                AND JP.ID_POSICION = P_ID_POSICION
                AND JP.ID_ESTADO = 1
          ))
        ORDER BY J.APELLIDO_PATERNO, J.NOMBRE;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR DATO IN C_DATOS LOOP
        FIDE_JSON_AGREGAR(V_JSON, DATO.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_JUGADORES_BUSCAR_FN;

FUNCTION FIDE_CONSULTAS_JUGADOR_RESUMEN_FN(
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
) RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_DATOS IS
        SELECT JSON_OBJECT(
            'ID_JUGADOR' VALUE J.ID_JUGADOR,
            'CEDULA' VALUE J.CEDULA,
            'ID_CATEGORIA' VALUE J.ID_CATEGORIA,
            'NOMBRE_CATEGORIA' VALUE J.NOMBRE_CATEGORIA,
            'NOMBRE' VALUE J.NOMBRE,
            'APELLIDO_PATERNO' VALUE J.APELLIDO_PATERNO,
            'APELLIDO_MATERNO' VALUE J.APELLIDO_MATERNO,
            'DORSAL' VALUE J.DORSAL,
            'DORSAL_FUNCION' VALUE J.DORSAL,
            'FECHA_NACIMIENTO' VALUE J.FECHA_NACIMIENTO,
            'POSICIONES' VALUE J.POSICIONES,
            'GOLES' VALUE J.GOLES,
            'ASISTENCIAS' VALUE J.ASISTENCIAS,
            'PASES_TOTALES' VALUE J.PASES_TOTALES,
            'PASES_EXITOSOS_TOTALES' VALUE J.PASES_EXITOSOS_TOTALES,
            'REGATES_TOTALES' VALUE J.REGATES_TOTALES,
            'REGATES_EXITOSOS_TOTALES' VALUE J.REGATES_EXITOSOS_TOTALES,
            'TIROS_TOTALES' VALUE J.TIROS_TOTALES,
            'TIROS_EXITOSOS_TOTALES' VALUE J.TIROS_EXITOSOS_TOTALES,
            'ENTRADAS_TOTALES' VALUE J.ENTRADAS_TOTALES,
            'ENTRADAS_EXITOSAS_TOTALES' VALUE J.ENTRADAS_EXITOSAS_TOTALES,
            'MINUTOS_TOTALES' VALUE J.MINUTOS_TOTALES,
            'PROMEDIO_PASES_EXITOSOS' VALUE J.PROMEDIO_PASES_EXITOSOS,
            'PROMEDIO_REGATES_EXITOSOS' VALUE J.PROMEDIO_REGATES_EXITOSOS,
            'PROMEDIO_TIROS_EXITOSOS' VALUE J.PROMEDIO_TIROS_EXITOSOS,
            'PROMEDIO_ENTRADAS_EXITOSAS' VALUE J.PROMEDIO_ENTRADAS_EXITOSAS,
            'TARJETAS' VALUE J.TARJETAS,
            'TARJETAS_AMARILLAS' VALUE J.TARJETAS_AMARILLAS,
            'TARJETAS_ROJAS' VALUE J.TARJETAS_ROJAS,
            'MONTO_PAGADO' VALUE J.MONTO_PAGADO,
            'LESIONES' VALUE J.LESIONES,
            'PROMEDIO_MINUTOS' VALUE J.PROMEDIO_MINUTOS,
            'PARTIDOS_JUGADOS' VALUE J.PARTIDOS_JUGADOS,
            'PARTIDOS_GANADOS' VALUE J.PARTIDOS_GANADOS,
            'PARTIDOS_PERDIDOS' VALUE J.PARTIDOS_PERDIDOS
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_JUGADORES_PERFIL_CONSULTA_V J
        WHERE J.ID_JUGADOR = P_ID_JUGADOR
          AND J.ID_ESTADO = 1;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR DATO IN C_DATOS LOOP
        FIDE_JSON_AGREGAR(V_JSON, DATO.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_JUGADOR_RESUMEN_FN;

