/*
    Consultas deportivas simplificadas.

    Primero se crean las vistas. Despues se agregan las declaraciones de la
    seccion PACKAGE SPEC y los cuerpos de la seccion PACKAGE BODY al paquete
    FIDE_PROYECTOFINALACADEMIALEIVA_PCK existente.

    Las funciones solo filtran una vista y recorren un cursor explicito. Los
    calculos repetidos quedan centralizados en las vistas.
*/

/* ============================ VISTAS ============================ */

CREATE OR REPLACE FORCE VIEW FIDE_JUGADORES_BUSQUEDA_CONSULTA_V AS
SELECT
    J.ID_JUGADOR,
    J.CEDULA,
    J.ID_CATEGORIA,
    C.NOMBRE_CATEGORIA,
    J.NOMBRE,
    J.APELLIDO_PATERNO,
    J.APELLIDO_MATERNO,
    J.DORSAL,
    J.ID_ESTADO,
    NVL(POS.POSICIONES, 'Sin posicion') AS POSICIONES,
    NVL(PAR.PARTIDOS_JUGADOS, 0) AS PARTIDOS_JUGADOS,
    NVL(LES.LESIONES, 0) AS LESIONES
FROM FIDE_JUGADORES_TB J
LEFT JOIN FIDE_CATEGORIAS_TB C ON C.ID_CATEGORIA = J.ID_CATEGORIA
LEFT JOIN (
    SELECT JP.ID_JUGADOR,
           LISTAGG(P.NOMBRE_POSICION, ', ') WITHIN GROUP (ORDER BY P.NOMBRE_POSICION) AS POSICIONES
    FROM FIDE_JUGADOR_POSICIONES_TB JP
    JOIN FIDE_POSICIONES_TB P ON P.ID_POSICION = JP.ID_POSICION
    WHERE JP.ID_ESTADO = 1
      AND P.ID_ESTADO = 1
    GROUP BY JP.ID_JUGADOR
) POS ON POS.ID_JUGADOR = J.ID_JUGADOR
LEFT JOIN (
    SELECT A.ID_JUGADOR, COUNT(DISTINCT A.ID_PARTIDO) AS PARTIDOS_JUGADOS
    FROM FIDE_ASISTENCIA_TB A
    WHERE A.ID_ESTADO = 1
    GROUP BY A.ID_JUGADOR
) PAR ON PAR.ID_JUGADOR = J.ID_JUGADOR
LEFT JOIN (
    SELECT PM.ID_JUGADOR, COUNT(DISTINCT L.ID_LESION) AS LESIONES
    FROM FIDE_PARTE_MEDICO_TB PM
    JOIN FIDE_LESIONES_TB L ON L.ID_PARTEMEDICO = PM.ID_PARTEMEDICO
    WHERE PM.ID_ESTADO = 1
      AND L.ID_ESTADO = 1
    GROUP BY PM.ID_JUGADOR
) LES ON LES.ID_JUGADOR = J.ID_JUGADOR;

CREATE OR REPLACE FORCE VIEW FIDE_JUGADORES_RENDIMIENTO_CONSULTA_V AS
SELECT
    J.ID_JUGADOR,
    J.CEDULA,
    J.NOMBRE,
    J.APELLIDO_PATERNO,
    J.APELLIDO_MATERNO,
    C.NOMBRE_CATEGORIA,
    NVL(COUNT(DISTINCT E.ID_PARTIDO), 0) AS PARTIDOS_JUGADOS,
    NVL(SUM(E.GOLES), 0) AS GOLES,
    NVL(SUM(E.ASISTENCIAS), 0) AS ASISTENCIAS,
    NVL(ROUND(AVG(E.PASES_EXITOSOS), 2), 0) AS PROMEDIO_PASES_EXITOSOS,
    NVL(ROUND(AVG(E.ENTRADAS_EXITOSAS), 2), 0) AS PROMEDIO_ENTRADAS_EXITOSAS,
    NVL(ROUND(AVG(E.MINUTOS_JUGADOS), 2), 0) AS PROMEDIO_MINUTOS
FROM FIDE_JUGADORES_TB J
LEFT JOIN FIDE_CATEGORIAS_TB C ON C.ID_CATEGORIA = J.ID_CATEGORIA
LEFT JOIN FIDE_ESTADISTICA_JUGADOR_TB E
    ON E.ID_JUGADOR = J.ID_JUGADOR
   AND E.ID_ESTADO = 1
WHERE J.ID_ESTADO = 1
GROUP BY J.ID_JUGADOR, J.CEDULA, J.NOMBRE, J.APELLIDO_PATERNO,
         J.APELLIDO_MATERNO, C.NOMBRE_CATEGORIA;

CREATE OR REPLACE FORCE VIEW FIDE_JUGADORES_PERFIL_CONSULTA_V AS
SELECT
    B.ID_JUGADOR,
    B.CEDULA,
    B.ID_CATEGORIA,
    B.NOMBRE_CATEGORIA,
    B.NOMBRE,
    B.APELLIDO_PATERNO,
    B.APELLIDO_MATERNO,
    B.DORSAL,
    B.ID_ESTADO,
    J.FECHA_NACIMIENTO,
    B.POSICIONES,
    NVL(S.GOLES, 0) AS GOLES,
    NVL(S.ASISTENCIAS, 0) AS ASISTENCIAS,
    NVL(S.PASES_TOTALES, 0) AS PASES_TOTALES,
    NVL(S.PASES_EXITOSOS_TOTALES, 0) AS PASES_EXITOSOS_TOTALES,
    NVL(S.REGATES_TOTALES, 0) AS REGATES_TOTALES,
    NVL(S.REGATES_EXITOSOS_TOTALES, 0) AS REGATES_EXITOSOS_TOTALES,
    NVL(S.TIROS_TOTALES, 0) AS TIROS_TOTALES,
    NVL(S.TIROS_EXITOSOS_TOTALES, 0) AS TIROS_EXITOSOS_TOTALES,
    NVL(S.ENTRADAS_TOTALES, 0) AS ENTRADAS_TOTALES,
    NVL(S.ENTRADAS_EXITOSAS_TOTALES, 0) AS ENTRADAS_EXITOSAS_TOTALES,
    NVL(S.MINUTOS_TOTALES, 0) AS MINUTOS_TOTALES,
    NVL(S.PROMEDIO_PASES_EXITOSOS, 0) AS PROMEDIO_PASES_EXITOSOS,
    NVL(S.PROMEDIO_REGATES_EXITOSOS, 0) AS PROMEDIO_REGATES_EXITOSOS,
    NVL(S.PROMEDIO_TIROS_EXITOSOS, 0) AS PROMEDIO_TIROS_EXITOSOS,
    NVL(S.PROMEDIO_ENTRADAS_EXITOSAS, 0) AS PROMEDIO_ENTRADAS_EXITOSAS,
    NVL(S.PROMEDIO_MINUTOS, 0) AS PROMEDIO_MINUTOS,
    NVL(T.TARJETAS, 0) AS TARJETAS,
    NVL(T.TARJETAS_AMARILLAS, 0) AS TARJETAS_AMARILLAS,
    NVL(T.TARJETAS_ROJAS, 0) AS TARJETAS_ROJAS,
    NVL(A.PARTIDOS_GANADOS, 0) AS PARTIDOS_GANADOS,
    NVL(A.PARTIDOS_PERDIDOS, 0) AS PARTIDOS_PERDIDOS,
    B.PARTIDOS_JUGADOS,
    B.LESIONES,
    FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_FACTURACION_TB_MONTO_PAGADO_JUGADOR_FN(B.ID_JUGADOR) AS MONTO_PAGADO
FROM FIDE_JUGADORES_BUSQUEDA_CONSULTA_V B
JOIN FIDE_JUGADORES_TB J ON J.ID_JUGADOR = B.ID_JUGADOR
LEFT JOIN (
    SELECT E.ID_JUGADOR,
           SUM(E.GOLES) AS GOLES,
           SUM(E.ASISTENCIAS) AS ASISTENCIAS,
           SUM(E.PASES) AS PASES_TOTALES,
           SUM(E.PASES_EXITOSOS) AS PASES_EXITOSOS_TOTALES,
           SUM(E.REGATES) AS REGATES_TOTALES,
           SUM(E.REGATES_EXITOSOS) AS REGATES_EXITOSOS_TOTALES,
           SUM(E.TIROS) AS TIROS_TOTALES,
           SUM(E.TIROS_EXITOSOS) AS TIROS_EXITOSOS_TOTALES,
           SUM(E.ENTRADAS) AS ENTRADAS_TOTALES,
           SUM(E.ENTRADAS_EXITOSAS) AS ENTRADAS_EXITOSAS_TOTALES,
           SUM(E.MINUTOS_JUGADOS) AS MINUTOS_TOTALES,
           ROUND(AVG(E.PASES_EXITOSOS), 2) AS PROMEDIO_PASES_EXITOSOS,
           ROUND(AVG(E.REGATES_EXITOSOS), 2) AS PROMEDIO_REGATES_EXITOSOS,
           ROUND(AVG(E.TIROS_EXITOSOS), 2) AS PROMEDIO_TIROS_EXITOSOS,
           ROUND(AVG(E.ENTRADAS_EXITOSAS), 2) AS PROMEDIO_ENTRADAS_EXITOSAS,
           ROUND(AVG(E.MINUTOS_JUGADOS), 2) AS PROMEDIO_MINUTOS
    FROM FIDE_ESTADISTICA_JUGADOR_TB E
    WHERE E.ID_ESTADO = 1
    GROUP BY E.ID_JUGADOR
) S ON S.ID_JUGADOR = B.ID_JUGADOR
LEFT JOIN (
    SELECT CT.ID_JUGADOR,
           SUM(CT.CANTIDAD_TARJETAS) AS TARJETAS,
           SUM(CASE WHEN UPPER(TT.COLOR) LIKE '%AMARILL%' THEN CT.CANTIDAD_TARJETAS ELSE 0 END) AS TARJETAS_AMARILLAS,
           SUM(CASE WHEN UPPER(TT.COLOR) LIKE '%ROJ%' THEN CT.CANTIDAD_TARJETAS ELSE 0 END) AS TARJETAS_ROJAS
    FROM FIDE_TARJETAS_TB CT
    JOIN FIDE_TIPOTARJETAS_TB TT ON TT.ID_TIPOTARJETA = CT.ID_TIPOTARJETA
    WHERE CT.ID_ESTADO = 1
    GROUP BY CT.ID_JUGADOR
) T ON T.ID_JUGADOR = B.ID_JUGADOR
LEFT JOIN (
    SELECT A.ID_JUGADOR,
           SUM(CASE WHEN P.GOLES_FAVOR > P.GOLES_CONTRA THEN 1 ELSE 0 END) AS PARTIDOS_GANADOS,
           SUM(CASE WHEN P.GOLES_FAVOR < P.GOLES_CONTRA THEN 1 ELSE 0 END) AS PARTIDOS_PERDIDOS
    FROM FIDE_ASISTENCIA_TB A
    JOIN FIDE_PARTIDOS_TB P ON P.ID_PARTIDO = A.ID_PARTIDO
    WHERE A.ID_ESTADO = 1
      AND P.ID_ESTADO = 1
    GROUP BY A.ID_JUGADOR
) A ON A.ID_JUGADOR = B.ID_JUGADOR;

CREATE OR REPLACE FORCE VIEW FIDE_PARTIDOS_RESUMEN_CONSULTA_V AS
SELECT
    P.ID_PARTIDO,
    P.ID_CATEGORIA,
    C.NOMBRE_CATEGORIA,
    P.ID_TEMPORADA,
    T.TIPO_TEMPORADA,
    T.ANIO AS TEMPORADA_ANIO,
    P.FECHA,
    P.RIVAL,
    P.GOLES_FAVOR,
    P.GOLES_CONTRA,
    CASE WHEN P.GOLES_FAVOR > P.GOLES_CONTRA THEN 'ganado'
         WHEN P.GOLES_FAVOR < P.GOLES_CONTRA THEN 'perdido'
         ELSE 'empate' END AS RESULTADO,
    NVL(E.TIROS, 0) AS TIROS,
    NVL(E.TIROS_PORTERIA, 0) AS TIROS_PORTERIA,
    NVL(E.PASES_EXITOSOS, 0) AS PASES_EXITOSOS,
    NVL(E.PASES_FALLIDOS, 0) AS PASES_FALLIDOS,
    NVL(E.POSESION_BALON, 0) AS POSESION_BALON,
    NVL(A.TOTAL_ASISTENCIA, 0) AS TOTAL_ASISTENCIA,
    P.ID_ESTADO
FROM FIDE_PARTIDOS_TB P
LEFT JOIN FIDE_CATEGORIAS_TB C ON C.ID_CATEGORIA = P.ID_CATEGORIA
LEFT JOIN FIDE_TEMPORADAS_TB T ON T.ID_TEMPORADA = P.ID_TEMPORADA
LEFT JOIN (
    SELECT ID_PARTIDO,
           SUM(TIROS) AS TIROS,
           SUM(TIROS_PORTERIA) AS TIROS_PORTERIA,
           SUM(PASES_EXITOSOS) AS PASES_EXITOSOS,
           SUM(PASES_FALLIDOS) AS PASES_FALLIDOS,
           MAX(POSESION_BALON) AS POSESION_BALON
    FROM FIDE_ESTADISTICA_EQUIPO_TB
    WHERE ID_ESTADO = 1
    GROUP BY ID_PARTIDO
) E ON E.ID_PARTIDO = P.ID_PARTIDO
LEFT JOIN (
    SELECT ID_PARTIDO, COUNT(*) AS TOTAL_ASISTENCIA
    FROM FIDE_ASISTENCIA_TB
    WHERE ID_ESTADO = 1
    GROUP BY ID_PARTIDO
) A ON A.ID_PARTIDO = P.ID_PARTIDO;

CREATE OR REPLACE FORCE VIEW FIDE_PARTICIPACION_CONSULTA_V AS
SELECT
    A.ID_JUGADOR,
    A.ID_PARTIDO,
    J.NOMBRE,
    J.APELLIDO_PATERNO,
    J.APELLIDO_MATERNO,
    C.NOMBRE_CATEGORIA,
    P.FECHA,
    P.RIVAL,
    P.GOLES_FAVOR,
    P.GOLES_CONTRA,
    CASE WHEN P.GOLES_FAVOR > P.GOLES_CONTRA THEN 'ganado'
         WHEN P.GOLES_FAVOR < P.GOLES_CONTRA THEN 'perdido'
         ELSE 'empate' END AS RESULTADO,
    NVL(E.PASES, 0) AS PASES,
    NVL(E.PASES_EXITOSOS, 0) AS PASES_EXITOSOS,
    NVL(E.REGATES, 0) AS REGATES,
    NVL(E.REGATES_EXITOSOS, 0) AS REGATES_EXITOSOS,
    NVL(E.TIROS, 0) AS TIROS,
    NVL(E.TIROS_EXITOSOS, 0) AS TIROS_EXITOSOS,
    NVL(E.ENTRADAS, 0) AS ENTRADAS,
    NVL(E.ENTRADAS_EXITOSAS, 0) AS ENTRADAS_EXITOSAS,
    NVL(E.MINUTOS_JUGADOS, 0) AS MINUTOS_JUGADOS,
    NVL(E.GOLES, 0) AS GOLES,
    NVL(E.ASISTENCIAS, 0) AS ASISTENCIAS,
    NVL(POS.POSICIONES, 'Sin posicion') AS POSICIONES
FROM FIDE_ASISTENCIA_TB A
JOIN FIDE_JUGADORES_TB J ON J.ID_JUGADOR = A.ID_JUGADOR
JOIN FIDE_PARTIDOS_TB P ON P.ID_PARTIDO = A.ID_PARTIDO
LEFT JOIN FIDE_CATEGORIAS_TB C ON C.ID_CATEGORIA = P.ID_CATEGORIA
LEFT JOIN FIDE_ESTADISTICA_JUGADOR_TB E
    ON E.ID_JUGADOR = A.ID_JUGADOR
   AND E.ID_PARTIDO = A.ID_PARTIDO
   AND E.ID_ESTADO = 1
LEFT JOIN (
    SELECT JP.ID_JUGADOR,
           LISTAGG(PS.NOMBRE_POSICION, ', ') WITHIN GROUP (ORDER BY PS.NOMBRE_POSICION) AS POSICIONES
    FROM FIDE_JUGADOR_POSICIONES_TB JP
    JOIN FIDE_POSICIONES_TB PS ON PS.ID_POSICION = JP.ID_POSICION
    WHERE JP.ID_ESTADO = 1
      AND PS.ID_ESTADO = 1
    GROUP BY JP.ID_JUGADOR
) POS ON POS.ID_JUGADOR = A.ID_JUGADOR
WHERE A.ID_ESTADO = 1
  AND J.ID_ESTADO = 1
  AND P.ID_ESTADO = 1;

CREATE OR REPLACE FORCE VIEW FIDE_DISPONIBILIDAD_CONSULTA_V AS
SELECT
    J.ID_JUGADOR,
    J.ID_CATEGORIA,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO AS NOMBRE_COMPLETO,
    C.NOMBRE_CATEGORIA,
    NVL(L.LESIONES_ACTIVAS, 0) AS LESIONES,
    NVL(T.TARJETAS_AMARILLAS, 0) AS TARJETAS_AMARILLAS,
    NVL(T.TARJETAS_ROJAS, 0) AS TARJETAS_ROJAS,
    CASE WHEN NVL(L.LESIONES_ACTIVAS, 0) > 0 THEN 'LESIONADO'
         WHEN NVL(T.TARJETAS_ROJAS, 0) > 0 THEN 'SUSPENDIDO'
         ELSE 'DISPONIBLE' END AS ESTADO
FROM FIDE_JUGADORES_TB J
LEFT JOIN FIDE_CATEGORIAS_TB C ON C.ID_CATEGORIA = J.ID_CATEGORIA
LEFT JOIN (
    SELECT PM.ID_JUGADOR, COUNT(DISTINCT L.ID_LESION) AS LESIONES_ACTIVAS
    FROM FIDE_PARTE_MEDICO_TB PM
    JOIN FIDE_LESIONES_TB L ON L.ID_PARTEMEDICO = PM.ID_PARTEMEDICO
    WHERE PM.ID_ESTADO = 1
      AND L.ID_ESTADO = 1
      AND (L.FECHA_RECUPERACION IS NULL OR L.FECHA_RECUPERACION >= TRUNC(SYSDATE))
    GROUP BY PM.ID_JUGADOR
) L ON L.ID_JUGADOR = J.ID_JUGADOR
LEFT JOIN (
    SELECT CT.ID_JUGADOR,
           SUM(CASE WHEN UPPER(TT.COLOR) LIKE '%AMARILL%' THEN CT.CANTIDAD_TARJETAS ELSE 0 END) AS TARJETAS_AMARILLAS,
           SUM(CASE WHEN UPPER(TT.COLOR) LIKE '%ROJ%' THEN CT.CANTIDAD_TARJETAS ELSE 0 END) AS TARJETAS_ROJAS
    FROM FIDE_TARJETAS_TB CT
    JOIN FIDE_TIPOTARJETAS_TB TT ON TT.ID_TIPOTARJETA = CT.ID_TIPOTARJETA
    WHERE CT.ID_ESTADO = 1
    GROUP BY CT.ID_JUGADOR
) T ON T.ID_JUGADOR = J.ID_JUGADOR
WHERE J.ID_ESTADO = 1;

CREATE OR REPLACE FORCE VIEW FIDE_JUGADOR_LESIONES_CONSULTA_V AS
SELECT
    PM.ID_JUGADOR,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO AS NOMBRE_COMPLETO,
    PM.FECHA,
    L.DESCRIPCION,
    PM.OBSERVACIONES,
    L.FECHA_RECUPERACION,
    CASE WHEN L.FECHA_RECUPERACION IS NULL OR L.FECHA_RECUPERACION >= TRUNC(SYSDATE) THEN 'ACTIVA'
         ELSE 'RECUPERADA' END AS ESTADO
FROM FIDE_PARTE_MEDICO_TB PM
JOIN FIDE_LESIONES_TB L ON L.ID_PARTEMEDICO = PM.ID_PARTEMEDICO
JOIN FIDE_JUGADORES_TB J ON J.ID_JUGADOR = PM.ID_JUGADOR
WHERE PM.ID_ESTADO = 1
  AND L.ID_ESTADO = 1;

CREATE OR REPLACE FORCE VIEW FIDE_JUGADORES_TEMPORADA_CONSULTA_V AS
SELECT
    E.ID_JUGADOR,
    E.ID_PARTIDO,
    P.ID_TEMPORADA,
    P.ID_CATEGORIA,
    J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO AS NOMBRE_COMPLETO,
    E.GOLES,
    E.ASISTENCIAS
FROM FIDE_ESTADISTICA_JUGADOR_TB E
JOIN FIDE_JUGADORES_TB J ON J.ID_JUGADOR = E.ID_JUGADOR
JOIN FIDE_PARTIDOS_TB P ON P.ID_PARTIDO = E.ID_PARTIDO
WHERE E.ID_ESTADO = 1
  AND J.ID_ESTADO = 1
  AND P.ID_ESTADO = 1;

/* ============================ PACKAGE SPEC ============================ */

FUNCTION FIDE_CONSULTAS_DASHBOARD_FN(
    P_ID_TEMPORADA IN FIDE_TEMPORADAS_TB.ID_TEMPORADA%TYPE,
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE
) RETURN CLOB;

FUNCTION FIDE_CONSULTAS_JUGADORES_COMPARAR_FN(
    P_ID_JUGADOR_1 IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE,
    P_ID_JUGADOR_2 IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE,
    P_ID_JUGADOR_3 IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
) RETURN CLOB;

FUNCTION FIDE_CONSULTAS_PARTIDO_DETALLE_FN(
    P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE
) RETURN CLOB;

FUNCTION FIDE_CONSULTAS_PARTIDO_JUGADORES_FN(
    P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE
) RETURN CLOB;

FUNCTION FIDE_CONSULTAS_JUGADOR_PARTIDO_FN(
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE,
    P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE
) RETURN CLOB;

FUNCTION FIDE_CONSULTAS_DISPONIBILIDAD_FN(
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE
) RETURN CLOB;

FUNCTION FIDE_CONSULTAS_JUGADOR_LESIONES_FN(
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
) RETURN CLOB;

FUNCTION FIDE_CONSULTAS_JUGADOR_PARTIDOS_FN(
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
) RETURN CLOB;

/* ============================ PACKAGE BODY ============================ */

FUNCTION FIDE_CONSULTAS_DASHBOARD_FN(
    P_ID_TEMPORADA IN FIDE_TEMPORADAS_TB.ID_TEMPORADA%TYPE,
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE
) RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_DASHBOARD IS
        SELECT JSON_OBJECT(
            'TOTAL_JUGADORES' VALUE (SELECT COUNT(*) FROM FIDE_JUGADORES_BUSQUEDA_CONSULTA_V J WHERE J.ID_ESTADO = 1 AND (P_ID_CATEGORIA IS NULL OR J.ID_CATEGORIA = P_ID_CATEGORIA)),
            'TOTAL_PARTIDOS' VALUE COUNT(*),
            'PARTIDOS_GANADOS' VALUE NVL(SUM(CASE WHEN R.RESULTADO = 'ganado' THEN 1 ELSE 0 END), 0),
            'GOLES_FAVOR' VALUE NVL(SUM(R.GOLES_FAVOR), 0),
            'TOTAL_ASISTENCIAS' VALUE NVL((SELECT SUM(E.ASISTENCIAS) FROM FIDE_JUGADORES_TEMPORADA_CONSULTA_V E WHERE (P_ID_TEMPORADA IS NULL OR E.ID_TEMPORADA = P_ID_TEMPORADA) AND (P_ID_CATEGORIA IS NULL OR E.ID_CATEGORIA = P_ID_CATEGORIA)), 0),
            'TOTAL_LESIONES' VALUE NVL((SELECT SUM(D.LESIONES) FROM FIDE_DISPONIBILIDAD_CONSULTA_V D WHERE P_ID_CATEGORIA IS NULL OR D.ID_CATEGORIA = P_ID_CATEGORIA), 0),
            'TOTAL_DISPONIBLES' VALUE NVL((SELECT COUNT(*) FROM FIDE_DISPONIBILIDAD_CONSULTA_V D WHERE D.ESTADO = 'DISPONIBLE' AND (P_ID_CATEGORIA IS NULL OR D.ID_CATEGORIA = P_ID_CATEGORIA)), 0),
            'TOP_GOLEADOR_NOMBRE' VALUE (SELECT MAX(X.NOMBRE_COMPLETO) KEEP (DENSE_RANK FIRST ORDER BY X.GOLES DESC) FROM (SELECT E.NOMBRE_COMPLETO, SUM(E.GOLES) AS GOLES FROM FIDE_JUGADORES_TEMPORADA_CONSULTA_V E WHERE (P_ID_TEMPORADA IS NULL OR E.ID_TEMPORADA = P_ID_TEMPORADA) AND (P_ID_CATEGORIA IS NULL OR E.ID_CATEGORIA = P_ID_CATEGORIA) GROUP BY E.ID_JUGADOR, E.NOMBRE_COMPLETO) X),
            'TOP_GOLEADOR_GOLES' VALUE NVL((SELECT MAX(X.GOLES) FROM (SELECT SUM(E.GOLES) AS GOLES FROM FIDE_JUGADORES_TEMPORADA_CONSULTA_V E WHERE (P_ID_TEMPORADA IS NULL OR E.ID_TEMPORADA = P_ID_TEMPORADA) AND (P_ID_CATEGORIA IS NULL OR E.ID_CATEGORIA = P_ID_CATEGORIA) GROUP BY E.ID_JUGADOR) X), 0),
            'TOP_ASISTENTE_NOMBRE' VALUE (SELECT MAX(X.NOMBRE_COMPLETO) KEEP (DENSE_RANK FIRST ORDER BY X.ASISTENCIAS DESC) FROM (SELECT E.NOMBRE_COMPLETO, SUM(E.ASISTENCIAS) AS ASISTENCIAS FROM FIDE_JUGADORES_TEMPORADA_CONSULTA_V E WHERE (P_ID_TEMPORADA IS NULL OR E.ID_TEMPORADA = P_ID_TEMPORADA) AND (P_ID_CATEGORIA IS NULL OR E.ID_CATEGORIA = P_ID_CATEGORIA) GROUP BY E.ID_JUGADOR, E.NOMBRE_COMPLETO) X),
            'TOP_ASISTENTE_ASISTENCIAS' VALUE NVL((SELECT MAX(X.ASISTENCIAS) FROM (SELECT SUM(E.ASISTENCIAS) AS ASISTENCIAS FROM FIDE_JUGADORES_TEMPORADA_CONSULTA_V E WHERE (P_ID_TEMPORADA IS NULL OR E.ID_TEMPORADA = P_ID_TEMPORADA) AND (P_ID_CATEGORIA IS NULL OR E.ID_CATEGORIA = P_ID_CATEGORIA) GROUP BY E.ID_JUGADOR) X), 0)
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_PARTIDOS_RESUMEN_CONSULTA_V R
        WHERE R.ID_ESTADO = 1
          AND (P_ID_TEMPORADA IS NULL OR R.ID_TEMPORADA = P_ID_TEMPORADA)
          AND (P_ID_CATEGORIA IS NULL OR R.ID_CATEGORIA = P_ID_CATEGORIA);
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR D IN C_DASHBOARD LOOP
        FIDE_JSON_AGREGAR(V_JSON, D.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_DASHBOARD_FN;

FUNCTION FIDE_CONSULTAS_JUGADORES_COMPARAR_FN(
    P_ID_JUGADOR_1 IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE,
    P_ID_JUGADOR_2 IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE,
    P_ID_JUGADOR_3 IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
) RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_JUGADORES IS
        SELECT JSON_OBJECT(
            'ID_JUGADOR' VALUE J.ID_JUGADOR,
            'NOMBRE' VALUE J.NOMBRE,
            'APELLIDO_PATERNO' VALUE J.APELLIDO_PATERNO,
            'APELLIDO_MATERNO' VALUE J.APELLIDO_MATERNO,
            'NOMBRE_CATEGORIA' VALUE J.NOMBRE_CATEGORIA,
            'PARTIDOS_JUGADOS' VALUE J.PARTIDOS_JUGADOS,
            'GOLES' VALUE J.GOLES,
            'ASISTENCIAS' VALUE J.ASISTENCIAS,
            'PROMEDIO_PASES_EXITOSOS' VALUE J.PROMEDIO_PASES_EXITOSOS,
            'PROMEDIO_ENTRADAS_EXITOSAS' VALUE J.PROMEDIO_ENTRADAS_EXITOSAS,
            'PROMEDIO_MINUTOS' VALUE J.PROMEDIO_MINUTOS
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_JUGADORES_RENDIMIENTO_CONSULTA_V J
        WHERE J.ID_JUGADOR IN (P_ID_JUGADOR_1, P_ID_JUGADOR_2, P_ID_JUGADOR_3)
        ORDER BY J.APELLIDO_PATERNO, J.NOMBRE;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR JUGADOR IN C_JUGADORES LOOP
        FIDE_JSON_AGREGAR(V_JSON, JUGADOR.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_JUGADORES_COMPARAR_FN;

FUNCTION FIDE_CONSULTAS_PARTIDO_DETALLE_FN(
    P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE
) RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_PARTIDO IS
        SELECT JSON_OBJECT(
            'ID_PARTIDO' VALUE R.ID_PARTIDO,
            'NOMBRE_CATEGORIA' VALUE R.NOMBRE_CATEGORIA,
            'TIPO_TEMPORADA' VALUE R.TIPO_TEMPORADA,
            'TEMPORADA_ANIO' VALUE R.TEMPORADA_ANIO,
            'FECHA' VALUE R.FECHA,
            'RIVAL' VALUE R.RIVAL,
            'GOLES_FAVOR' VALUE R.GOLES_FAVOR,
            'GOLES_CONTRA' VALUE R.GOLES_CONTRA,
            'RESULTADO' VALUE R.RESULTADO,
            'TIROS' VALUE R.TIROS,
            'TIROS_PORTERIA' VALUE R.TIROS_PORTERIA,
            'PASES_EXITOSOS' VALUE R.PASES_EXITOSOS,
            'PASES_FALLIDOS' VALUE R.PASES_FALLIDOS,
            'POSESION_BALON' VALUE R.POSESION_BALON,
            'TOTAL_ASISTENCIA' VALUE R.TOTAL_ASISTENCIA
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_PARTIDOS_RESUMEN_CONSULTA_V R
        WHERE R.ID_PARTIDO = P_ID_PARTIDO
          AND R.ID_ESTADO = 1;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR PARTIDO IN C_PARTIDO LOOP
        FIDE_JSON_AGREGAR(V_JSON, PARTIDO.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_PARTIDO_DETALLE_FN;

FUNCTION FIDE_CONSULTAS_PARTIDO_JUGADORES_FN(
    P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE
) RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_JUGADORES IS
        SELECT JSON_OBJECT(
            'ID_JUGADOR' VALUE J.ID_JUGADOR,
            'ID_PARTIDO' VALUE J.ID_PARTIDO,
            'NOMBRE_COMPLETO' VALUE J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO,
            'POSICIONES' VALUE J.POSICIONES,
            'MINUTOS_JUGADOS' VALUE J.MINUTOS_JUGADOS,
            'GOLES' VALUE J.GOLES,
            'ASISTENCIAS' VALUE J.ASISTENCIAS,
            'PASES_EXITOSOS' VALUE J.PASES_EXITOSOS,
            'ENTRADAS_EXITOSAS' VALUE J.ENTRADAS_EXITOSAS,
            'REGATES_EXITOSOS' VALUE J.REGATES_EXITOSOS,
            'TIROS_EXITOSOS' VALUE J.TIROS_EXITOSOS
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_PARTICIPACION_CONSULTA_V J
        WHERE J.ID_PARTIDO = P_ID_PARTIDO
        ORDER BY J.GOLES DESC, J.ASISTENCIAS DESC, J.APELLIDO_PATERNO;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR JUGADOR IN C_JUGADORES LOOP
        FIDE_JSON_AGREGAR(V_JSON, JUGADOR.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_PARTIDO_JUGADORES_FN;

FUNCTION FIDE_CONSULTAS_JUGADOR_PARTIDO_FN(
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE,
    P_ID_PARTIDO IN FIDE_PARTIDOS_TB.ID_PARTIDO%TYPE
) RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_ESTADISTICA IS
        SELECT JSON_OBJECT(
            'ID_JUGADOR' VALUE J.ID_JUGADOR,
            'ID_PARTIDO' VALUE J.ID_PARTIDO,
            'NOMBRE_COMPLETO' VALUE J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO,
            'NOMBRE_CATEGORIA' VALUE J.NOMBRE_CATEGORIA,
            'FECHA' VALUE J.FECHA,
            'RIVAL' VALUE J.RIVAL,
            'GOLES_FAVOR' VALUE J.GOLES_FAVOR,
            'GOLES_CONTRA' VALUE J.GOLES_CONTRA,
            'RESULTADO' VALUE J.RESULTADO,
            'PASES' VALUE J.PASES,
            'PASES_EXITOSOS' VALUE J.PASES_EXITOSOS,
            'REGATES' VALUE J.REGATES,
            'REGATES_EXITOSOS' VALUE J.REGATES_EXITOSOS,
            'TIROS' VALUE J.TIROS,
            'TIROS_EXITOSOS' VALUE J.TIROS_EXITOSOS,
            'ENTRADAS' VALUE J.ENTRADAS,
            'ENTRADAS_EXITOSAS' VALUE J.ENTRADAS_EXITOSAS,
            'MINUTOS_JUGADOS' VALUE J.MINUTOS_JUGADOS,
            'GOLES' VALUE J.GOLES,
            'ASISTENCIAS' VALUE J.ASISTENCIAS
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_PARTICIPACION_CONSULTA_V J
        WHERE J.ID_JUGADOR = P_ID_JUGADOR
          AND J.ID_PARTIDO = P_ID_PARTIDO;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR ESTADISTICA IN C_ESTADISTICA LOOP
        FIDE_JSON_AGREGAR(V_JSON, ESTADISTICA.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_JUGADOR_PARTIDO_FN;

FUNCTION FIDE_CONSULTAS_DISPONIBILIDAD_FN(
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE
) RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_DISPONIBILIDAD IS
        SELECT JSON_OBJECT(
            'ID_JUGADOR' VALUE D.ID_JUGADOR,
            'ID_CATEGORIA' VALUE D.ID_CATEGORIA,
            'NOMBRE_COMPLETO' VALUE D.NOMBRE_COMPLETO,
            'NOMBRE_CATEGORIA' VALUE D.NOMBRE_CATEGORIA,
            'ESTADO' VALUE D.ESTADO,
            'LESIONES' VALUE D.LESIONES,
            'TARJETAS_AMARILLAS' VALUE D.TARJETAS_AMARILLAS,
            'TARJETAS_ROJAS' VALUE D.TARJETAS_ROJAS
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_DISPONIBILIDAD_CONSULTA_V D
        WHERE P_ID_CATEGORIA IS NULL OR D.ID_CATEGORIA = P_ID_CATEGORIA
        ORDER BY D.NOMBRE_COMPLETO;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR JUGADOR IN C_DISPONIBILIDAD LOOP
        FIDE_JSON_AGREGAR(V_JSON, JUGADOR.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_DISPONIBILIDAD_FN;

FUNCTION FIDE_CONSULTAS_JUGADOR_LESIONES_FN(
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
) RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_LESIONES IS
        SELECT JSON_OBJECT(
            'ID_JUGADOR' VALUE L.ID_JUGADOR,
            'NOMBRE_COMPLETO' VALUE L.NOMBRE_COMPLETO,
            'FECHA' VALUE L.FECHA,
            'DESCRIPCION' VALUE L.DESCRIPCION,
            'OBSERVACIONES' VALUE L.OBSERVACIONES,
            'FECHA_RECUPERACION' VALUE L.FECHA_RECUPERACION,
            'ESTADO' VALUE L.ESTADO
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_JUGADOR_LESIONES_CONSULTA_V L
        WHERE L.ID_JUGADOR = P_ID_JUGADOR
        ORDER BY L.FECHA DESC;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR LESION IN C_LESIONES LOOP
        FIDE_JSON_AGREGAR(V_JSON, LESION.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_JUGADOR_LESIONES_FN;

FUNCTION FIDE_CONSULTAS_JUGADOR_PARTIDOS_FN(
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
) RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_PARTIDOS IS
        SELECT JSON_OBJECT(
            'ID_JUGADOR' VALUE J.ID_JUGADOR,
            'ID_PARTIDO' VALUE J.ID_PARTIDO,
            'NOMBRE_COMPLETO' VALUE J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO,
            'FECHA' VALUE J.FECHA,
            'RIVAL' VALUE J.RIVAL,
            'GOLES_FAVOR' VALUE J.GOLES_FAVOR,
            'GOLES_CONTRA' VALUE J.GOLES_CONTRA,
            'RESULTADO' VALUE J.RESULTADO,
            'MINUTOS_JUGADOS' VALUE J.MINUTOS_JUGADOS,
            'GOLES' VALUE J.GOLES,
            'ASISTENCIAS' VALUE J.ASISTENCIAS
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_PARTICIPACION_CONSULTA_V J
        WHERE J.ID_JUGADOR = P_ID_JUGADOR
        ORDER BY J.FECHA DESC, J.ID_PARTIDO DESC;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);
    FOR PARTIDO IN C_PARTIDOS LOOP
        FIDE_JSON_AGREGAR(V_JSON, PARTIDO.ITEM, V_PRIMER_ITEM);
    END LOOP;
    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN OTHERS THEN
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_JUGADOR_PARTIDOS_FN;
