/*
   Genera la mensualidad pendiente al crear un jugador activo.
   Ejecutar este script en Oracle para reemplazar la versión anterior.
*/

CREATE OR REPLACE PROCEDURE FIDE_FACTURACION_INSCRIPCIONES_TB_CREAR_INICIAL_SP (
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE,
    P_ID_ESTADO  IN FIDE_JUGADORES_TB.ID_ESTADO%TYPE
)
IS
    V_ID_ESTADO_ACTIVO    FIDE_ESTADOS_TB.ID_ESTADO%TYPE;
    V_ID_ESTADO_PENDIENTE FIDE_ESTADOS_TB.ID_ESTADO%TYPE;
BEGIN
    -- IDs fijos del catálogo de estados: 1 = Activo, 9 = Pendiente de pago.
    V_ID_ESTADO_ACTIVO := 1;

    -- Los jugadores inactivos no deben generar mensualidades.
    IF P_ID_ESTADO <> V_ID_ESTADO_ACTIVO THEN
        RETURN;
    END IF;

    V_ID_ESTADO_PENDIENTE := 9;

    /*
       No consulta FIDE_JUGADORES_TB: el procedimiento se ejecuta desde un
       trigger sobre esa tabla y consultarla causaría el error ORA-04091.
    */
    INSERT INTO FIDE_FACTURACION_INSCRIPCIONES_TB (
        ID_JUGADOR,
        MES,
        ANIO,
        MONTO,
        FECHA_PAGO,
        ID_ESTADO,
        OBSERVACIONES
    )
    SELECT
        P_ID_JUGADOR,
        EXTRACT(MONTH FROM SYSDATE),
        EXTRACT(YEAR FROM SYSDATE),
        10000,
        NULL,
        V_ID_ESTADO_PENDIENTE,
        'MENSUALIDAD GENERADA AL INSCRIBIR EL JUGADOR'
    FROM DUAL
    WHERE NOT EXISTS (
        SELECT 1
        FROM FIDE_FACTURACION_INSCRIPCIONES_TB F
        WHERE F.ID_JUGADOR = P_ID_JUGADOR
          AND F.MES = EXTRACT(MONTH FROM SYSDATE)
          AND F.ANIO = EXTRACT(YEAR FROM SYSDATE)
    );
END FIDE_FACTURACION_INSCRIPCIONES_TB_CREAR_INICIAL_SP;
/

CREATE OR REPLACE TRIGGER FIDE_JUGADORES_TB_FACTURA_INICIAL_TRG
AFTER INSERT ON FIDE_JUGADORES_TB
FOR EACH ROW
BEGIN
    FIDE_FACTURACION_INSCRIPCIONES_TB_CREAR_INICIAL_SP(
        :NEW.ID_JUGADOR,
        :NEW.ID_ESTADO
    );
END FIDE_JUGADORES_TB_FACTURA_INICIAL_TRG;
/
