
PROCEDURE FIDE_JSON_INICIAR(P_JSON OUT CLOB) IS
BEGIN
    DBMS_LOB.CREATETEMPORARY(P_JSON, TRUE);
    DBMS_LOB.WRITEAPPEND(P_JSON, 1, '[');
END FIDE_JSON_INICIAR;

PROCEDURE FIDE_JSON_AGREGAR(
    P_JSON IN OUT NOCOPY CLOB,
    P_ITEM IN CLOB,
    P_PRIMER_ITEM IN OUT BOOLEAN
) IS
BEGIN
    IF NOT P_PRIMER_ITEM THEN
        DBMS_LOB.WRITEAPPEND(P_JSON, 1, ',');
    END IF;

    DBMS_LOB.APPEND(P_JSON, P_ITEM);
    P_PRIMER_ITEM := FALSE;
END FIDE_JSON_AGREGAR;

PROCEDURE FIDE_JSON_CERRAR(P_JSON IN OUT NOCOPY CLOB) IS
BEGIN
    DBMS_LOB.WRITEAPPEND(P_JSON, 1, ']');
END FIDE_JSON_CERRAR;

FUNCTION FIDE_CONSULTAS_TEMPORADAS_LISTAR_FN
RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_TEMPORADAS IS
        SELECT JSON_OBJECT(
            'ID_TEMPORADA' VALUE ID_TEMPORADA,
            'TIPO_TEMPORADA' VALUE TIPO_TEMPORADA,
            'ANIO' VALUE ANIO
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_TEMPORADAS_V
        WHERE ID_ESTADO = 1
        ORDER BY ANIO DESC;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);

    FOR TEMP IN C_TEMPORADAS LOOP
        FIDE_JSON_AGREGAR(V_JSON, TEMP.ITEM, V_PRIMER_ITEM);
    END LOOP;

    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN TO_CLOB('[]');
    WHEN TOO_MANY_ROWS THEN
        RETURN TO_CLOB('[]');
    WHEN VALUE_ERROR THEN
        RETURN TO_CLOB('[]');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO (' || SQLCODE || '): ' || SQLERRM);
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_TEMPORADAS_LISTAR_FN;

FUNCTION FIDE_CONSULTAS_POSICIONES_LISTAR_FN
RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_POSICIONES IS
        SELECT JSON_OBJECT(
            'ID_POSICION' VALUE ID_POSICION,
            'NOMBRE_POSICION' VALUE NOMBRE_POSICION
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_POSICIONES_V
        WHERE ID_ESTADO = 1
        ORDER BY NOMBRE_POSICION;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);

    FOR POS IN C_POSICIONES LOOP
        FIDE_JSON_AGREGAR(V_JSON, POS.ITEM, V_PRIMER_ITEM);
    END LOOP;

    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN TO_CLOB('[]');
    WHEN TOO_MANY_ROWS THEN
        RETURN TO_CLOB('[]');
    WHEN VALUE_ERROR THEN
        RETURN TO_CLOB('[]');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO (' || SQLCODE || '): ' || SQLERRM);
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_POSICIONES_LISTAR_FN;

FUNCTION FIDE_CONSULTAS_CATEGORIAS_LISTAR_FN
RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_CATEGORIAS IS
        SELECT JSON_OBJECT(
            'ID_CATEGORIA' VALUE ID_CATEGORIA,
            'NOMBRE_CATEGORIA' VALUE NOMBRE_CATEGORIA
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_CATEGORIAS_V
        WHERE ID_ESTADO = 1
        ORDER BY NOMBRE_CATEGORIA;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);

    FOR CAT IN C_CATEGORIAS LOOP
        FIDE_JSON_AGREGAR(V_JSON, CAT.ITEM, V_PRIMER_ITEM);
    END LOOP;

    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN TO_CLOB('[]');
    WHEN TOO_MANY_ROWS THEN
        RETURN TO_CLOB('[]');
    WHEN VALUE_ERROR THEN
        RETURN TO_CLOB('[]');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO (' || SQLCODE || '): ' || SQLERRM);
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_CATEGORIAS_LISTAR_FN;

FUNCTION FIDE_CONSULTAS_PARTIDOS_BUSCAR_FN(
    P_ANIO IN FIDE_TEMPORADAS_TB.ANIO%TYPE,
    P_ID_TEMPORADA IN FIDE_TEMPORADAS_TB.ID_TEMPORADA%TYPE,
    P_RIVAL IN FIDE_PARTIDOS_TB.RIVAL%TYPE,
    P_FECHA IN VARCHAR2,
    P_RESULTADO IN VARCHAR2
)
RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_PARTIDOS IS
        SELECT JSON_OBJECT(
            'ID_PARTIDO' VALUE P.ID_PARTIDO,
            'ID_CATEGORIA' VALUE P.ID_CATEGORIA,
            'ID_TIPOPARTIDOS' VALUE P.ID_TIPOPARTIDOS,
            'ID_TEMPORADA' VALUE P.ID_TEMPORADA,
            'TIPO_TEMPORADA' VALUE T.TIPO_TEMPORADA,
            'TEMPORADA_ANIO' VALUE T.ANIO,
            'FECHA' VALUE P.FECHA,
            'RIVAL' VALUE P.RIVAL,
            'GOLES_FAVOR' VALUE P.GOLES_FAVOR,
            'GOLES_CONTRA' VALUE P.GOLES_CONTRA,
            'ID_SEDE' VALUE P.ID_SEDE,
            'RESULTADO' VALUE FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_PARTIDOS_TB_RESULTADO_PARTIDO_FN(P.ID_PARTIDO),
            'TOTAL_ASISTENCIA' VALUE FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_ASISTENCIA_TB_TOTAL_ASISTENCIA_PARTIDO_FN(P.ID_PARTIDO)
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_PARTIDOS_V P
        LEFT JOIN FIDE_TEMPORADAS_V T ON T.ID_TEMPORADA = P.ID_TEMPORADA
        WHERE (P_ANIO IS NULL OR EXTRACT(YEAR FROM P.FECHA) = P_ANIO)
          AND (P_ID_TEMPORADA IS NULL OR P.ID_TEMPORADA = P_ID_TEMPORADA)
          AND (P_RIVAL IS NULL OR UPPER(P.RIVAL) LIKE '%' || UPPER(P_RIVAL) || '%')
          AND (P_FECHA IS NULL OR TRUNC(P.FECHA) = TO_DATE(P_FECHA, 'YYYY-MM-DD'))
          AND (
                P_RESULTADO IS NULL
                OR (P_RESULTADO = 'ganado' AND P.GOLES_FAVOR > P.GOLES_CONTRA)
                OR (P_RESULTADO = 'perdido' AND P.GOLES_FAVOR < P.GOLES_CONTRA)
                OR (P_RESULTADO = 'empate' AND P.GOLES_FAVOR = P.GOLES_CONTRA)
              )
        ORDER BY P.FECHA DESC, P.ID_PARTIDO DESC;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);

    FOR PARTIDO IN C_PARTIDOS LOOP
        FIDE_JSON_AGREGAR(V_JSON, PARTIDO.ITEM, V_PRIMER_ITEM);
    END LOOP;

    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN TO_CLOB('[]');
    WHEN TOO_MANY_ROWS THEN
        RETURN TO_CLOB('[]');
    WHEN VALUE_ERROR THEN
        RETURN TO_CLOB('[]');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO (' || SQLCODE || '): ' || SQLERRM);
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_PARTIDOS_BUSCAR_FN;

FUNCTION FIDE_CONSULTAS_JUGADORES_BUSCAR_FN(
    P_NOMBRE IN FIDE_JUGADORES_TB.NOMBRE%TYPE,
    P_ID_CATEGORIA IN FIDE_CATEGORIAS_TB.ID_CATEGORIA%TYPE,
    P_CEDULA IN FIDE_JUGADORES_TB.CEDULA%TYPE,
    P_ID_POSICION IN FIDE_POSICIONES_TB.ID_POSICION%TYPE
)
RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_JUGADORES IS
        SELECT JSON_OBJECT(
            'ID_JUGADOR' VALUE J.ID_JUGADOR,
            'CEDULA' VALUE J.CEDULA,
            'ID_CATEGORIA' VALUE J.ID_CATEGORIA,
            'NOMBRE_CATEGORIA' VALUE J.NOMBRE_CATEGORIA,
            'NOMBRE' VALUE J.NOMBRE,
            'APELLIDO_PATERNO' VALUE J.APELLIDO_PATERNO,
            'APELLIDO_MATERNO' VALUE J.APELLIDO_MATERNO,
            'DORSAL' VALUE J.DORSAL,
            'POSICIONES' VALUE (
                SELECT LISTAGG(JP.NOMBRE_POSICION, ', ') WITHIN GROUP (ORDER BY JP.NOMBRE_POSICION)
                FROM FIDE_JUGADOR_POSICIONES_CONSULTA_V JP
                WHERE JP.ID_JUGADOR = J.ID_JUGADOR
            )
            RETURNING CLOB
        ) AS ITEM
        FROM FIDE_JUGADORES_CONSULTA_V J
        WHERE J.ID_ESTADO = 1
          AND (P_NOMBRE IS NULL OR UPPER(J.NOMBRE || ' ' || J.APELLIDO_PATERNO || ' ' || J.APELLIDO_MATERNO) LIKE '%' || UPPER(P_NOMBRE) || '%')
          AND (P_ID_CATEGORIA IS NULL OR J.ID_CATEGORIA = P_ID_CATEGORIA)
          AND (P_CEDULA IS NULL OR UPPER(J.CEDULA) LIKE '%' || UPPER(P_CEDULA) || '%')
          AND (
                P_ID_POSICION IS NULL
                OR EXISTS (
                    SELECT 1
                    FROM FIDE_JUGADOR_POSICIONES_CONSULTA_V JP_FILTER
                    WHERE JP_FILTER.ID_JUGADOR = J.ID_JUGADOR
                      AND JP_FILTER.ID_POSICION = P_ID_POSICION
                  )
              )
        ORDER BY J.APELLIDO_PATERNO, J.NOMBRE;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);

    FOR JUGADOR IN C_JUGADORES LOOP
        FIDE_JSON_AGREGAR(V_JSON, JUGADOR.ITEM, V_PRIMER_ITEM);
    END LOOP;

    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN TO_CLOB('[]');
    WHEN TOO_MANY_ROWS THEN
        RETURN TO_CLOB('[]');
    WHEN VALUE_ERROR THEN
        RETURN TO_CLOB('[]');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO (' || SQLCODE || '): ' || SQLERRM);
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_JUGADORES_BUSCAR_FN;

FUNCTION FIDE_CONSULTAS_JUGADOR_RESUMEN_FN(
    P_ID_JUGADOR IN FIDE_JUGADORES_TB.ID_JUGADOR%TYPE
)
RETURN CLOB
IS
    V_JSON CLOB;
    V_PRIMER_ITEM BOOLEAN := TRUE;

    CURSOR C_RESUMEN IS
        SELECT JSON_OBJECT(
            'ID_JUGADOR' VALUE J.ID_JUGADOR,
            'CEDULA' VALUE J.CEDULA,
            'ID_CATEGORIA' VALUE J.ID_CATEGORIA,
            'NOMBRE_CATEGORIA' VALUE J.NOMBRE_CATEGORIA,
            'NOMBRE' VALUE J.NOMBRE,
            'APELLIDO_PATERNO' VALUE J.APELLIDO_PATERNO,
            'APELLIDO_MATERNO' VALUE J.APELLIDO_MATERNO,
            'DORSAL' VALUE J.DORSAL,
            'FECHA_NACIMIENTO' VALUE J.FECHA_NACIMIENTO,
            'POSICIONES' VALUE (
                SELECT LISTAGG(JP.NOMBRE_POSICION, ', ') WITHIN GROUP (ORDER BY JP.NOMBRE_POSICION)
                FROM FIDE_JUGADOR_POSICIONES_CONSULTA_V JP
                WHERE JP.ID_JUGADOR = J.ID_JUGADOR
            ),
            'DORSAL_FUNCION' VALUE FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_JUGADORES_TB_DORSALES_LISTAR_FN(J.ID_JUGADOR),
            'GOLES' VALUE FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_ESTADISTICA_JUGADOR_TB_TOTAL_GOLES_JUGADOR_FN(J.ID_JUGADOR),
            'ASISTENCIAS' VALUE FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_ESTADISTICA_JUGADOR_TB_TOTAL_ASISTENCIAS_JUGADOR_FN(J.ID_JUGADOR),
            'PASES_TOTALES' VALUE NVL((SELECT SUM(S.PASES) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 0),
            'PASES_EXITOSOS_TOTALES' VALUE NVL((SELECT SUM(S.PASES_EXITOSOS) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 0),
            'REGATES_TOTALES' VALUE NVL((SELECT SUM(S.REGATES) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 0),
            'REGATES_EXITOSOS_TOTALES' VALUE NVL((SELECT SUM(S.REGATES_EXITOSOS) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 0),
            'TIROS_TOTALES' VALUE NVL((SELECT SUM(S.TIROS) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 0),
            'TIROS_EXITOSOS_TOTALES' VALUE NVL((SELECT SUM(S.TIROS_EXITOSOS) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 0),
            'ENTRADAS_TOTALES' VALUE NVL((SELECT SUM(S.ENTRADAS) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 0),
            'ENTRADAS_EXITOSAS_TOTALES' VALUE NVL((SELECT SUM(S.ENTRADAS_EXITOSAS) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 0),
            'MINUTOS_TOTALES' VALUE NVL((SELECT SUM(S.MINUTOS_JUGADOS) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 0),
            'PROMEDIO_PASES_EXITOSOS' VALUE NVL(ROUND((SELECT AVG(S.PASES_EXITOSOS) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 2), 0),
            'PROMEDIO_REGATES_EXITOSOS' VALUE NVL(ROUND((SELECT AVG(S.REGATES_EXITOSOS) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 2), 0),
            'PROMEDIO_TIROS_EXITOSOS' VALUE NVL(ROUND((SELECT AVG(S.TIROS_EXITOSOS) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 2), 0),
            'PROMEDIO_ENTRADAS_EXITOSAS' VALUE NVL(ROUND((SELECT AVG(S.ENTRADAS_EXITOSAS) FROM FIDE_ESTADISTICA_JUGADOR_CONSULTA_V S WHERE S.ID_JUGADOR = J.ID_JUGADOR), 2), 0),
            'TARJETAS' VALUE FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_TARJETAS_TB_TOTAL_TARJETAS_JUGADOR_FN(J.ID_JUGADOR),
            'TARJETAS_AMARILLAS' VALUE NVL((
                SELECT SUM(T.CANTIDAD_TARJETAS)
                FROM FIDE_TARJETAS_TB T
                JOIN FIDE_TIPOTARJETAS_TB TT ON TT.ID_TIPOTARJETA = T.ID_TIPOTARJETA
                WHERE T.ID_JUGADOR = J.ID_JUGADOR
                  AND T.ID_ESTADO = 1
                  AND UPPER(TT.COLOR) LIKE '%AMARILL%'
            ), 0),
            'TARJETAS_ROJAS' VALUE NVL((
                SELECT SUM(T.CANTIDAD_TARJETAS)
                FROM FIDE_TARJETAS_TB T
                JOIN FIDE_TIPOTARJETAS_TB TT ON TT.ID_TIPOTARJETA = T.ID_TIPOTARJETA
                WHERE T.ID_JUGADOR = J.ID_JUGADOR
                  AND T.ID_ESTADO = 1
                  AND UPPER(TT.COLOR) LIKE '%ROJ%'
            ), 0),
            'MONTO_PAGADO' VALUE FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_FACTURACION_TB_MONTO_PAGADO_JUGADOR_FN(J.ID_JUGADOR),
            'LESIONES' VALUE FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_PARTE_MEDICO_TB_TOTAL_LESIONES_JUGADOR_FN(J.ID_JUGADOR),
            'PROMEDIO_MINUTOS' VALUE FIDE_PROYECTOFINALACADEMIALEIVA_PCK.FIDE_ESTADISTICA_JUGADOR_TB_PROMEDIO_MINUTOS_JUGADOS_FN(J.ID_JUGADOR),
            'PARTIDOS_JUGADOS' VALUE (
                SELECT COUNT(DISTINCT A.ID_PARTIDO)
                FROM FIDE_ASISTENCIA_V A
                WHERE A.ID_JUGADOR = J.ID_JUGADOR
            ),
            'PARTIDOS_GANADOS' VALUE (
                SELECT COUNT(DISTINCT A.ID_PARTIDO)
                FROM FIDE_ASISTENCIA_V A
                JOIN FIDE_PARTIDOS_V P ON P.ID_PARTIDO = A.ID_PARTIDO
                WHERE A.ID_JUGADOR = J.ID_JUGADOR
                  AND P.GOLES_FAVOR > P.GOLES_CONTRA
            ),
            'PARTIDOS_PERDIDOS' VALUE (
                SELECT COUNT(DISTINCT A.ID_PARTIDO)
                FROM FIDE_ASISTENCIA_V A
                JOIN FIDE_PARTIDOS_V P ON P.ID_PARTIDO = A.ID_PARTIDO
                WHERE A.ID_JUGADOR = J.ID_JUGADOR
                  AND P.GOLES_FAVOR < P.GOLES_CONTRA
            )
            RETURNING CLOB
        ) AS ITEM
            FROM FIDE_JUGADORES_CONSULTA_V J
            WHERE J.ID_JUGADOR = P_ID_JUGADOR
              AND J.ID_ESTADO = 1;
BEGIN
    FIDE_JSON_INICIAR(V_JSON);

    FOR RESUMEN IN C_RESUMEN LOOP
        FIDE_JSON_AGREGAR(V_JSON, RESUMEN.ITEM, V_PRIMER_ITEM);
    END LOOP;

    FIDE_JSON_CERRAR(V_JSON);
    RETURN V_JSON;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN TO_CLOB('[]');
    WHEN TOO_MANY_ROWS THEN
        RETURN TO_CLOB('[]');
    WHEN VALUE_ERROR THEN
        RETURN TO_CLOB('[]');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO (' || SQLCODE || '): ' || SQLERRM);
        RETURN TO_CLOB('[]');
END FIDE_CONSULTAS_JUGADOR_RESUMEN_FN;
