-- Valores iniciales calculados como MAX(ID) + 1 a partir de los inserts.
-- Ejecutar este script despues de cargar los datos y antes de insertar nuevos registros.

CREATE SEQUENCE ID_ESTADO_SEQ
START WITH 12
INCREMENT BY 1;

CREATE SEQUENCE ID_TIPOTARJETA_SEQ
START WITH 3
INCREMENT BY 1;

CREATE SEQUENCE ID_CANTON_SEQ
START WITH 37
INCREMENT BY 1;

CREATE SEQUENCE ID_CARGO_SEQ
START WITH 5
INCREMENT BY 1;

CREATE SEQUENCE ID_CATEGORIA_SEQ
START WITH 10
INCREMENT BY 1;

CREATE SEQUENCE ID_CATEGORIAINVENTARIO_SEQ
START WITH 6
INCREMENT BY 1;

CREATE SEQUENCE ID_DISTRITO_SEQ
START WITH 353
INCREMENT BY 1;

CREATE SEQUENCE ID_ESPECIALIDAD_SEQ
START WITH 8
INCREMENT BY 1;

CREATE SEQUENCE ID_POSICION_SEQ
START WITH 16
INCREMENT BY 1;

CREATE SEQUENCE ID_PROVINCIA_SEQ
START WITH 8
INCREMENT BY 1;

CREATE SEQUENCE ID_TEMPORADA_SEQ
START WITH 9
INCREMENT BY 1;

CREATE SEQUENCE ID_TIPOLESION_SEQ
START WITH 10
INCREMENT BY 1;

CREATE SEQUENCE ID_TIPOPARTIDOS_SEQ
START WITH 3
INCREMENT BY 1;

CREATE SEQUENCE ID_ARTICULO_SEQ
START WITH 51
INCREMENT BY 1;

CREATE SEQUENCE ID_DIRECCION_EXACTA_SEQ
START WITH 1053
INCREMENT BY 1;

CREATE SEQUENCE ID_MEDICO_SEQ
START WITH 15
INCREMENT BY 1;

CREATE SEQUENCE ID_EMPLEADO_SEQ
START WITH 8
INCREMENT BY 1;

CREATE SEQUENCE ID_JUGADOR_SEQ
START WITH 100
INCREMENT BY 1;

CREATE SEQUENCE ID_FACTURACION_INSCRIPCION_SEQ
START WITH 1189
INCREMENT BY 1;

CREATE SEQUENCE ID_SEDE_SEQ
START WITH 4
INCREMENT BY 1;

CREATE SEQUENCE ID_PARTEMEDICO_SEQ
START WITH 31
INCREMENT BY 1;

CREATE SEQUENCE ID_PARTIDO_SEQ
START WITH 37
INCREMENT BY 1;

CREATE SEQUENCE ID_REVISION_SEQ
START WITH 100
INCREMENT BY 1;

CREATE SEQUENCE ID_TELEFONO_SEQ
START WITH 15
INCREMENT BY 1;

CREATE SEQUENCE ID_ESTADISTICA_EQUIPO_SEQ
START WITH 37
INCREMENT BY 1;

CREATE SEQUENCE ID_ESTADISTICA_JUGADOR_SEQ
START WITH 397
INCREMENT BY 1;

CREATE SEQUENCE ID_LESION_SEQ
START WITH 41
INCREMENT BY 1;
