-- Triggers corregidos para permitir IDs explicitos y generarlos solo cuando
-- el INSERT no recibe un valor.

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_ESTADO IS NULL THEN
        :NEW.ID_ESTADO := ID_ESTADO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ESTADOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPOTARJETAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TIPOTARJETAS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPOTARJETA IS NULL THEN
        :NEW.ID_TIPOTARJETA := ID_TIPOTARJETA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TIPOTARJETAS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CANTONES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_CANTON IS NULL THEN
        :NEW.ID_CANTON := ID_CANTON_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_CANTONES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CARGOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CARGOS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_CARGO IS NULL THEN
        :NEW.ID_CARGO := ID_CARGO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_CARGOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_CATEGORIA IS NULL THEN
        :NEW.ID_CATEGORIA := ID_CATEGORIA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_CATEGORIAS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_INVENTARIO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CATEGORIA_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_CATEGORIAINVENTARIO IS NULL THEN
        :NEW.ID_CATEGORIAINVENTARIO := ID_CATEGORIAINVENTARIO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_CATEGORIA_INVENTARIO_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_DISTRITO IS NULL THEN
        :NEW.ID_DISTRITO := ID_DISTRITO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_DISTRITOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESPECIALIDADES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ESPECIALIDADES_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_ESPECIALIDAD IS NULL THEN
        :NEW.ID_ESPECIALIDAD := ID_ESPECIALIDAD_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ESPECIALIDADES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_POSICIONES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_POSICIONES_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_POSICION IS NULL THEN
        :NEW.ID_POSICION := ID_POSICION_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_POSICIONES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_PROVINCIA IS NULL THEN
        :NEW.ID_PROVINCIA := ID_PROVINCIA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_PROVINCIAS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TEMPORADAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TEMPORADAS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TEMPORADA IS NULL THEN
        :NEW.ID_TEMPORADA := ID_TEMPORADA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TEMPORADAS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPOLESION_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TIPOLESION_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPOLESION IS NULL THEN
        :NEW.ID_TIPOLESION := ID_TIPOLESION_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TIPOLESION_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_PARTIDOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_PARTIDOS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPOPARTIDOS IS NULL THEN
        :NEW.ID_TIPOPARTIDOS := ID_TIPOPARTIDOS_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TIPO_PARTIDOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ARTICULOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ARTICULOS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_ARTICULO IS NULL THEN
        :NEW.ID_ARTICULO := ID_ARTICULO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ARTICULOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_EXACTA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_DIRECCION_EXACTA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_DIRECCION_EXACTA IS NULL THEN
        :NEW.ID_DIRECCION_EXACTA := ID_DIRECCION_EXACTA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_DIRECCION_EXACTA_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MEDICOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_MEDICOS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_MEDICO IS NULL THEN
        :NEW.ID_MEDICO := ID_MEDICO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_MEDICOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EMPLEADOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_EMPLEADOS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_EMPLEADO IS NULL THEN
        :NEW.ID_EMPLEADO := ID_EMPLEADO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_EMPLEADOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_JUGADORES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_JUGADORES_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_JUGADOR IS NULL THEN
        :NEW.ID_JUGADOR := ID_JUGADOR_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_JUGADORES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURACION_INSCRIPCIONES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_FACTURACION_INSCRIPCIONES_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_FACTURACION_INSCRIPCION IS NULL THEN
        :NEW.ID_FACTURACION_INSCRIPCION := ID_FACTURACION_INSCRIPCION_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_FACTURACION_INSCRIPCIONES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEDES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_SEDES_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_SEDE IS NULL THEN
        :NEW.ID_SEDE := ID_SEDE_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_SEDES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_JUGADOR_POSICIONES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_JUGADOR_POSICIONES_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_JUGADOR_POSICIONES_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PARTE_MEDICO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_PARTE_MEDICO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_PARTEMEDICO IS NULL THEN
        :NEW.ID_PARTEMEDICO := ID_PARTEMEDICO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_PARTE_MEDICO_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PARTIDOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_PARTIDOS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_PARTIDO IS NULL THEN
        :NEW.ID_PARTIDO := ID_PARTIDO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_PARTIDOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_REVISION_FISICA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_REVISION_FISICA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_REVISION IS NULL THEN
        :NEW.ID_REVISION := ID_REVISION_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_REVISION_FISICA_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TELEFONOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TELEFONOS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TELEFONO IS NULL THEN
        :NEW.ID_TELEFONO := ID_TELEFONO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TELEFONOS_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ASISTENCIA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ASISTENCIA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ASISTENCIA_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADISTICA_EQUIPO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADISTICA_EQUIPO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_ESTADISTICA_EQUIPO IS NULL THEN
        :NEW.ID_ESTADISTICA_EQUIPO := ID_ESTADISTICA_EQUIPO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ESTADISTICA_EQUIPO_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADISTICA_JUGADOR_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADISTICA_JUGADOR_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_ESTADISTICA_JUGADOR IS NULL THEN
        :NEW.ID_ESTADISTICA_JUGADOR := ID_ESTADISTICA_JUGADOR_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ESTADISTICA_JUGADOR_TB_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_LESIONES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_LESIONES_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_LESION IS NULL THEN
        :NEW.ID_LESION := ID_LESION_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_LESIONES_TB_INSERT_TRG;
/

-- TARJETAS usa una clave primaria compuesta: no tiene ID_TARJETA ni secuencia.
CREATE OR REPLACE TRIGGER FIDE_TARJETAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TARJETAS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP - INTERVAL '6' HOUR;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_TARJETAS_TB_INSERT_TRG;
/
