-- Vistas de lectura para las tablas que integran DIRECCION_EXACTA.
-- No modifican datos ni reemplazan los procedimientos de insercion/actualizacion.

CREATE OR REPLACE FORCE VIEW FIDE_SEDES_CON_DIRECCION_V AS
SELECT
    S.*,
    D.ID_PROVINCIA AS DIRECCION_ID_PROVINCIA,
    D.ID_CANTON AS DIRECCION_ID_CANTON,
    D.ID_DISTRITO AS DIRECCION_ID_DISTRITO,
    D.OTRAS_SENIAS AS DIRECCION_OTRAS_SENIAS
FROM FIDE_SEDES_V S
LEFT JOIN FIDE_DIRECCION_EXACTA_V D
    ON D.ID_DIRECCION_EXACTA = S.ID_DIRECCION_EXACTA;

CREATE OR REPLACE FORCE VIEW FIDE_EMPLEADOS_CON_DIRECCION_V AS
SELECT
    E.*,
    D.ID_PROVINCIA AS DIRECCION_ID_PROVINCIA,
    D.ID_CANTON AS DIRECCION_ID_CANTON,
    D.ID_DISTRITO AS DIRECCION_ID_DISTRITO,
    D.OTRAS_SENIAS AS DIRECCION_OTRAS_SENIAS
FROM FIDE_EMPLEADOS_V E
LEFT JOIN FIDE_DIRECCION_EXACTA_V D
    ON D.ID_DIRECCION_EXACTA = E.ID_DIRECCION_EXACTA;

CREATE OR REPLACE FORCE VIEW FIDE_JUGADORES_CON_DIRECCION_V AS
SELECT
    J.*,
    D.ID_PROVINCIA AS DIRECCION_ID_PROVINCIA,
    D.ID_CANTON AS DIRECCION_ID_CANTON,
    D.ID_DISTRITO AS DIRECCION_ID_DISTRITO,
    D.OTRAS_SENIAS AS DIRECCION_OTRAS_SENIAS
FROM FIDE_JUGADORES_V J
LEFT JOIN FIDE_DIRECCION_EXACTA_V D
    ON D.ID_DIRECCION_EXACTA = J.ID_DIRECCION_EXACTA;
